ruby/prism

- config.yml
- src/parser.h
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
This PR implements parsing for loops in the structure:
```ruby
for i in 0..10 do
i # or some other expression here
end
```
This PR handles multiple indexes e.g. `for i, j in 0..10` and makes error handling more robust.
> Parse for loops

- config.yml
- src/yarp.c
- test/parse_test.rb
Closes #118 
This PR implements parsing for dynamic symbols:
```ruby 
:'abc'
:"abc#{123}"
alias :'abc' :'def'
undef :"abc#{123}"
```
> Implement dynamic symbols

- src/yarp.c
- test/parse_test.rb
closes: https://github.com/Shopify/yarp/issues/131
I attempted to shape the structure close to the current parse tree dump shape:
```
ruby --dump=parsetree -e "%I[a b#{2} c]"
###########################################################
###########################################################
```
This way symbol literal nodes are still just symbol nodes unless they are using interpolation.
> Handle %I interpolated symbols

- config.yml
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
Expressions in parentheses get their own node which wraps the expression in it.
> Improve parenthesized expression handling

- bin/template.rb
- bin/templates/src/node.c.erb
- config.yml
- src/yarp.c
- test/parse_test.rb
* No longer accept `yp_string_t*` when creating nodes, instead they live directly on the node so just initialize them after the node has been allocated.
* Start handling escape characters by adding a `yp_string_t` child onto `StringNode`
> String updates

- config.yml
- src/yarp.c
- test/parse_test.rb
Added support for `**nil`, please let me know if the test is correct (maybe we want to wrap in `NilNode`?)
Closes #160
> Support **nil in method signature

- src/parser.h
- src/yarp.c
Previously we had interp and term on every lex mode, even when they weren't being used. Now we've got a union in order to pave the way for some of the additionally metadata we're going to need to store to support heredocs.
@iliabylich I think this is the direction you meant a while ago when you mentioned we needed a union here.
> Union on lex modes

- config.yml
- src/yarp.c
- test/parse_test.rb
I still want to add metadata onto the __FILE__ and __LINE__ nodes that has their actual information, but this is a good start.
Closes #163
> Nodes for __ENCODING__, __FILE__, and __LINE__

- bin/template.rb
- config.yml
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
Closes #114
Related changes:
- Updated string parsing code to create an `InterpolatedStringNode` only if the string has interpolation
- Modified regex in `bin/template.rb` to use a positive lookbehind so that in `InterpolatedXStringNode` the letters `X` and `S` are handled individually, resulting in `Interpolated_X_String_Node` instead of `Interpolated_XString_Node`
> Implement xstrings

- config.yml
- src/yarp.c
- test/parse_test.rb
Adds support for syntax like, `[*a]`
> Add support for array splats

- config.yml
- src/parser.h
- src/yarp.c
- test/parse_test.rb
Fixes: https://github.com/Shopify/yarp/issues/209
```
begin; a; rescue; b; else; c; ensure; d; end
```
becomes,
```
BeginNode(
KEYWORD_BEGIN("begin"),
Statements([CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, "a")]),
RescueNode(
KEYWORD_RESCUE("rescue"),
[],
nil,
nil,
Statements([CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, "b")]),
nil
),
ElseNode(
KEYWORD_ELSE("else"),
Statements([CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, "c")]),
SEMICOLON(";")
),
EnsureNode(
KEYWORD_ENSURE("ensure"),
Statements([CallNode(nil, nil, IDENTIFIER("d"), nil, nil, nil, "d")]),
KEYWORD_END("end")
),
nil
)
```
> Add support for rescue else syntax

- config.yml
- src/yarp.c
- test/parse_test.rb
This PR contains implementation for calling a method with unnamed rest parameter.
```ruby
def foo(*)
bar(*)
end
```
The behavior is very similar to the forwarding parameter `...`.
> Implement calling with unnamed rest parameter 

- src/yarp.c
- test/parse_test.rb
{
}
and
[
]
previously the above parsed as a missing key, instead this should now successfully return an empty hash node.
> Improve whitespace handling in hash literals

- src/yarp.c
- test/parse_test.rb
I ran into an example like,
```
{ foo: "bar" +
"baz"
}
```
which fails looking for the argument after the `+`. 
I believe all of these operators are fine with whitespace here, but I didn't test all of them.
> Fix small issue when parsing multiline string addition

- config.yml
- src/parser.h
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
This adds support for block arguments syntax. Focusing on `do/end` and `{/}` blocks with `|` variables.
> Support block with braces

- .github/workflows/package-vscode.yml
Off the back of the work to [add an LSP + VSCode extension](https://github.com/Shopify/yarp/pull/257), this PR adds a new workflow for packaging the extension on release.
> Add workflow to package vscode extension for release

- config.yml
- src/yarp.c
- test/parse_test.rb
Parse optional keyword parameters. This is a little bit more tricky than parsing optional default parameters because there is no straight forward way to tell if a keyword parameter is optional or not and the behaviour also differs depending on wether the method parameters are defined with or without parenthesis. For more context see https://github.com/Shopify/yarp/pull/239.
> Parse optional keyword parameters

- bin/template.rb
- bin/templates/ext/yarp/node.c.erb
- bin/templates/java/org/yarp/Loader.java.erb
- bin/templates/lib/yarp/serialize.rb.erb
- bin/templates/src/ast.h.erb
- bin/templates/src/node.c.erb
- bin/templates/src/prettyprint.c.erb
- bin/templates/src/serialize.c.erb
- config.yml
- docs/heredocs.md
- lib/yarp.rb
- src/parser.h
- src/util/yp_buffer.c
- src/util/yp_buffer.h
- src/yarp.c
- test/parse_test.rb
This PR introduces the concept of parsing heredocs. It specifically _doesn't_ handle a couple of cases, including:
* Nested heredocs (i.e., a heredoc interpolated into another heredoc)
* Heredocs with quotes on their declarations (e.g., ``<<-`FOO` ``, `<<-'FOO'`, and `<<-"FOO"`)
* Dedenting heredocs (e.g., `<<~FOO`)
* Heredocs that don't start at the beginning of the line
> Heredoc beginnings

- src/yarp.c
- src/yarp.h
We need to treat comments effectively as newlines, but still have the lex callback fire off comment events.
> Lex comments properly

- config.yml
- src/yarp.c
- test/parse_test.rb
This commit fixes a couple of memory leaks in YARP. They include:
* The LambdaNode type parses its scope using a Scope node, but does not retain a pointer to it. As such, the scope gets allocated but never deallocated. Instead, we now hold onto it and release it when the overall tree is deallocated.
* When parsing bare hashes as arguments, the first association in the hash was always being dropped. This is now fixed, the tests are fixed, and the memory leak is fixed.
* When creating a rescue node, the statements was being allocated on its own and then immediately discarded without deallocating. We now manually deallocate it, but this is something that we need to fix in a future PR because there's no reason to create one in the first place.
* ForNode nodes were parsing their locals with a …
> Fix memory leaks

- src/yarp.c
`hi&.there`
before:
```
Ripper lex                                                             YARP lex                                                              
---------------------------------------------------------------------- ----------------------------------------------------------------------
[[1, 0], :on_ident, "hi", CMDARG]                                      [[1, 0], :on_ident, "hi", CMDARG]                                     
[[1, 2], :on_op, "&.", DOT]                                            [[1, 2], :on_op, "&.", CMDARG]                                        
[[1, 4], :on_ident, "there", ARG]                                      [[1, 4], :on_ident, "there", ARG]                                     
[[1, 9], :on_nl, "\n", BEG] …
```
> Fix state on &. tokens

- src/yarp.c
- test/parse_test.rb
```
foo(:a, :b, :c,)
```
becomes:
```
CallNode(
nil,
nil,
IDENTIFIER("foo"),
PARENTHESIS_LEFT("("),
ArgumentsNode(
[SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil),
HashNode(
nil,
[AssocNode(
SymbolNode(nil, LABEL("b"), LABEL_END(":")),
SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("c"), nil),
nil
)],
nil
)]
),
PARENTHESIS_RIGHT(")"),
nil,
"foo"
)
```
> Support trailing commas in arguments

- src/yarp.c
- test/parse_test.rb
parse statements needs the newline to still be `parser->current` to know we are done with the return line.
> support return with trailing conditional

- Rakefile
- config.yml
- src/yarp.c
- test/parse_test.rb
* The statements on the `else` node need to be marked as optional.
* We need to optionally accept the `then` keyword after the `when` clause predicates.
* We need to expect a predicate after the `when` keyword.
* The rakefile now automatically prints out the percentage passed.
* The `when` keyword should default to the `beg` state after it is lexed.
> Fixes for the case keyword

- src/yarp.c
Now we're more accurately mirroring the lex state from CRuby when lexing ? characters.
> Fix question mark lexing

- src/yarp.c
- test/parse_test.rb
This PR fixes parsing
```ruby
case arg
when foo
:a
else
:b
end
```
However, I am not sure about what should be the `end_keyword` of the `ElseNode` here. Currently it is `newline` but I don't know whether this is OK. On the other hand I see that `CaseNode` also has an `end_keyword` child, so in this case I don't know what the last `end` token should be part of, should it be part of `CaseNode` or `ElseNode`?
> Fix case-else with else containing statements

- Rakefile
- bin/lex
- docs/extension.md
- ext/yarp/extension.c
- lib/yarp.rb
- lib/yarp/ripper_compat.rb
- test/errors_test.rb
- test/location_test.rb
- test/parse_test.rb
Previously, we only returned an array of tokens when we lexed. This could be misleading, since the parser could have gathered up errors and warnings without it being known to the consumer. Now when we call lex or lex_compat, we return a ParseResult that contains the tokens as well as errors, warnings, and comments.
As a part of this, we know ensure we don't have any errors when we call `rake lex`, which actually has made our percentage drop to 79% from 80%, presumably because there are a couple of files where we matched the lexer output but didn't correctly match the parser output.
> Results for lexing

- src/yarp.c
Just replaces direct `parser->lex_state` assignments with calling `lex_state_set`.
> Replace direct `parser->lex_state` assignments with `lex_state_set`

- src/yarp.c
- test/parse_test.rb
Fixes argument parsing in codes like:
```ruby
if exit_loop then break 42 end
```
> Fix argument parsing in if-then blocks

- src/yarp.c
Takes `rake lex` from 85.24% -> 85.6%
Closes #351
> Remove extraneous state set in :: case

- .github/workflows/main.yml
- Rakefile
- config.yml
- ext/yarp/extension.c
- lib/yarp.rb
- src/yarp.c
- test/parse_test.rb
This PR introduces multiple assignment. There are two kinds.
The first is multiple assignment where you have multiple values on the left-hand side of the expression. This looks like:
```ruby
@foo, bar =
@@foo, bar =
$foo, bar =
```
and many others. To accomplish this, we've repurposed the previously-named `MultiTargetNode` to now be a `MultiWriteNode`. All of the examples in the above are `MultiWriteNode`s. It has an array of targets (in the first line, it would be a `InstanceVariableWriteNode` and a `LocalVariableWriteNode`, both will `nil` for their values), an operator, and a value.
The second is when you have multiple-values on the right-hand side of the expression. This looks like:
```ruby
foo = 1, 2, 3
@foo = 1, 2, 3
```
This is effectively the same thing as assigning an array …
> Multi assign

- src/yarp.c
- test/parse_test.rb
Fixes parsing array literals with labels, so we should parse this
```ruby
[a: [:b, :c]]
```
but **not** this
```ruby
[a: [:b, :c], :d]
```
> Fix array literals with labels

- lib/yarp.rb
- src/yarp.c
Also heredocs should be able to start based on `on_ignored_nl`
> Fix the states for interpolation, __END__, "#", ~@, &=, and `

- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
Fixes parsing:
```ruby
foo :a if b?
foo :a unless b?
foo :a until b?
foo :a while b?
```
The following should also be parsed but I couldn't fix it:
```ruby
foo :a rescue :b
```
Takes `rake lex` from `88.87%` to `89.24%`.
> Fix parsing modifiers with arguments to call

- Rakefile
- bin/lex
- lib/yarp.rb
- src/yarp.c
- test/parse_test.rb
Tilde heredocs dedent each line to the minimum amount of leading whitespace. This commit calculates that whitespace, and strips it from each line in a tilde heredoc.
Closes #309
> Implement tilde heredocs dedents

- src/yarp.c
- test/errors_test.rb
Ruby does not allow defining a module in a method body https://github.com/ruby/ruby/blob/22d944c8b76be04dc437100c46626db5fe9dd7f0/parse.y#L3514
This PR emits an error message for this case.
> Emit error message for module definition in method body

- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
Fixes parsing:
```ruby
module ::Foo
end
```
> Fix parsing module names starting with `::`

- src/util/yp_strspn.c
- src/util/yp_strspn.h
- src/yarp.c
- src/yarp.h
A lot of places we're currently looping through the input can be made more clear by using `strspn`. We can make some specialized `strspn` calls to use lookup tables with known charsets for common cases.
Also, we shouldn't return invalid tokens for numbers if they are malformed, we should just add errors to the list. Folks are going to be typing numbers from the beginning like `0x` and we know it's _going_ to be a number, so we shouldn't hurt our ability to recover.
> Replace a lot of places we're looping with strspn

- src/yarp.c
Previously when a space character was found we were subtracting min_whitespace from new_size and adding it to cur_char, but we should only do that by 1.
> Fix heredocs crash

- Rakefile
- config.yml
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
* Handle parens to start, i.e., `(foo, bar) = 1`
* Handle splats to start, i.e., `*foo = 1`
* Handle anonymous splats, i.e., `* = 1`
* Handle tons of nesting, i.e., `((foo, bar,), baz, (qux,)) = 1`
Also, this commit turns on `rake lex` in CI, ignoring the last 4 files. I'm gonna get them, but I got impatient and I introduced a regression a couple commits ago so I want CI to catch it.
> Multi write fixes

- .github/workflows/main.yml
- Rakefile
- config.yml
- lib/yarp/lex_compat.rb
- src/parser.h
- src/util/yp_strspn.c
- src/util/yp_strspn.h
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
These changes now bring us up to:
```
ruby/spec
PASSING=4661
FAILING=2
PERCENT=99.96%
rails/rails
PASSING=3049
FAILING=24
PERCENT=99.22%
ruby/ruby
PASSING=8025
FAILING=205
PERCENT=97.51%
```
Here is a list of the changes:
* Previously we only had one token for `::`, which led to some ambiguity with `foo :: Bar` (is that a constant lookup or a method call?). Now we delineate between unary `::` and binary `::` by checking the lex state (which mirrors what CRuby does).
* `lex_compat` had a bug where it wouldn't properly handle blank lines, which do not count toward common leading whitespace calculation in tilde heredocs.
* Magic comments should only be considered at the top of the file. (Previously we were checking magic comments on every comment.)
* Regular expressions now check their …
> A bunch of stuff

- src/yarp.c
- test/parse_test.rb
> Callers of parse_arguments should specify if they can accept forwarding

- config.yml
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
This commit adds unescaped strings to three more nodes, mirroring the behavior of StringNodes.
Closes #466
> Unescaped strings on RegularExpressionNode, XStringNode, SymbolNode

- src/util/yp_strpbrk.c
- src/util/yp_strpbrk.h
- src/yarp.c
- src/yarp.h
Here we have rolled our own version of `strpbrk`. The standard library `strpbrk`
has undefined behavior when the source string is not null-terminated. We want
to support strings that are not null-terminated because `yp_parse` does not
have the contract that the string is null-terminated. (This is desirable
because it means the extension can call `yp_parse` with the result of a call to
mmap).
The standard library `strpbrk` also does not support passing a maximum length
to search. We want to support this for the reason mentioned above, but we
also don't want it to stop on null bytes. Ruby actually allows null bytes
within strings, comments, regular expressions, etc. So we need to be able to
skip past them.
Fixes #406
> Implement our own strpbrk

- src/yarp.c
- test/errors_test.rb
Emit an error message when we see a 
- constant 
- instance variable
- global variable
- class variable
in the parameters list like CRuby:
```
ruby -e "def foo(A);end"                                      
-e:1: formal argument cannot be a constant
def foo(A);end
-e: compile error (SyntaxError)
```
Ref https://github.com/ruby/ruby/blob/56b38fdd69d56e8ff2ae9032fa55f2eda8bb5d63/parse.y#L5599
> Emit error messages for "bad" parameter types

- lib/yarp/lex_compat.rb
- targets.yml
Plain heredocs without `-` are not split on escaped newlines.
> PlainHeredocs versus DashHeredocs

- test/parse_test.rb
On 3.1 it fails like:
```
.............................................................F
==============================================================================================================================
Failure: test: /home/eregon/code/yarp/test/fixtures/hashes.rb(ParseTest)
/home/eregon/code/yarp/test/parse_test.rb:57:in `block (3 levels) in <class:ParseTest>'
54:       # Ripper.
55:       YARP.lex_compat(source) => { errors: [], value: tokens }
56:       YARP.lex_ripper(source).zip(tokens).each do |(ripper, yarp)|
=> 57:         assert_equal ripper, yarp
58:       end
59:     end
60:   end
/home/eregon/code/yarp/test/parse_test.rb:56:in `each'
/home/eregon/code/yarp/test/parse_test.rb:56:in `block (2 levels) in <class:ParseTest>'
<[[20, 4], :on_label_end, "\":", BEG|LABEL]> …
```
> ParseTest requires Ruby 3.2+

- src/yarp.c
> Fix up command start on blocks with trailing newlines

- docs/encoding.md
- src/enc/ascii.c
- src/enc/big5.c
- src/enc/iso_8859_1.c
- src/enc/iso_8859_10.c
- src/enc/iso_8859_11.c
- src/enc/iso_8859_13.c
- src/enc/iso_8859_14.c
- src/enc/iso_8859_15.c
- src/enc/iso_8859_16.c
- src/enc/iso_8859_2.c
- src/enc/iso_8859_3.c
- src/enc/iso_8859_4.c
- src/enc/iso_8859_5.c
- src/enc/iso_8859_6.c
- src/enc/iso_8859_7.c
- src/enc/iso_8859_8.c
- src/enc/iso_8859_9.c
- src/enc/unicode.c
- src/enc/windows_1251.c
- src/enc/windows_1252.c
- src/enc/yp_encoding.h
- src/parser.h
- src/yarp.c
* Add a new `char_width` callback on encodings to use in checking the width of a character so that we can properly parse things like `?こ`. Fixes #617.
* Fill in all of the `char_width` callbacks on existing encodings.
* Remove all the public visibility of encoding functions since we no longer need them to be public.
* Reorder the encoding checkers to check for the most common ones first.
> Encoding updates

- lib/yarp/lex_compat.rb
- targets.yml
It can get very confused based on when ripper emits it, so let's just skip comparing it.
> Don't compare heredoc end lex state

- src/yarp.c
> Fix parsing beginless range after ignored newlines

- bin/parse
- bin/templates/ext/yarp/node.c.erb
- bin/templates/java/org/yarp/Loader.java.erb
- bin/templates/lib/yarp/serialize.rb.erb
- bin/templates/src/prettyprint.c.erb
- bin/templates/src/serialize.c.erb
- src/yarp.c
* Optional locations now store `NULL` in their start and end to indicate that they were not provided.
* When they are serialized, they always serialize a single byte to indicate whether or not they are present.
* The deserializers now always read at least one byte to determine if they are present, and then read the location if it's non-zero.
Fixes #589.
> Various location fixes

- bin/parse
- config.yml
- src/yarp.c
- test/fixtures/patterns.rb
- test/snapshots/patterns.rb
The following patterns are now supported:
```ruby
foo => ^(1)
foo => ^(nil)
foo => ^("bar" + "baz")
foo => ::Foo
foo => ::Foo::Bar::Baz
foo => Foo()
foo => Foo(1)
foo => Foo(1, 2, 3)
foo => Foo(bar)
foo => Foo(*bar, baz)
foo => Foo(bar, *baz)
foo => Foo(*bar, baz, *qux)
foo => Foo[]
foo => Foo[1]
foo => Foo[1, 2, 3]
foo => Foo[bar]
foo => Foo[*bar, baz]
foo => Foo[bar, *baz]
foo => Foo[*bar, baz, *qux]
foo => *bar
foo => *bar, baz, qux
foo => bar, *baz, qux
foo => bar, baz, *qux
foo => *bar, baz, *qux
foo => []
foo => [[[[[]]]]]
foo => [*bar]
foo => [*bar, baz, qux]
foo => [bar, *baz, qux]
foo => [bar, baz, *qux]
foo => [*bar, baz, *qux]
```
> More pattern matching

- include/yarp/unescape.h
- src/unescape.c
- src/yarp.c
- test/errors_test.rb
Github issue https://github.com/Shopify/yarp/issues/569
Changes:
- add error when `?\u{nnnn}` literal contain more than one codepoint (e.g. `?\u{0000 0001}`)
- add error when `\u{nnnn}` contains more than 6 digits
- add error when `\u{nnnn}` contains not hexadecimal characters
> Fix Unicode character literal

- src/yarp.c
When looking into #659, I found that if we disable assertions, we get warnings in two places. This fixes those warnings.
> Fix assertions which were doing operations

- test/parse_test.rb
- test/snapshots/keyword_method_names.rb
- test/snapshots/keywords.rb
- test/snapshots/patterns.rb
- test/snapshots/unparser/corpus/literal/pragma.rb
- test/snapshots/whitequark/pattern_matching__FILE__LINE_literals.rb
- test/snapshots/whitequark/string___FILE__.rb
Because a string buffer is used rather than an IO device with a tty, PP determines the width from its environment.  If `ENV["COLUMNS"]` was set to anything besides `"80"`, then the snapshots will not match the `pp` output.  This will happen when the shell exports the `COLUMNS` variable.
Fixes #727
> Provide fixed-width to PP.pp for ParseTest

- ext/yarp/compile.c
- src/unescape.c
Confirmed there are now [no compiler warnings](https://github.com/Shopify/yarp/actions/runs/4612485609/jobs/8153436795?pr=767) where [there previously were](https://github.com/Shopify/yarp/actions/runs/4609053009/jobs/8145649611) on the "Run Ruby tests" tab
> Fix existing build warnings

- src/yarp.c
- test/comments_test.rb
Asserted that the changes to comment_test made the existing test fail (since it threw an error) before the fix.
Closes #759
> Fix trailing embdoc

- bin/lex
Previously, if bin/lex had errors, it wouldn't be visible to the user. This prints errors before printing the bin/lex comparison
As suggested in #759 
New output comes before the usual comparison and looks like this:
```
Errors lexing:                       
- Unterminated embdoc                                                                                                                                                                                                                                       
```
> Add error output to bin/lex

- bin/templates/include/yarp/ast.h.erb
- bin/templates/lib/yarp/serialize.rb.erb
- config.yml
This allows us to distinguish between not provided and having actual values
Closes #665
> Start node_type and token_type enums at 1

- src/yarp.c
- test/fixtures/methods.rb
- test/snapshots/methods.rb
before this change ... range default in arguments got the ENDARG state as if they where forwarding params. Now we can tell the differenced based on if the previous state was END after parsing a number
> Fix range default on argument defaults

- bin/template.rb
This is a transitional PR which allows extra attributes of parameters from config.yml to get saved as 'options' to the parameter we interact with when generating code via ERB.
Why? In my current branch I have marked syntactical tokens that execution is uninterested in serializing (and then loading into an AST) as 'exclude: execute'.  My templates for serialize.c, Nodes.java, and Loader.java then will skip those elements altogether. I can think of other useful attributes we can put in to help with generation.
> Allow generic option collection in templating parameters

- src/yarp.c
- test/fixtures/embdoc_no_newline_at_end.rb
- test/snapshots/embdoc_no_newline_at_end.rb
There is an embdoc off by one error which causes =end with no newline to not be returned in the lex. This fixes that error and adds a test
> Fix small embdoc off at end

- .github/workflows/main.yml
- tasks/lex.rake
- tasks/top-100-gems.yml
This commit introduces the `lex:topgems` rake task, and adds it to CI. The rake task lexes against the top 100 gems, and compares their failures to the known failures in `tasks/top-100-gems.yml`. If they are not equivalent, the rake task will fail.
This will ensure we have no regressions when lexing the top 100 gems
Closes #788
> Lex against top 100 gems as part of CI

- lib/yarp/lex_compat.rb
- src/unescape.c
- src/yarp.c
- test/fixtures/dos_endings.rb
- test/parse_test.rb
- test/snapshots/dos_endings.rb
- test/snapshots/seattlerb/heredoc__backslash_dos_format.rb
This fixes some places where we assume that newlines are always unix newlines. Instead now we can handle newlines that are dos style as well.
I also removed a few tabs that probably shouldn't be there.
> Fix places where dos newlines create the wrong lex

- bin/parse
It's easier to provide an argument instead of a file for quick testing (when Ruby expression is short enough)
Example:
```shell
bin/parse -e "FOO::BAR = 1"
```
> Add `-e` switch to the `bin/parse` script

- src/yarp.c
- test/fixtures/method_calls.rb
- test/snapshots/method_calls.rb
Fixes parsing code like:
```ruby
foo :a,
while x
bar do |a|
a
end
end,
until x
baz do
end
end
```
The following is not a valid Ruby (see the trailing comma) but we currently does not emit an error message yet. That can be fixed in another PR.
```ruby
foo :a,
while x
bar do |a|
a
end
end,
until x
baz do
end
end,
ruby -c test.rb 
test.rb: test.rb:10: syntax error, unexpected end-of-input (SyntaxError)
end,
```
> Fix calls where arguments has loops with blocks inside

- src/yarp.c
- test/fixtures/arrays.rb
- test/snapshots/arrays.rb
%i#one two three#
thinks that it might be interpolation, this causes the correct terminator behavior in that case.
> Allow octothorpe list terminators

- src/yarp.c
- test/errors_test.rb
Mirror the CRuby behavior for setter methods in endless method definitions.
```ruby
def a=() = 42
```
```
test.rb: test.rb:1: setter method cannot be defined in an endless method definition (SyntaxError)
def a=() = 42
^~~~~~
```
> Emit an error message for endless setters

- src/yarp.c
- test/errors_test.rb
- Emit error for `return` in class/module body
- Emit error for class definition inside a `def` body
> Emit error for `return`s in class/module body

- src/yarp.c
- test/snapshots/arrays.rb
- test/snapshots/method_calls.rb
- test/snapshots/seattlerb/lasgn_middle_splat.rb
- test/snapshots/seattlerb/masgn_colon2.rb
- test/snapshots/seattlerb/masgn_colon3.rb
- test/snapshots/seattlerb/masgn_lhs_splat.rb
- test/snapshots/variables.rb
- test/snapshots/whitequark/asgn_mrhs.rb
- test/snapshots/whitequark/masgn.rb
- test/snapshots/whitequark/masgn_splat.rb
The location of the `ArrayNode` is not set correctly when there is no opening and closing nodes for it. E.g. `a = 1, 2, 3` 
This PR updates the end location of the `ArrayNode` every time we append an element to it.
> Fix array node location

- src/yarp.c
- test/fixtures/not.rb
- test/snapshots/not.rb
Small fix that came up from examples in zonify-0.4.9
> Allow whitespace after not in expressions

- src/yarp.c
Now the project can be compiled with `#define YP_DEBUG 1`.
> Fix `YP_DEBUG`

- test/test_helper.rb
This shows clearly where it does not hold and gives more context.
> Check that the start_offset <= end_offset for all locations

- src/yarp.c
- test/fixtures/single_quote_heredocs.rb
- test/snapshots/single_quote_heredocs.rb
- test/snapshots/unparser/corpus/semantic/dstr.rb
- test/snapshots/whitequark/dedenting_non_interpolating_heredoc_line_continuation.rb
- test/snapshots/whitequark/parser_slash_slash_n_escaping_in_literals.rb
Escaping in single quoted heredocs should use YP_UNESCAPE_MINIMAL, not YP_UNESCAPE_ALL.
Closes #884
> Fix escaping in single quote heredocs

- bin/templates/java/org/yarp/Loader.java.erb
- bin/templates/lib/yarp/serialize.rb.erb
- bin/templates/src/serialize.c.erb
- docs/serialization.md
* See #872.
This currently fails the added assert:
```
..............................................................................................................................
.....ruby: src/serialize.c:28: serialize_location: Assertion `location->start <= location->end' failed.
rake aborted!
SignalException: SIGABRT
```
I found with `gdb --args ruby -Ilib -Itest $f test/parse_test.rb`:
```
(gdb) bt
#0  0x00007ffff76afe5c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff765fa76 in raise () from /lib64/libc.so.6
#2  0x00007ffff76497fc in abort () from /lib64/libc.so.6
#3  0x00007ffff764971b in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff7658656 in __assert_fail () from /lib64/libc.so.6
#5  0x00007fffe57a2d5a in serialize_location …
```
> Serialize length instead of end offset

- bin/template.rb
- bin/templates/java/org/yarp/Loader.java.erb
- bin/templates/java/org/yarp/Nodes.java.erb
- bin/templates/lib/yarp/serialize.rb.erb
- bin/templates/src/serialize.c.erb
For https://github.com/ruby/yarp/issues/872
By adding these methods, and TruffleRuby migrating to them, we can avoid breaking the `Test Loader.java with TruffleRuby` CI job.
> Add length() and endOffset() to migrate to (startOffset, length) in a compatible way

- Rakefile
- bin/template.rb
Slight templating refactor to allow us to run the template script directly via `ruby bin/template.rb` which will let us easily run this script and generate the templated files when we mirror to ruby/ruby
> Refactor templating to set up for mirroring

- .github/workflows/main.yml
- targets.yml
Rails is included as one of the top-100 gems, so we lex it in the lex-top-100 GitHub actions workflow already, and don't need to also lex it individually
> Remove lex-rails GitHub workflow

- bin/templates/ext/yarp/node.c.erb
- bin/templates/java/org/yarp/Loader.java.erb
- bin/templates/java/org/yarp/Nodes.java.erb
- bin/templates/lib/yarp/node.rb.erb
- bin/templates/lib/yarp/serialize.rb.erb
- lib/yarp.rb
For https://github.com/ruby/yarp/issues/872
> Store length instead of endOffset in Java and Ruby objects

- ext/yarp/extension.h
- include/yarp.h
- include/yarp/diagnostic.h
- include/yarp/enc/yp_encoding.h
- include/yarp/missing.h
- include/yarp/node.h
- include/yarp/pack.h
- include/yarp/regexp.h
- include/yarp/unescape.h
- include/yarp/util/yp_buffer.h
- include/yarp/util/yp_char.h
- include/yarp/util/yp_conversion.h
- include/yarp/util/yp_list.h
- include/yarp/util/yp_state_stack.h
- include/yarp/util/yp_string.h
- include/yarp/util/yp_string_list.h
- include/yarp/util/yp_strpbrk.h
Change the style for function definitions in .h files to match ruby/ruby so that it's consistent when we mirror
> Style: define functions on one line in .h files

- include/yarp/parser.h
- include/yarp/util/yp_constant_pool.h
- src/util/yp_constant_pool.c
This is the initial work toward having a constant pool in YARP. This first commit adds a constant pool struct. This struct is effectively a hash map pointing from strings to ID. The IDs can be used to uniquely identify strings. They are incremental starting at 1.
This is implemented with a hash table using the dbj2 hashing function. This was chosen because the strings are likely to be short (we're going to use this for local variables and method names). This was also chosen because we don't need any kind of cryptographic security here (you would choose a difference hashing function if there were a possibility of DDOS, but if you're parsing user input as Ruby code you've already lost that battle).
The interface for this is relatively small (just 3 functions). They are:
```c
// Initialize a …
```
> Constant pool

- .gitattributes
This will impact the language stats and also make it so that snapshot changes aren't expanded by default in the diff.
> Fix up linguist for GitHub

- src/yarp.c
This is currently breaking on 32 bit machines because in the case where we only have errors in the parameters, we never set the location, and then have underflow if the file is sufficiently large
> Add default location to parameters node

- Makefile
- bin/profile.c
- src/enc/unicode.c
This commit adds two things. The first is a build/profile make target which is a small script that walks through a directory recursively and parses every Ruby file that it finds. I use this in combination with dappprof and dtrace to do some profiling to determine where we're spending the most time.
The second thing this adds is a complete refactor of our UTF-8 decoder. Because UTF-8 is the default encoding and we need to know if characters are alphanumeric or not very commonly, it's important that this path is very fast. Previously we were always decoding the unicode codepoint and then comparing it to a list of known values, but that's incredibly inefficient when the character is < 128 (i.e., almost all Ruby code). Instead we can use a lookup table like we do for all the other encodings. …
> Profiling and unicode work

- include/yarp/util/yp_char.h
- include/yarp/util/yp_strpbrk.h
- src/util/yp_char.c
- src/util/yp_strpbrk.c
This is just stylistic but could potentially provide us with some compiler help if we ever accidentally try to subtract different arrays.
> Use ptrdiff_t instead of long

- .github/workflows/main.yml
- .github/workflows/truffleruby.yml
Use GA's "cancel-in-progress" concurrency check so that subsequent pushes to a PR don't have multiple CI runs going simultaneously.
See https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency
> Github Actions cancel-in-progress

- ext/yarp/extension.c
- include/yarp/enc/yp_encoding.h
- include/yarp/parser.h
- src/enc/unicode.c
- src/yarp.c
Instead of going through the function pointer every time, instead check if the encoding has been changed. This patch entirely eliminates the encoding-related functions from the profile.
> Encoding fast path

- bin/templates/src/node.c.erb
When we generate files, error messages (including compilation errors and stack traces) would point to the generated .c file when the error actually originates from the source ERB file.  When fixing these generated files, we need to fix the source ERB file rather than the generated file, so this commit changes the generated file to use the source file for line and file reporting information
For example, if there is a syntax error in the source ERB file like this:
When you compile YARP, the error will be reported in the wrong place like this:
This patch fixes the error message so that it's reported as part of the source ERB file:
This PR only fixes `node.c`.  We need to fix the other files, but there also might be a more generic way to do this (maybe like a custom ERB generator that …
> Fix line and file information in generated files

- bin/templates/src/node.c.erb
- bin/templates/src/prettyprint.c.erb
- include/yarp/util/yp_allocator.h
- include/yarp/util/yp_constant_pool.h
- src/util/yp_constant_pool.c
- src/util/yp_string_list.c
Seeing a lot of reallocations when adding lists of constants because it does one for the 1st constant, then another for the 2nd constant, then another for the 3rd. Setting this to 8 by default doesn't significantly increase memory usage (all of the constant ids are still within a single cache line) but does avoid a bunch of unnecessary syscalls.
> Increase default constant id list size

- .github/workflows/main.yml
- bin/parse
- ext/yarp/extconf.rb
- ext/yarp/extension.c
- src/yarp.c
- tasks/lex.rake
- test/comments_test.rb
- test/encoding_test.rb
- test/errors_test.rb
- test/location_test.rb
- test/parse_test.rb
Instead of exposing parse_file_dup as a debugging utility, this commit adds a debug mode build that will perform the same checks without the additional complexity of parse_file_dup
> Refactor to remove parse_file_dup, use debug_mode build

- .gitignore
- Makefile.in
- Rakefile
- configure.ac
- include/yarp/defines.h
- include/yarp/missing.h
- src/yarp.c
- test/availability/strnstr.c
This PR introduces autotools for detecting whether or not some
functions exist.  The benefit of using autotools is that we don't need
to write our own feature detection C files, and that we'll use the same
`HAVE_*` macros that Ruby uses.  That means we can copy our C files in
to Ruby and piggyback off Ruby's configure scripts when Ruby is built.
> Introduce autotools

- .gitattributes
- .github/workflows/main.yml
- .gitignore
- Makefile.in
- Rakefile
- ext/yarp/extconf.rb
- ext/yarp/extension.c
- ext/yarp/extension.h
- include/yarp/defines.h
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
- test/parse_test.rb
Apologies for the large changeset, but the changes are all closely related.
In this PR:
- a Windows build CI job is added to `main.yml`
- Windows compilation warnings are addressed
- the SOEXT shared object file extension is fixed on Windows
- `ext/yarp/extconf.rb` is overhauled to be a self-documenting PORO
- `Makefile` generates both a dynamic shared library and a static archive for `librubyparser`
- the C extension now statically links librubyparser by default (can override with `--disable-static`)
- fixture files now have `.gitattributes` set so git won't munge line endings on Windows
- fixtures are read in binary mode to avoid CRLF autoconversion by File.read
I believe this supersedes (and incorporates pieces of) #1000 and #966. I've credited some commits with co-authors where …
> Windows build, static linking of the gem, improve extconf.rb

- .editorconfig
Many editors will pick up these style directives and do the right thing.
See 82e659a7 / #943 for background.
> Copy in the relevant sections of Ruby's .editorconfig

- lib/yarp.rb
This reverts commit 7cc29c2d1230d6b503ebd6739431f58468988afb.
This commit was unnecessary, and breaks builds on ruby/ruby. I think this commit is necessary if using an old ruby version. But if running `rake` with latest ruby, it's not necessary to have this config suffix and `.so` should suffice. Tested on mac
> Revert "Partially fix `rake test` on Mac"

- src/yarp.c
- test/snapshots/classes.txt
- test/snapshots/methods.txt
- test/snapshots/modules.txt
- test/snapshots/procs.txt
- test/snapshots/rescue.txt
- test/snapshots/seattlerb/defn_oneliner_rescue.txt
- test/snapshots/seattlerb/defs_oneliner_rescue.txt
- test/snapshots/seattlerb/rescue_do_end_ensure_result.txt
- test/snapshots/seattlerb/rescue_do_end_no_raise.txt
- test/snapshots/seattlerb/rescue_do_end_raised.txt
- test/snapshots/seattlerb/rescue_do_end_rescued.txt
- test/snapshots/unparser/corpus/literal/block.txt
- test/snapshots/unparser/corpus/literal/def.txt
- test/snapshots/whitequark/rescue_without_begin_end.txt
Prior to this commit, the location was incorrect whenever we called `parse_rescues_as_begin` because it was being set to the empty begin_token. This commit sets it to the first non-null child of the begin node (could be statements, rescue clause, else clause or ensure clause)
> Fix location on BeginNode

- Makefile.in
Two issues being fixed in this PR:
- headers are not located in `src`, they're in `include`
- the objects' dependencies need to be declared with `$(OBJECTS):` not `OBJECTS:`
So now, changes to header files will actually cause a recompilation.
> Makefile: fix object dependencies on headers

- ext/yarp/extension.c
https://github.com/ruby/ruby/actions/runs/5347722364/jobs/9696622788#step:15:102
```
Leaked file descriptor: ParseTest#test_filepath_/home/runner/work/ruby/ruby/src/test/yarp/fixtures/unparser/corpus/literal/empty.txt: 9 #<File::Stat dev=0x811, ino=783189, mode=0100644, nlink=1, uid=1001, gid=122, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2023-06-22 16:06:29.980038261 +0000, mtime=2023-06-22 16:00:36.372381267 +0000, ctime=2023-06-22 16:00:36.372381267 +0000>
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
ruby    19337 runner    9r   REG   8,17        0 783189 /home/runner/work/ruby/ruby/src/test/yarp/fixtures/unparser/corpus/literal/empty.txt
```
> Fix leaked FD for an empty file

- test/parse_test.rb
Full path name of the source directory is a useless noise as tests.
> Name test methods from relative paths

- Makefile.in
- Rakefile
- include/yarp/defines.h
Closes #1067
This PR introduces separate object files (and build directories) for the dll (`librubyparser.so`) and the static archive (`librubyparser.a`) to ensure the dll makes public symbols public and the static archive does not.
I've also made the Makefile much quieter by default, but provide support for a `V=1` argument for verbose mode (just like mkmf Makefiles).
This makes the difference between (uppercase `T`):
```
$ nm lib/yarp.so | fgrep yp_parse
0000000000031210 T yp_parse
0000000000003e1d t yp_parse.cold
00000000000313d0 T yp_parse_serialize
0000000000031160 T yp_parser_free
0000000000030ee0 T yp_parser_init
0000000000015520 t yp_parser_local_depth.isra.0
0000000000015450 t yp_parser_parameter_name_check
0000000000031140 T yp_parser_register_encoding_changed_callback …
```
> fix static symbol resolution

- .github/workflows/main.yml
- include/yarp.h
- include/yarp/diagnostic.h
- include/yarp/node.h
- include/yarp/pack.h
- include/yarp/parser.h
- include/yarp/regexp.h
- include/yarp/unescape.h
- include/yarp/util/yp_char.h
- include/yarp/util/yp_constant_pool.h
- include/yarp/util/yp_newline_list.h
- include/yarp/util/yp_string.h
- include/yarp/util/yp_string_list.h
- src/util/yp_string.c
- templates/include/yarp/ast.h.erb
Just implementing consistency here. From now on, we should always import local headers first to make sure our defines are correctly established.
Also remove `yp_string_alloc` because it's not used.
In general these kinds of things should eventually go into a `style.md` file, but for now I'm not taking that on.
> Import local headers before standard headers

- ext/yarp/extension.c
- ext/yarp/extension.h
- lib/yarp.rb
- lib/yarp/lex_compat.rb
- src/util/yp_newline_list.c
- templates/ext/yarp/api_node.c.erb
- templates/lib/yarp/node.rb.erb
- templates/lib/yarp/serialize.rb.erb
- test/parse_test.rb
This PR adds a bunch of functionality to the Ruby extension.
Every `YARP::Node`, `YARP::Token`, `YARP::Comment`, `YARP::Error`, and `YARP::Warning` now have a `YARP::Location` instance. (We were previously relatively inconsistent between using a location vs using start_offset + length. Now we just have a single object.)
`YARP::Location` instances now have the following instance variables. They are all given in the initializer/constructed by the parser in the extension:
* `@source` - a `YARP::Source` object
* `@start_offset` - the start offset of the node in the source
* `@length` - the length of the node in the source
`YARP::Location` instances now have the following methods:
* `#start_offset` - returns the instance variable
* `#end_offset` - returns the instance variable + the length
* …
> Introduce Source

- fuzz/heisenbug.c
ASAN may detect a memory leak if we don't free ```mutation_buffer```.
> Free resources in heisenbug

- src/yarp.c
- test/errors_test.rb
> Return NULL for empty ParametersNode

- lib/yarp.rb
Pattern matching variable pinning was introduced in Ruby 3.1. We need to remove it from YARP to support earlier rubies.
> Remove pattern matching pinning to enable support for <= Ruby 3.0

- tasks/check_manifest.rake
- yarp.gemspec
- ignore lib/yarp.bundle
- :check_manifest task is a dependency of :test
- remove yp_snprintf.c from the gemspec (see 4793b1ce / #962)
> Fix up the gemspec and the manifest check

- ext/yarp/extconf.rb
This, naturally, means that we need to run autoconf and generate the template files, which increases the requirements on the installation target system.
> Allow the gem to be used from a Gemfile "git:" source

- ext/yarp/extconf.rb
While running commands with "sh" works on MacOS and Windows, it won't work on some Linux systems (where the command won't be found).
Let's remove it for "autoconf" and "autoheader" until we actually see a need for it.
> extconf.rb: using "sh" when unnecessary won't work on some systems

- ext/yarp/extconf.rb
because we can not rely on development dependencies being present at install time (like ruby_memcheck).
> extconf.rb: avoid invoking "rake" to generate templates

- include/yarp/util/yp_char.h
- src/util/yp_char.c
- src/util/yp_newline_list.c
- src/yarp.c
- test/parse_test.rb
- test/snapshots/seattlerb/pct_w_heredoc_interp_nested.txt
The problem was that we were treating heredoc bodies as part of the %W list because we didn't push the scanning cursor past the heredoc after lexing out the here doc.  To fix this, we changed the whitespace scanning function to quit scanning when it reaches a newline but only in the case that a heredoc is present.
Additionally, we need to prevent double counting newlines in the case of a heredoc.  For example:
```ruby
%W(<<foo 123)
foo
```
The newline after the `)` is counted as part of scanning the heredoc, so we added logic to prevent double counting the newline when scanning the rest of the %W list.
> Fix heredocs inside %W and %w lists

- test/parse_test.rb
Ripper's lexemes were slightly different in Ruby 3.2 for Heredocs. We ignored this complex heredoc test in this case because Ripper's output has changed
> Exclude heredoc_nested test for Rubies < 3.3

- configure.ac
* It used to be needed for strnlen() and strncasecmp(), but we don't use both of these anymore. See https://github.com/ruby/yarp/pull/1164#issuecomment-1646565625
* It causes warnings in clang on macOS, see https://github.com/ruby/yarp/pull/1164
> Do not define _XOPEN_SOURCE, it is not needed anymore

- tasks/check_manifest.rake
Files that are auto-generated by language servers make the manifest check fail. I suggest we ignore the folders/files related to those.
- The .cache folder and compile_commands.json comes from clangd, which is very useful for working on the C part of the code
- The .ruby-lsp folder comes from the Ruby LSP
> Ignore LSP related files from manifest

- Rakefile
- tasks/test.rake
This PR allows:
1. JRuby to run rake tasks
2. Allow Java to compile any generated template code
For near term use this means for development work in YARP I can change a template and know with a rake run that I generated something which is at least valid Java.  Note: The yarp.jar created is just put into tmp since there is no immediate plan for JRuby to consume this code as a jar (it will be imported into JRuby repo).
Longer term (when fiddle impl of the gem side of YARP has landed) it will allow JRuby to test like MRI does.
> Allow JRuby to run Rake

- README.md
- docs/building.md
- include/yarp/defines.h
- yarp.gemspec
Add a document outlining which flags should be passed to the compiler.
Also revisiting symbol exports _again_. I think this is much more correct this time. I'm going to lay out my understanding here for posterity.
First, let's define a couple of concepts:
* `__attribute__((__visibility__("default")))` - GCC/Clang compiler directive to export a symbol
* `__declspec(dllexport)` - MSVC compiler directive to export a symbol
* `_WIN32` - Macro defined by MSVC to indicate that the target is Windows
* `RUBY_FUNC_EXPORTED` - Macro defined by Ruby to indicate that a symbol should be exported
* `YP_EXPORT_SYMBOLS` - Macro defined by YARP to indicate that some symbols should be exported
* `YP_EXPORTED_FUNCTION` - Macro defined by YARP to indicate that a symbol should be exported
Next, let's define …
> Document building, more macro changes

- tasks/check_manifest.rake
Added by https://github.com/ruby/yarp/pull/1146 due to merge conflict most likely
> Remove redundant ignores in check_manifest.rake

- .github/workflows/main.yml
- Gemfile
Actually runs #1170 any time anything changes so we know the Java generated at least compiles. 
A later PR will expand this to also run JRuby via the fiddle backend to also verify the gem part is also working on JRuby.
> Add JRuby rake CI task

- src/yarp.c
Fixes https://github.com/ruby/yarp/issues/1033.
> Ensure token cannot begin an expression

- config.yml
- src/yarp.c
- test/snapshots/constants.txt
- test/snapshots/methods.txt
- test/snapshots/unparser/corpus/literal/assignment.txt
- test/snapshots/variables.txt
- test/snapshots/whitequark/casgn_unscoped.txt
- test/snapshots/whitequark/parser_bug_490.txt
The common case of `Foo = 1`.
Fixes #1136.
> Add constant write node

- .gitattributes
- test/newline_test.rb
If `lib/yarp/lex_compat.rb` is still causing problems, feel free to just skip it.
It seems useful to test that file for newlines though as it's like the biggest Ruby file in YARP.
> Less brittle newline test

- config.yml
- src/yarp.c
> Rename RescueNode#exception to RescueNode#reference

- ext/yarp/extension.c
- include/yarp.h
- src/yarp.c
This is more or less the code I used in my POC in JRuby to parse evals.  Evals depend on parent variable scopes and will produce a different syntax tree.
Questions:
1. How does MRI compile evals currently?  I cannot find anything.
2. This passes in a char * of data.  It does not encode the variables we pass in because the system calling this already knows.  Is this adequate though?
3. Can I get guidance on how best to test this?
> WIP - Introduce contextually parsing programs vs evals

- ext/yarp/extension.c
- ext/yarp/extension.h
- templates/ext/yarp/api_node.c.erb
Right now whenever you go to create a Ruby object from a C struct we dynamically look up the constants. This is not great for performance. Now instead we template out a constant for each VALUE that holds the classes, and then directly reference it.
> Less const_get

- .github/workflows/main.yml
Fixes https://github.com/ruby/yarp/issues/842, gcc added just because why not.
Both are failing, so need to be fixed to make them required checks
[Test run](https://github.com/ojab/yarp/actions/runs/5511118250)
> Add gcc-analyzer & clang-analyzer to CI

- ext/yarp/api_pack.c
Conversions from `uint64_t`/`VALUE` to `long` may loose upper bits.
> Fix wrong conversion and cast

- docs/serialization.md
- ext/yarp/extension.c
- fuzz/parse.c
- lib/yarp.rb
- src/yarp.c
- test/newline_test.rb
- test/parse_serialize_test.rb
This adds the ability to pass the filepath through the yp_parse_serialize function in the metadata. It also adds documentation about this new API and fixes a couple of places that were calling it with the old signature. Finally, it adds a specific test to ensure yp_parse_serialize doesn't break.
@enebo I've added the filepath to the beginning of the metadata. Let me know if you have any questions on it!
> Add filepath to yp_parse_serialize metadata

- Gemfile
- Gemfile.lock
- ext/yarp/extension.h
- include/yarp/version.h
- templates/java/org/yarp/Loader.java.erb
- templates/lib/yarp/serialize.rb.erb
- test/errors_test.rb
- test/newline_test.rb
- test/parse_test.rb
- yarp.gemspec
* Drop requirement to Ruby 3.0.0
* Bump YARP version to 0.6.0
* Polyfill `unpack1` with the offset parameter for Ruby 3.0
* Remove single-line pattern matching in `serialize.rb` to get rid of warning in Ruby 3.0
* Fix tests so that they pass on Ruby 3.0, 3.1, 3.2, and 3.3
Incorporated work from #1140 so we can close that after this is out.
> Prep for gem release

- src/yarp.c
- templates/include/yarp/ast.h.erb
Prior to this commit, we folded the flags into the type. This created extra overhead when calculating the type and setting the flags. This commit separates them.
Found this when debugging a direct access to `node->type` working on the compiler. I'm now using `YP_NODE_TYPE` over there regardless, but it seems to add unnecessary overhead to store the flags with the type.
> Separate yp_node_flags_t from yp_node_type_t

- .github/workflows/main.yml
I have begrudgingly been convinced that we need these checks in CI for the gem. Also split out the lint task, because it doesn't need to run on all of the different OSs.
> Split out lint task, increase matrix for gem

- CHANGELOG.md
- yarp.gemspec
Now that we have a public gem, we should do a better job of documenting API changes to make it easier on our consumers to see what's happening.
> Add a CHANGELOG

- src/yarp.c
- test/snapshots/method_calls.txt
- test/snapshots/numbers.txt
- test/snapshots/seattlerb/cond_unary_minus.txt
- test/snapshots/seattlerb/parse_pattern_019.txt
- test/snapshots/seattlerb/uminus_float.txt
- test/snapshots/unparser/corpus/literal/literal.txt
- test/snapshots/unparser/corpus/semantic/literal.txt
- test/snapshots/whitequark/args.txt
- test/snapshots/whitequark/float.txt
- test/snapshots/whitequark/int.txt
- test/snapshots/whitequark/lparenarg_after_lvar__since_25.txt
Some unary minuses get incorporated into number literals, and some do not. So a straight compilation of -@ calls is not correct. For example:
-5 # will not call Integer#-@
-5**1 # will call Integer#-@
So if you monkey-patch Integer#-@, those values will be different. As such, it makes more sense to incorporate the minus sign into the range of the integer itself.
We also do this for floats, rationals, and imaginaries.
Fixes #1148
> Incorporate unary minus on numbers into node

- lib/yarp.rb
A small quality-of-life improvement for Ruby API consumers.
> Node#slice for getting the source slice of a node

- .github/workflows/main.yml
- .github/workflows/truffleruby.yml
- .gitignore
- Gemfile.lock
- rakelib/serialization.rake
- templates/java/org/yarp/Nodes.java.erb
As we discussed on Slack.
This change in CI means e.g. node names and field names and other similar breaking changes can be merged with a green CI here.
The modified CI job now runs Loader.java and ensures it can deserialize fine, in addition to just javac-building `.java` files before.
That uses JRuby for convenience, so the file walking logic can be shared in Ruby instead of having to duplicate it in Java, cc @enebo
> Test Java Loader in build-java job

- src/yarp.c
- test/errors_test.rb
Fixes: https://github.com/ruby/yarp/issues/1230
> add a diagnostic for `*rest` in order after optional state

- config.yml
- src/yarp.c
- templates/ext/yarp/api_node.c.erb
- templates/include/yarp/ast.h.erb
- templates/java/org/yarp/Loader.java.erb
- templates/java/org/yarp/Nodes.java.erb
- templates/lib/yarp/node.rb.erb
- templates/lib/yarp/serialize.rb.erb
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
- templates/template.rb
A couple of things are happening in this commit. We now have a special param type for flags (previously these were all uint32 params). The param type accepts a "kind" field that should link up 1:1 with one of the flag types.
This commit changes all of the previous params known as flags to be of the flags type.
The flags type is special in that it doesn't have its own field in the struct. Instead we embed the value within the flags field (previously the top half of the type enum) shifted by the number of common flags (currently 1). This ends up saving us 4 bytes per call node, range node, until node, while node, regular expression node, and interpolated regular expression node.
When serializing or converting to Ruby, we unshift the value and return it as normal. As such only the C API has …
> Refactor flags

- lib/yarp/lex_compat.rb
- rakelib/serialization.rake
- src/yarp.c
- test/parse_test.rb
- test/snapshots/seattlerb/heredoc_nested.txt
Looks like we're pretty much working as expected already, we just needed to not double-count a newline. Also skipping some tests here for comparing to ripper because there may be a bug or at least unanticipated behavior in ripper for nested heredocs. See Ruby bug here: https://bugs.ruby-lang.org/issues/19838.
Fixes #1176.
> Nested heredocs

- .gitattributes
- test/newline_test.rb
- test/parse_test.rb
* Only skip the Ripper part, since that one depends on the RUBY_VERSION.
I noticed in https://github.com/ruby/yarp/actions/runs/5859209143/job/15884736966
On CRuby:
`1246 tests, 334838 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications`
On TruffleRuby:
`256 tests, 7106 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications`
With this PR on TruffleRuby:
https://github.com/ruby/yarp/actions/runs/5859462998/job/15885515840?pr=1249
`1222 tests, 309691 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications`
Which is much closer (not exactly the same since some tests rely on `RubyVM` and `YARP::Debug`)
> Run parse_test.rb on JRuby, TruffleRuby and older CRuby versions

- bin/locals
- lib/yarp.rb
- lib/yarp/lex_compat.rb
- rakelib/lint.rake
- test/locals_test.rb
- test/newline_test.rb
- test/parse_serialize_test.rb
We want to ensure that we have the same set of locals for any given scope as CRuby does so that we can compile them correctly.
Currently we need to skip "special" locals like the keyword arguments hash and numbered parameters, but this gets us to a place we can iterate.
I had to add a bit of stuff to make the newline test work again. That's what the extra noise is for.
> Check locals

- fuzz/unescape.c
- include/yarp/util/yp_constant_pool.h
- include/yarp/util/yp_list.h
- include/yarp/util/yp_newline_list.h
- include/yarp/util/yp_state_stack.h
- src/unescape.c
- src/util/yp_list.c
- src/util/yp_state_stack.c
- src/yarp.c
- templates/src/serialize.c.erb
We're serializing the size a couple of times for errors, warnings, and comments. This can get costly if there are a lot, so instead we'll track the size.
The compiler also started figuring out that we hadn't initialized every variable, so this also sets everything in `yp_parser_init`.
> Add a size tracker to yp_list_t

- ext/yarp/extension.c
- include/yarp/util/yp_buffer.h
- lib/yarp/ffi.rb
- src/util/yp_buffer.c
Right now, we have to keep the buffer FFI object in sync with the definition of yp_buffer_t because we access its fields directly. If we add more fields or change the order, things will get out of sync.
Instead, let's treat yp_buffer_t as an opaque pointer and access its fields through accessor functions directly. This is more consistent with how we handle strings anyway.
> Treat yp_buffer_t as an opaque pointer

- test/locals_test.rb
See the crash https://github.com/ruby/ruby/actions/runs/5871605132/job/15921373210?pr=8226. We can further investigate why reading these iseqs is causing crashes on 32 bit machines. But since it looks like a Ruby bug, and not a YARP bug, we'd rather proceed with the sync now. We can then make the fix on the Ruby side (while the syncing resumes as normal).
> Omit locals test if running on a 32 bit machine

- include/yarp/defines.h
Ruby CI has informed us that snprintf is not available on Windows versions, but _sprintf is supported. This commit allows us to use _sprintf where applicable.
> Use _snprintf when using Windows versions prior to 2015 (< 1900)

- src/yarp.c
- test/fixtures/endless_range_in_conditional.txt
- test/snapshots/endless_range_in_conditional.txt
yp_flip_flop should only recurse on range endpoints if they exist.
Previously, parsing code like `if ..2` would segfault. This bug was found with the fuzzer.
> fix: endless ranges in conditional expressions

- bin/memsize
When trying to run `bin/memsize` on a newly-built tree from `HEAD`, I encountered the error:
```
Traceback (most recent call last):
4: from bin/memsize:8:in `<main>'
3: from bin/memsize:8:in `map'
2: from bin/memsize:11:in `block in <main>'
1: from bin/memsize:11:in `sum'
bin/memsize:22:in `block (2 levels) in <main>': Unknown type: constant[] (RuntimeError)
```
This PR fixes things up so that `bin/memsize` runs properly.  IIUC, `flags` shouldn't be counted, since I think it's accounted for in other ways, but let me know if that's not the case.
> update `memsize` with new types

- Makefile
- fuzz/tools/minimize.sh
- ensure header files are generated for compilation in the container
- don't quote the flags passed to afl-tmin (empty flags end up being an empty string which confuses afl-tmin) in the minimization step
> improve fuzzing

- templates/ext/yarp/api_node.c.erb
This change is good for a ~10% performance improvement in the unscientific benchmark of:
```ruby
files.each do |f|
YARP.parse_file(f)
end
```
where `files` is all the Ruby files in a large codebase.
> preallocate arrays when building the Ruby AST

- .gitattributes
Fixes the issue reported in https://github.com/ruby/yarp/pull/1270
> Keep the line endings for *.txt as they are committed in the repository

- templates/lib/yarp/node.rb.erb
- templates/template.rb
https://github.com/ruby/ruby/pull/8228 will render templates in the ruby/ruby's build process. For that, this PR adds a couple of changes:
* Let `templates/template.rb` take an optional `ARGV` to specify rendering targets individually
* Support Ruby 2.5 ([baseruby](https://github.com/ruby/ruby/blob/4e881ee6b6a55c9fc154d535b268a431e26f1b7c/configure.ac#L78-L79)) to run `templates/template.rb`
* We should have CI for baseruby compatibility in this repository as well, but I'd like to fix the sync script asap and deal with it in a later PR. At least we could notice it when we sync changes.
> Prepare for rendering templates in ruby/ruby

- src/yarp.c
- test/errors_test.rb
The problem being addressed here:
```
>> YARP.parse('a %')
irb: src/yarp.c:5594: parser_lex: Assertion `parser->current.end <= parser->end' failed.
Aborted (core dumped)
```
Bug found via the fuzzer.
> fix: unterminated % in arguments

- config.yml
- src/yarp.c
- test/location_test.rb
- test/snapshots/blocks.txt
- test/snapshots/boolean_operators.txt
- test/snapshots/defined.txt
- test/snapshots/seattlerb/bug_op_asgn_rescue.txt
- test/snapshots/seattlerb/const_2_op_asgn_or2.txt
- test/snapshots/seattlerb/const_3_op_asgn_or.txt
- test/snapshots/seattlerb/const_op_asgn_and1.txt
- test/snapshots/seattlerb/const_op_asgn_and2.txt
- test/snapshots/seattlerb/const_op_asgn_or.txt
- test/snapshots/seattlerb/messy_op_asgn_lineno.txt
- test/snapshots/seattlerb/op_asgn_command_call.txt
- test/snapshots/seattlerb/op_asgn_primary_colon_const_command_call.txt
- test/snapshots/seattlerb/parse_line_defn_complex.txt
- test/snapshots/seattlerb/parse_line_op_asgn.txt
- test/snapshots/unparser/corpus/literal/assignment.txt
- test/snapshots/unparser/corpus/literal/opasgn.txt
- test/snapshots/unparser/corpus/literal/send.txt
- test/snapshots/whitequark/const_op_asgn.txt
- test/snapshots/whitequark/op_asgn_cmd.txt
- test/snapshots/whitequark/rescue_mod_op_assign.txt
- test/snapshots/whitequark/ruby_bug_12402.txt
- test/snapshots/whitequark/ruby_bug_12669.txt
- test/snapshots/whitequark/var_and_asgn.txt
- test/snapshots/whitequark/var_op_asgn.txt
- test/snapshots/whitequark/var_op_asgn_cmd.txt
- test/snapshots/whitequark/var_or_asgn.txt
* `{ClassVariable,Constant,ConstantPath,GlobalVariable,InstanceVariable,LocalVariable}OperatorAndWriteNode` instead become `AndWriteNode` with their target being the original value being written to. I decided to keep them as read nodes to save on space because they'll never end up having a value and technically you have to read them first before anything else.
* Same for `OrWrite`.
* Same for `OperatorWrite`.
> Refactor operator write nodes

- config.yml
- src/yarp.c
- test/location_test.rb
A lot of these fields aren't actually statements since they could be `StatementsNode` or `BeginNode`. Fixes #1121
> Rename statements to body where appropriate

- src/yarp.c
- test/snapshots/blocks.txt
- test/snapshots/boolean_operators.txt
- test/snapshots/defined.txt
- test/snapshots/seattlerb/bug_op_asgn_rescue.txt
- test/snapshots/seattlerb/const_2_op_asgn_or2.txt
- test/snapshots/seattlerb/const_3_op_asgn_or.txt
- test/snapshots/seattlerb/const_op_asgn_and1.txt
- test/snapshots/seattlerb/const_op_asgn_and2.txt
- test/snapshots/seattlerb/const_op_asgn_or.txt
- test/snapshots/seattlerb/messy_op_asgn_lineno.txt
- test/snapshots/seattlerb/op_asgn_command_call.txt
- test/snapshots/seattlerb/op_asgn_primary_colon_const_command_call.txt
- test/snapshots/seattlerb/parse_line_defn_complex.txt
- test/snapshots/seattlerb/parse_line_op_asgn.txt
- test/snapshots/unparser/corpus/literal/assignment.txt
- test/snapshots/unparser/corpus/literal/opasgn.txt
- test/snapshots/unparser/corpus/literal/send.txt
- test/snapshots/whitequark/const_op_asgn.txt
- test/snapshots/whitequark/op_asgn_cmd.txt
- test/snapshots/whitequark/rescue_mod_op_assign.txt
- test/snapshots/whitequark/ruby_bug_12402.txt
- test/snapshots/whitequark/ruby_bug_12669.txt
- test/snapshots/whitequark/var_and_asgn.txt
- test/snapshots/whitequark/var_op_asgn.txt
- test/snapshots/whitequark/var_op_asgn_cmd.txt
- test/snapshots/whitequark/var_or_asgn.txt
It is going to make it more difficult to find all locations where a variable is written to if they're just read nodes. To keep things consistent we should make them write nodes.
> Change AndWriteNode, OrWriteNode, OperatorWriteNode to contain write nodes

- templates/template.rb
* For example in ProgramNode: # attr_reader statements: Node => # attr_reader statements: StatementsNode
> Use node kind for Ruby types

- docs/serialization.md
- rust/yarp-sys/README.md
I found two typos while reading through the docs and thought I'd open a pull request to fix them 🙌🏼
> Fix typos in docs

- rust/yarp/build.rs
Otherwise we get peculiar build errors because Cargo doesn't think anything has changed.
> tell Cargo about the `config.yml` dependency for `yarp`

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
This new function is slightly redundant with `ParseResult::as_slice`, but the new function is consistent with `Comment::text`.  And like `Comment::text`, `Location::as_byte_slice` is more useful when you are writing visitors and what to examine some of the source text of a node (my motivating example was examining the opening delimiter of `InterpolatedStringNode` for determining heredocs).
Open to changing the name for consistency with `ParseResult::as_slice` or `str::as_bytes`.
> [rust] add an `as_byte_slice` method to `Location`

- bin/lex
- bin/locals
- bin/parse
For instance, if you don't pass any args to bin/parse, it will now default to "bin/parse test.rb" This commit applies this change to bin/lex, bin/locals and bin/parse
> All bin/ scripts which take filepaths default to "test.rb"

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
The motivating example for this change is a visitor that wants to maintain parent node information as it traverses the AST.  The type of the stack maintained during the traversal should be `Vec<Node>`, but there's no way from the concrete nodes to upcast to the `Node` enum.
> [rust] add a converter from concrete nodes to generic `Node`

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
Per the subject, as requested by @kddnewton in post-commit review in #1301
> rename `as_byte_slice` to `as_slice`

- src/yarp.c
`memchr` does not stop on NULL bytes, so this loop never executes.
> Remove unnecessary loop

- lib/yarp/lex_compat.rb
- test/fixtures/indented_file_end.txt
- test/snapshots/indented_file_end.txt
in Ripper EOL after whitespace is returned as a on_nl node with the whitespace as the content.
> Match EOF after newline behavior

- src/yarp.c
- test/comments_test.rb
- test/errors_test.rb
Introduce three new inline helper functions:
- `match_line_ending`
- `match_line_ending_at`
- `match_line_ending_addr`
These functions are similar in signature to the `peek*` functions, but return the length of the line ending being inspected (or 0 if no line ending was found).
These functions are then used to simplify how we're detecting line endings throughout "src/yarp.c".
Also:
- test coverage backfilled for `__END__` comments with CRLF line endings.
- error message for invalid `%` tokens updated to not include the potential line endings.
- some small refactorings for readability along the way
> Improve handling of line endings

- fuzz/unescape.c
- include/yarp/unescape.h
- src/unescape.c
- src/yarp.c
When an escape occurs in a string, we can't blindly move forward by a single byte. We need to check the width according to the current encoding.
This is a trade-off, we could return immediately after realizing the `\` is not actually escaping something. However that means we need to handle escaped newlines in every caller. This makes it a little easier.
This gets one more file off @HParker's branch: 406bd8fb31b6eb0552606473c16baddf-act-mdlb.txt
> Encoding-dependent escapes

- src/yarp.c
Nothing particularly of substance here, just renaming things and moving some stuff around.
* `le_len` to `eol_length`
* Braces on the same line as switch case
* `peek_addr` -> `peek_at` (Now that we have it looking at specific places, I think it makes more sense for this API to be `at`)
* `peek_at` -> `peek_offset` (This is now more clear (I think) because it tells you it's offset from the current address)
* `match_line_ending_addr` -> `match_eol_at` (Making these match)
* `match_line_ending_at` -> `match_eol_offset`
> A couple of small stylistic changes

- config.yml
- include/yarp.h
- include/yarp/node.h
- src/yarp.c
- templates/include/yarp/ast.h.erb
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
This commit creates a scope node, and exposes a method to get ScopeNodes from other existing nodes. It still has TODOs around creating ScopeNodes for other types of nodes, which will be done in future commits.
> Add a ScopeNode and a way to create scope nodes from existing nodes

- ext/yarp/extension.c
- lib/yarp/lex_compat.rb
- src/yarp.c
- test/bom_test.rb
* BOM should not impact looking for the encoding string
* We should re-encode tokens when the encoding changes
* BOM should change the column of comments only
Fixes one more file in the remaining parse errors.
> Fix lex compat with BOM

- templates/java/org/yarp/Loader.java.erb
- templates/lib/yarp/serialize.rb.erb
- templates/src/serialize.c.erb
Previously, we would copy the entire string every time into the serialized output. Depending on the string, this can get expensive. Now, for the most part strings should end up being about 3 bytes: 1 or 2 for the offset from the start (_maybe_ 3 for large files) and likely a 1 byte length.
> Add the ability to serialize shared strings

- src/yarp.c
- test/errors_test.rb
Previously this snippet would track the same newline twice, leading to a failed assertion in yp_newline_list_append:
```
<<-END + /b
END
```
Found via the fuzzer.
> fix: unterminated regular expression with a heredoc

- src/yarp.c
- test/fixtures/wrapping_heredoc.txt
- test/parse_test.rb
- test/snapshots/wrapping_heredoc.txt
For example:
```ruby
<<-A.gsub(/b\
a
A
c/, "")
```
should be parsed as a heredoc containing `"x\n"`, and a regex that is comprised of two string tokens, `"a"` and `"b"`:
```
CallNode(168...193)(
InterpolatedStringNode(168...172)(
(168...172),
[StringNode(182...184)(nil, (182...184), nil, "a\n")],
(184...186)
),
(172...173),
(173...177),
(177...178),
ArgumentsNode(178...192)(
[InterpolatedRegularExpressionNode(178...188)(
(178...179),
[StringNode(179...182)(nil, (179...182), nil, "b"),
StringNode(186...187)(nil, (186...187), nil, "c")],
(187...188),
0
),
StringNode(190...192)(
(190...191),
(191...191),
(191...192),
""
)]
),
(192...193),
nil,
0,
"gsub"
)]
```
Similarly for the string case:
```ruby
<<-A + "e\
d
A
f"
```
should be parsed as:
```
CallNode(281...298)( …
```
> fix: regexes and strings with escaped newline around a heredoc

- lib/yarp/lex_compat.rb
Ripper state can carry over from the previous node type making coparison less useful
> ignore state on embexpr_end

- config.yml
- lib/yarp.rb
- lib/yarp/desugar_visitor.rb
- src/yarp.c
- test/yarp/library_symbols_test.rb
* `constant_id` and `operator_id` are confusing.
* Solves points 3 and 4 of https://github.com/ruby/yarp/issues/1296
> Rename constant pool fields to name or operator

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
The ultimate goal of this PR is to add something like the proposed `ConstantId::as_slice`.
The design proposed here threads `yp_parser_t` into the various Rust structures.  This is necessary because `ConstantId` needs access to the associated parser it was created from so it can index into the parser's constant pool.
I can imagine an alternate world where one provides `yarp::Parser` (or similar) to `ConstantId::as_slice` instead, and any other place that requires some global state from `yp_parser_t`.  (If you squint, this is the same sort of idea that `ParseResult::as_slice` implements, except the latter function does it backwards and is probably redundant with `Location::as_slice`.)  I think the design adopted in this PR is the better one, because it gives stronger guarantees about tying …
> [rust] add `ConstantId` wrapper for `yp_constant_id_t`

- rust/yarp/build.rs
I don't think this should be exposed outside of the `yarp` crate, even if this API is not quite in its final form.
> [rust] limit the visibility of `Node` constructor

- rust/yarp/build.rs
> Use path.to_str().unwrap() for faster failure in build.rs

- .github/workflows/github-pages.yml
When the repo is forked, the GitHub Pages action will run but fail, for example:
https://github.com/andyw8/yarp/actions/runs/6015582054
I _think_ this will solve it.
> Prevent GitHub pages failure on forks

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
This came up when trying to write code against this crate; sometimes you just want the location of a node without caring about the specific kind of node that it is.
The helper is possibly superfluous, but it makes things slightly more readable IMHO.
> add a location accessor on generic `Node`

- test/yarp/ruby_api_test.rb
I was adding this functionality to the `yarp` crate and noticed there were no tests for the Ruby code.
> add tests for `Location#join`

- lib/yarp/desugar_visitor.rb
- test/yarp/desugar_visitor_test.rb
Class variables, global variables, constants, and constant paths should actually desugar to `defined?` instead of just reading the value.
> Desugar ||= more accurately

- ext/yarp/extension.c
- src/yarp.c
- test/yarp/errors_test.rb
- test/yarp/fuzzer_test.rb
I've introduced a new test file, `test/yarp/fuzzer_test.rb` to exercise the snippets. These snippets all caused invalid memory access that is caught by valgrind.
You can run these tests with:
```
bundle exec rake test:valgrind TESTOPTS=-n/fuzzer/
```
I've also enabled valgrind debugging for `YARP.dump` similar to what has been done in `YARP.parse`.
The fixes here are mostly small and should be uncontroversial.
The commit fixing "$" at the end of a file. I've introduced a label and some `goto`s to unify error handling in `lex_global_variable`. This may violate the informal style guide and/or your sensibilities, in which case let me know and I'll change it.
> Fixing end-of-file issues found by the fuzzer

- src/yarp.c
- test/yarp/fuzzer_test.rb
The fuzzed snippets added in this PR are not very obvious, but they result in nodes with start locations after their end locations. This causes assertions to fail during serialization.
Primarily this is happening because locations during error recovery are "best efforts" and nodes may appear out of order in a list; but there is also an implicit assumption in nodes _are_ in location order.
To address this, this PR introduces checks on both start and end locations when a node is being appended or created.
> Fixing start/end location confusion found by the fuzzer

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
Per the use of `OptionalLocation` pieces from `config.yml` elsewhere, e.g.:
https://github.com/ruby/yarp/blob/4d2f7afe1fd880f98b68d851eb9049af64b35fc5/templates/ext/yarp/api_node.c.erb#L170-L171
we should be looking at the `start` of the `yp_location_t` we're accessing to determine if the location is present, rather than the address of the `yp_location_t` itself (which will never be null).
> [rust] fix accessing optional locations

- src/yarp.c
I added these mostly for the `content_loc` variables, but it seemed reasonable to clarify the other cases too.
> add some `const` qualifiers to local variables

- src/unescape.c
- src/yarp.c
- test/yarp/errors_test.rb
- test/yarp/fuzzer_test.rb
These were causing invalid memory access.
Also:
- clean up handling of EOF after `"\\"` by moving the check from `parser_lex` into `yp_unescape_calculate_difference`
- report a syntax error for unterminated bracket-style unicode strings, like `\u{1234`
> fix: octal, hex, and unicode strings at the end of a file

- include/yarp/unescape.h
- src/unescape.c
- src/yarp.c
- test/yarp/errors_test.rb
Closes #1367
This change passes in an error list to `escape.c:unescape_hexadecimal` and reports a syntax error if the first character isn't hexadecimal, e,g:
```ruby
def test_invalid_hex_escape
assert_errors expression('"\\xx"'), '"\\xx"', [
["Invalid hex escape.", 1..3],
]
end
```
Essentially, this change updates `yp_unescape_calculate_difference` to not create syntax errors, and we rely entirely on `yp_unescape_manipulate_string` to report syntax errors.
To do that, this PR adds another (!) parameter to `unescape`: `yp_list_t *error_list`. When present, `unescape` reports syntax errors (and otherwise does not).
However, an edge case that needed to be addressed is reporting syntax errors in this case:
```ruby
?\u{1234 2345}
```
In a string context, it's possible to have multiple …
> fix: report syntax error for invalid hex escape, and avoid double-reporting

- templates/include/yarp/ast.h.erb
This commit adds the node type and the node flags as comments to the AST templated code.
> Print information about type, flags on AST templated code

- src/util/yp_newline_list.c
- src/util/yp_string_list.c
If we move to a bump/arena allocator like in https://github.com/HParker/yarp/tree/introduce-yp_malloc
we likely don't want to support realloc as it likely requires extra book keeping. Instead we can malloc and memset so our allocator has less cases to consider.
> remove reallocs preparing for custom memory management

- bin/parse
- lib/yarp.rb
- templates/lib/yarp/node.rb.erb
Templates out an inspect method to make it easier to see all of the fields. Note that I didn't override pretty printing yet, because I didn't want the diff to be massive. This changes:
```
$ bin/parse -e 'foo + 1'
#<YARP::ParseResult:0x0000000103301c78
@comments=[],
@errors=[],
@source=#<YARP::Source:0x00000001032e1b30 @offsets=[0], @source="foo + 1">,
@value=
ProgramNode(0...7)(
[],
StatementsNode(0...7)([CallNode(0...7)(CallNode(0...3)(nil, nil, (0...3), nil, nil, nil, nil, 2, "foo"), nil, (4...5), nil, ArgumentsNode(6...7)([IntegerNode(6...7)()]), nil, nil, 0, "+")])
),
@warnings=[]>
```
to:
```
$ bin/parse -e 'foo + 1'
@ ProgramNode (location: (0...7))
├── locals: []
└── statements:
@ StatementsNode (location: (0...7))
└── body: (length: 1)
└── @ CallNode (location: (0...7))
├── …
```
> Provide a better inspect

- templates/template.rb
https://github.com/ruby/yarp/pull/1381 broke ruby/ruby's CI https://github.com/ruby/ruby/actions/runs/6054821565/job/16432831277, and this PR is trying to fix it.
> Support LANG=C environments in template.rb

- templates/template.rb
Explicitly specify the encoding, instead of `Encoding.default_external` temporarily.
> Read template in UTF-8

- bin/memsize
- config.yml
- docs/configuration.md
- docs/serialization.md
- include/yarp/node.h
- rust/yarp/build.rs
- rust/yarp/src/lib.rs
- src/yarp.c
- templates/ext/yarp/api_node.c.erb
- templates/include/yarp/ast.h.erb
- templates/java/org/yarp/Loader.java.erb
- templates/lib/yarp/node.rb.erb
- templates/lib/yarp/serialize.rb.erb
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
- templates/template.rb
- test/yarp/location_test.rb
- test/yarp/snapshots/procs.txt
- test/yarp/snapshots/seattlerb/block_arg_scope.txt
- test/yarp/snapshots/seattlerb/block_arg_scope2.txt
- test/yarp/snapshots/seattlerb/block_scope.txt
- test/yarp/snapshots/seattlerb/pipe_semicolon.txt
- test/yarp/snapshots/seattlerb/stabby_proc_scope.txt
- test/yarp/snapshots/unparser/corpus/literal/block.txt
- test/yarp/snapshots/unparser/corpus/literal/lambda.txt
- test/yarp/snapshots/whitequark/arg_scope.txt
- test/yarp/snapshots/whitequark/blockargs.txt
- test/yarp/snapshots/whitequark/send_lambda_args_shadow.txt
This is a tradeoff that I think is worth it. Right now we have a location list that tracks the location of each of the block locals. Instead, I'd like to make that a node list that has a proper node in each spot in the list. In doing so, we eliminate the need to have a location list at all, making it simpler on all of the various consumers as we have one fewer field type. There should be minimal memory implications here since this syntax is exceedingly rare.
> Introduce a BlockLocalVariableNode

- config.yml
- rust/yarp/src/lib.rs
- src/yarp.c
- test/yarp/location_test.rb
- test/yarp/snapshots/seattlerb/index_0_opasgn.txt
- test/yarp/snapshots/seattlerb/op_asgn_dot_ident_command_call.txt
- test/yarp/snapshots/seattlerb/op_asgn_index_command_call.txt
- test/yarp/snapshots/seattlerb/op_asgn_primary_colon_identifier1.txt
- test/yarp/snapshots/seattlerb/op_asgn_primary_colon_identifier_command_call.txt
- test/yarp/snapshots/seattlerb/op_asgn_val_dot_ident_command_call.txt
- test/yarp/snapshots/seattlerb/safe_op_asgn.txt
- test/yarp/snapshots/seattlerb/safe_op_asgn2.txt
- test/yarp/snapshots/unparser/corpus/literal/assignment.txt
- test/yarp/snapshots/unparser/corpus/literal/opasgn.txt
- test/yarp/snapshots/whitequark/and_asgn.txt
- test/yarp/snapshots/whitequark/op_asgn.txt
- test/yarp/snapshots/whitequark/op_asgn_cmd.txt
- test/yarp/snapshots/whitequark/op_asgn_index.txt
- test/yarp/snapshots/whitequark/op_asgn_index_cmd.txt
- test/yarp/snapshots/whitequark/or_asgn.txt
- test/yarp/snapshots/whitequark/ruby_bug_12402.txt
- test/yarp/snapshots/whitequark/send_op_asgn_conditional.txt
Fixes https://github.com/ruby/yarp/issues/1236
This is definitely a tradeoff, because now we don't have a single call node anymore. However, I think this is acceptable considering the call node couldn't represent that actually 2 methods get called when you have these nodes. So it would have been confusing to client libraries anyway.
> Call and operator write ergonomics

- lib/yarp.rb
- lib/yarp/pattern.rb
- test/yarp/pattern_test.rb
- yarp.gemspec
This is a feature that I have in Syntax Tree that I've been missing in YARP, so I'm porting it over. This allows you to define a `YARP::Pattern` object that knows how to compare itself against YARP nodes and determine if it matches. Effectively you can think of this as an object that represents a pattern matching expression.
For example:
```ruby
case node
in InstanceVariableReadNode[name: /^@B/i]
end
```
That works well when you have a specific call site where you want to compare against nodes, but doesn't work as well if you want it as a variable such that you can pass it around and compare programmatically. Instead, you can now do:
```ruby
pattern = YARP::Pattern.new("InstanceVariableReadNode[name: /^@B/i]")
if pattern.call(node)
end
```
These patterns also know how to walk trees to …
> Introduce YARP::Pattern

- lib/yarp.rb
- test/yarp/location_test.rb
YARP's `end_column` is off by 1 compared to Syntax Tree, e.g.:
```
ruby-lsp(main):009> SyntaxTree.parse("class Foo\nend").child_nodes.first.body.first.location
=>
#<SyntaxTree::Location:0x00000001073f7a48
@end_char=13,
@end_column=3, # <-----
@end_line=2,
@start_char=0,
@start_column=0,
@start_line=1>
```
vs
```
ruby-lsp(main):034> location = YARP.parse("class Foo\nend").value.child_nodes.first.body.first.location
ruby-lsp(main):036> location.end_offset
=> 13
ruby-lsp(main):037> location.end_column
=> 2 # <-----
ruby-lsp(main):038> location.end_line
=> 2
ruby-lsp(main):039> location.start_offset
=> 0
ruby-lsp(main):040> location.start_column
=> 0
ruby-lsp(main):041> location.start_line
=> 1
```
This should probably be marked as a breaking change.
> Fix `Location#end_column`

- ext/yarp/extension.c
- ext/yarp/extension.h
- templates/ext/yarp/api_node.c.erb
- templates/lib/yarp/serialize.rb.erb
- test/yarp/encoding_test.rb
Currently, when using `Node#slice` for a source that includes unicode characters, we're getting the wrong return. The reason is because we're not taking the encoding into consideration.
Example
```ruby
YARP.parse("á").value.slice
```
We should take the encoding into consideration, so that `slice` returns the expected strings.
> Consider source encoding for `slice`

- .gitignore
- Gemfile.lock
- docs/serialization.md
- include/yarp/util/yp_constant_pool.h
- rust/yarp-sys/src/lib.rs
- src/util/yp_constant_pool.c
- src/yarp.c
- templates/ext/yarp/api_node.c.erb
- templates/java/org/yarp/Loader.java.erb
- templates/lib/yarp/serialize.rb.erb
- templates/src/serialize.c.erb
- test/yarp/parse_serialize_test.rb
Before this commit, constants in the constant pool were assumed to be slices of the source string. This works in _almost_ all cases.
There are times, however, when a string needs to be synthesized. This can occur when passing in locals that need to be scoped through eval, or when generating method names like `foo=`.
After this commit, there is a single bit `owned` boolean on constants in the pool that indicates whether or not it is a slice of the source string. If it is not, it is assumed to be allocated memory that should be freed by the constant pool when the constant pool is freed.
When serializing, constants now take up 9 bytes instead of 8. The first byte indicates whether or not it is an owned string. When it is, instead of 4 bytes for the source offset and 4 bytes for the length it …
> Introduce owned constants

- src/yarp.c
Using the macros makes everything a little bit more concise and clearer.
> use `YP_LOCATION_*_VALUE` macros more consistently

- lib/yarp.rb
- test/yarp/comments_test.rb
Development tools like RDoc or LSPs need to show comments in certain situations as they are considered documentation. The most prominent example is to implement hover in an LSP, where we want to show the documentation for a given node.
Currently, there's no easy way to figure out which comments are associated with each node. Let's bring in SyntaxTree's algorithm for attaching comments to locations so that we can easily ask a location what comments exist there.
> Add ParseResult#attach_comments! to tie comments to their locations

- .github/workflows/truffleruby.yml
To avoid unnecessary noise, e.g. https://github.com/andyw8/yarp/actions
> Prevent truffleruby cron job from running on forks

- config.yml
- src/yarp.c
- test/yarp/location_test.rb
- test/yarp/snapshots/unparser/corpus/literal/if.txt
- test/yarp/snapshots/whitequark/cond_match_current_line.txt
These are replacements for regular expressions when they are used alone as the predicate of a conditional. That's because they are significantly different from a regular expression because they are not evaluated for truthyness, but instead evaluated as a match against the last line read by an IO object.
> Introduce MatchLastLineNode and InterpolatedMatchLastLineNode

- config.yml
- include/yarp.h
- src/yarp.c
- test/yarp/location_test.rb
- test/yarp/snapshots/alias.txt
- test/yarp/snapshots/seattlerb/alias_gvar_backref.txt
- test/yarp/snapshots/seattlerb/alias_resword.txt
- test/yarp/snapshots/seattlerb/dsym_to_sym.txt
- test/yarp/snapshots/unparser/corpus/literal/alias.txt
- test/yarp/snapshots/whitequark/alias.txt
- test/yarp/snapshots/whitequark/alias_gvar.txt
Into AliasGlobalVariableNode and AliasMethodNode. These have different enough semantics that we feel comfortable splitting them up.
Fixes https://github.com/ruby/yarp/issues/1432
> Split AliasNode

- rust/yarp/build.rs
When I wrote `ConstantId::as_slice`, I misunderstood how `yp_constant_id_t` works in concert with `yp_constant_pool_t`: it's not a straight index into the pool of constants.
This implementation is, of course, suboptimal in the sense that we're taking what should be a cheap operation and making it linear in the number of constant ids the program contains, but it is at least correct.  I don't have a test for this, as the example that I was seeing this on doesn't fail as a standalone test in the testsuite, for reasons I don't fully understand.
It would not be entirely surprising to me if everybody using the C API gets bitten by this.  Happy to rewrite the constant pool implementation so it works more like one would expect.
> [rust] fix accessing `ConstantId` slices

- templates/java/org/yarp/Nodes.java.erb
* Locations are excluded because those will be removed soon.
Before:
```
/home/runner/work/yarp/yarp/test/yarp/fixtures/xstring.txt
ProgramNode
StatementsNode
XStringNode[Li]
InterpolatedXStringNode
StringNode[Li]
EmbeddedStatementsNode
StatementsNode
CallNode
StringNode
XStringNode[Li]
XStringNode[Li]
```
After:
```
/home/eregon/code/yarp/test/yarp/fixtures/xstring.txt
ProgramNode
locals: 
statements: StatementsNode
body: 
XStringNode[Li]
unescaped: "foo"
InterpolatedXStringNode
parts: 
StringNode[Li]
unescaped: "foo "
EmbeddedStatementsNode
statements: StatementsNode
body: 
CallNode
receiver: null
arguments: null
block: null
flags: 2
name: "bar"
StringNode
unescaped: " baz"
XStringNode[Li]
unescaped: "foo"
XStringNode[Li]
unescaped: "foo"
```
cc @enebo
> Improve #toString() for Java nodes by showing field names and field values

- ext/yarp/extension.c
Noticed this while trying to valgrind a `YARP::Debug.profile_file` loop with a bunch of files.
> free strings in the ruby extension

- src/yarp.c
Following up on #1483, this removes our usage of varargs entirely. Under the new approach we make explicit methods for the various signatures. Because we know the type of everything any it's very consistent, this makes it easier for compilers to inline.
Also, I renamed the functions to be more consistent with each other so that we'll have some more internal consistency.
> Remove varargs entirely

- src/yarp.c
- test/yarp/errors_test.rb
If the read_name is invalid, we shouldn't try to set a write name.
Fixes #1488
> Write names should not underflow size_t

- config.yml
- src/yarp.c
- test/yarp/location_test.rb
- test/yarp/snapshots/regex.txt
- test/yarp/snapshots/whitequark/lvar_injecting_match.txt
This rarely used node holds information about the local variables that need to get written in the case a regular expression is used on the left-hand side of a =~ operator and it has named capture groups.
Note that we already "handled" these nodes by adding locals to the AST, but we didn't actually expose this information, making it difficult to compile.
The general idea behind this node is that it maintains the ability for consumers to find all of the call nodes in the tree easily so it's not flattening down. However, it should be okay because you hopefully don't need any information in the call node to determine what to compile because the locals list is on the top level.
Fixes #1459
> Introduce MatchWriteNode

- src/yarp.c
- test/yarp/errors_test.rb
- test/yarp/snapshots/for.txt
- test/yarp/snapshots/unparser/corpus/literal/for.txt
- test/yarp/snapshots/whitequark/for.txt
This simplifies how we handle multi-targets, and also fixes a bug we had where for loops were always getting multi-targets, even when there was only a single target.
Fixes #1434
> Simplify multi-target parsing

- config.yml
- src/yarp.c
- test/yarp/fixtures/hashes.txt
- test/yarp/location_test.rb
- test/yarp/snapshots/hashes.txt
- test/yarp/snapshots/if.txt
- test/yarp/snapshots/rescue.txt
- test/yarp/snapshots/seattlerb/assoc__bare.txt
- test/yarp/snapshots/whitequark/hash_pair_value_omission.txt
- test/yarp/snapshots/whitequark/keyword_argument_omission.txt
Fixes #1447
We now always insert an implicit node into a hash value when the hash value is omitted. This should make it easier on compilers and static analysis tools to determine what is actually going on without having to look at the local tables themselves. Because we have different nodes types for these nodes, tools can still consistently handle/ignore them as they like. As a bonus, all of the implicit nodes are very small.
> Add implicit nodes for ommitted hash values

- Gemfile
- rakelib/test.rake
This PR implements @eregon 's idea (thank you!) from the discussion in #1498: we can separate `ruby_memcheck` into its own group, and handle its non-presence.  This change enables people to install a smaller set of gems if they so choose.
> separate `ruby_memcheck` into its own group

- lib/yarp.rb
- test/yarp/regexp_test.rb
Fixes #1516
I'm trying to match the final `Regexp` constants with `RegularExpressionNode#options` and `InterpolatedRegularExpressionNode#options`.
I don't know if this is a good approach. If it's not, feel free to close unceremoniously! ❤️
> Return Regexp options that match MRI for e, u, s, and n

- src/yarp.c
- test/yarp/comments_test.rb
- test/yarp/parse_test.rb
Fixes https://github.com/ruby/yarp/issues/1443
This is a breaking change: Comments will no longer include the line break. 
Co-authored with @kddnewton and @vinistock.
> Fix behaviour of locations for comments

- templates/lib/yarp/node.rb.erb
- test/yarp/dispatcher_test.rb
This commit changes the node template to create a dispatcher class, which can be used to walk an AST an emit events to all registered listeners.
This is useful when performing several types of analysis on the same AST to avoid having to perform several rounds of visits. Two main examples are:
- LSPs: each different request can be a listener, which contains logic specific only to that request
- Linters: each linter rule can be a listener that also encapsulates logic only related to itself
For both of them, this allows the complete analysis to be completed in a single round of visits, saving numerous method dispatches and improving performance.
> Add node event dispatcher

- rust/yarp/build.rs
- rust/yarp/src/lib.rs
This function helps eliminate the need for exposing raw pointers in the public API, and is just plain easier to read than dealing with a bunch of offset arithmetic.
> [rust] add `Location::join`

- src/util/yp_constant_pool.c
...so that we can use cheap masks for resolving hash table insertions instead of expensive modulo.
This change improves the performance of:
```ruby
debug = YARP.const_get(:Debug)
files.each do |file|
debug.profile_file(file)
end
```
by about 5% on a subset of Stripe's codebase.  Some of this might just be due to having slightly higher default constant pool sizes that don't requiring resizing.
> force constant pool capacity to be a power of 2

- src/yarp.c
Fixes a potential null pointer dereference which is reported by the clang-analyzer.
clang-analyzer report (stripped version):
```
Array access (via field 'start') results in a null pointer dereference
Control jumps to 'case YP_TOKEN_PIPE_PIPE_EQUAL:'  at line 13590
Control jumps to 'case YP_CALL_NODE:'  at line 13648
Calling 'yp_call_node_variable_call_p': 
Returning without writing to 'node->message_loc.start'
Returning from 'yp_call_node_variable_call_p': 
Assuming the condition is false: 
Taking false branch
Calling 'parse_target': 
Control jumps to 'case YP_CALL_NODE:'  at line 8418
Assuming field 'start' is equal to NULL: 
Left side of '&&' is false
Assuming field 'start' is equal to NULL: 
Left side of '&&' is true
Array access (via field 'start') results in a null pointer …
```
> Fix a possible null pointer derefence

- include/yarp/util/yp_constant_pool.h
- rust/yarp/build.rs
- src/util/yp_constant_pool.c
- src/yarp.c
- templates/ext/yarp/api_node.c.erb
- templates/src/serialize.c.erb
So that we're not potentially guessing at the size
> Explicitly use u32 for constant pool

- ext/yarp/extension.c
- include/yarp/unescape.h
- src/unescape.c
- src/yarp.c
- test/yarp/snapshots/spanning_heredoc.txt
- test/yarp/snapshots/strings.txt
- test/yarp/snapshots/whitequark/parser_slash_slash_n_escaping_in_literals.txt
- test/yarp/unescape_test.rb
Introduces a new flavor of unescaping, YP_UNESCAPE_WHITESPACE, which is the same as MINIMAL but also unescapes whitespace.
Note that a spanning_heredoc.txt fixture test is updated to be less wrong, but YARP's behavior doesn't yet fully match Ruby in this case.
Fixes #1505
> fix: handling escaped whitespace in a %w list

- test/yarp/parse_test.rb
CI is currently failing due to an issue with Ripper on the latest TruffleRuby version. This commit removes the offending tests from running, to ensure CI is green again.
> Ignore parsing specific files on TruffleRuby to make CI green

- .github/workflows/main.yml
- .gitignore
- config.yml
- docs/serialization.md
- lib/yarp/ffi.rb
- rakelib/serialization.rake
- src/yarp.c
- templates/include/yarp/ast.h.erb
- templates/java/org/yarp/Loader.java.erb
- templates/java/org/yarp/Nodes.java.erb
- templates/lib/yarp/serialize.rb.erb
- templates/src/serialize.c.erb
- templates/template.rb
* Add a include_location_fields argument for serialize functions.
* Add a byte in the header to indicate whether location fields are included.
* Fixes https://github.com/ruby/yarp/issues/807
cc @enebo
> Only keep semantic fields in Java, i.e. skip location fields

- src/yarp.c
I noticed while profiling on x86-64 Linux that `strlen` was coming up awfully high on the profile and traced it to `lex_keyword`:
1. There's not much reason to recompute the length of the keyword inside the function, when the caller already knows that information and has gone to some trouble to verify it prior to calling `lex_keyword`.
2. The version of GCC (9.4.0) I was using didn't want to inline `lex_keyword` without adding the `inline` keyword.  Clang on my arm64 mac already inlines this function without `inline`, but this code is hot enough that I think it's worth giving an explicit hint to the compiler about what it should do.
These changes speed up parsing a subset of Stripe's codebase by 4-5%.  Each change described above is responsible for about half of that speedup.
> encourage the compiler to compile `lex_keyword` more efficiently

- rust/yarp/src/lib.rs
This just exposes useful information to Rust.
> [rust] add `ParseResult::frozen_string_literals`

- include/yarp/defines.h
Syncing changes that were made to ruby/ruby back to ruby/yarp
> Suppress macro redefinition warnings

- src/yarp.c
> use `yp_statements_node_body_length` a little bit more

- src/yarp.c
- test/yarp/errors_test.rb
Rejects where the predicate of `while` and `until` is not "closed".
```ruby
while 0 0; foo; end
until 0 0; foo; end
```
Ruby does not allow these:
```
ruby -c test.rb
test.rb: test.rb:1: syntax error, unexpected integer literal, expecting `do' for condition or ';' or '\n' (SyntaxError)
while 0 0; foo; end
^
test.rb:2: syntax error, unexpected integer literal, expecting `do' for condition or ';' or '\n'
until 0 0; foo; end
^
```
> Check predicate of `while` and `until`

- include/prism/util/pm_constant_pool.h
- rust/prism/build.rs
- src/util/pm_constant_pool.c
- templates/ext/prism/api_node.c.erb
- templates/src/serialize.c.erb
> Constants refactor

- src/prism.c
- test/prism/errors_test.rb
Closes #1574
Extend the check introduced in https://github.com/ruby/yarp/pull/1561 for `elsif`
> Check whether the predicate is closed for conditionals

- src/prism.c
Fixes #1612 .  This requires a little more typing, but I think it's worth it so people don't have to think about the special case where `peek_string` would return memory outside of the currently-being-parsed string.
cc @stevenjohnstone
> remove `peek_string` to avoid subtle memory issues

- rust/prism/src/lib.rs
Noticed this while working on #1620.
> [rust] fix clippy `ptr_cast_constness` warning

- config.yml
- rust/prism-sys/build.rs
- rust/prism/build.rs
- rust/prism/src/lib.rs
- templates/include/prism/ast.h.erb
The raw `flags()` accessor that is currently exposed is functional, but seeing as how none of the relevant constants for the flag values are exported in `prism-sys`, `flags()` isn't very useful.  Let's write actual functions for each of the relevant flags, which will hopefully result in clearer code and make it so people don't have to worry about the bit-twiddliness of flag storage.
> [rust] add flag accessors on nodes

- lib/prism/parse_result.rb
Currently when calling `location` from a node, the class is called with a trailing parenthesis. This change was introduced in #1549.
```
[1] pry(main)> program_node.location
=> (1,0)-(2,6))
```
```
[1] pry(main)> program_node.location
=> (1,0)-(2,6)
```
> Remove trailing parenthesis in `Location#pretty_print`

- rust/prism/src/lib.rs
`node` promised to return a `Node<'pr>`, but `'pr` is the lifetime for the slice that `ParseResult` holds.  In reality, the returned node should be bounded by the lifetime of the `ParseResult` itself, just like the return values for `errors`, `comments`, and `warnings`.
Since this code was wrong, Rust was perfectly happy to let `Node` references outlive the `ParseResult` so long as those `Node` references didn't outlive the slice being parsed.
> [rust] fix lifetime for `ParseResult::node`

- src/prism.c
- test/prism/errors_test.rb
```
➜  prism git:(haldun/duplicated-shadow-arg) ✗ cat test.rb
tap{|a;a|}
➜  prism git:(haldun/duplicated-shadow-arg) ✗ ruby -c test.rb 
test.rb: test.rb:1: duplicated argument name (SyntaxError)
tap{|a;a|}
^
➜  prism git:(haldun/duplicated-shadow-arg) ✗ ./bin/parse test.rb 
Errors:
[#<Prism::ParseError @message="Repeated parameter name" @location=#<Prism::Location @start_offset=7 @length=1 start_line=1>>]
```
> Check for duplicate names in shadow args

- lib/prism/node_ext.rb
- test/prism/constant_path_node_test.rb
Add `full_name` to both `ConstantPathNode` and `ConstantPathTargetNode`, so that one can easily figure out the complete name of the constant being referenced.
> Add full_name to `ConstantPathNode` and `ConstantPathTargetNode`

- include/prism/parser.h
- src/prism.c
- test/prism/snapshots/for.txt
- test/prism/snapshots/whitequark/for.txt
- test/prism/snapshots/whitequark/for_mlhs.txt
A transparent scope is a scope that cannot have local variables added to it's local table. When a local is added to it's table, it instead gets added to the first non-transparent parent scope.
This is used in for loops to ensure the correct depth for local variables inside the body
> Introduce transparent scopes.

- src/prism.c
- test/prism/errors_test.rb
Emit error for the following cases:
```ruby
a in _1
a => _1
1 => a, _1
1 in a, _1
```
Related #1580
This PR does not handle the case `/(?<_1>)/ =~ a` hence it is not closing the mentioned issue.
> Emit error when assigning to a numbered parameter

- include/prism/node.h
- src/prism.c
So when building instruction sequences for a scope we can reference items from the parent. This is useful for for loops, where the local variable tables from the parent scope will need to be referenced.
> Attach the ast node node to the scope

- src/prism.c
- test/prism/snapshots/for.txt
- test/prism/snapshots/unparser/corpus/literal/for.txt
- test/prism/snapshots/whitequark/for.txt
- test/prism/snapshots/whitequark/for_mlhs.txt
In CRuby's parser locals in for nodes appear deeper in the ast than they do in Prism, but we can fix that with a transparent scope
> Increase the depth for the For node index variable

- src/prism.c
- test/prism/errors_test.rb
Closes #1562
Also fixes code where Ruby rejects but Prism accepts:
```ruby
{x:'y':}
```
> Fix parsing symbols in strings after labels

- .gitignore
- bin/parse
- docs/serialization.md
- ext/prism/extension.c
- include/prism/parser.h
- java/org/prism/ParseResult.java
- lib/prism/ffi.rb
- lib/prism/lex_compat.rb
- lib/prism/parse_result.rb
- rakelib/check_manifest.rake
- src/diagnostic.c
- src/prism.c
- templates/java/org/prism/Loader.java.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
- test/prism/magic_comment_test.rb
- test/prism/parse_test.rb
* Magic comments now get attached to the parse result object
* We now support the emacs and vim syntax, so to my knowledge we are now 1:1 with CRuby
We still don't properly support:
* The `warn_indent` magic comment
* The `shareable_constant_value` magic comment
But now that we are handling the syntax all in one place, adding these should be much easier.
Fixes #574
> Parse magic comments

- config.yml
- templates/ext/prism/api_node.c.erb
- templates/include/prism/ast.h.erb
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
- templates/template.rb
Moves the common flag bits to the top. This lets us eliminate the `COMMON` constant, and also allows us to group encoding flags on a nibble so we can more easily mask them.
> Move common flags to top bits

- lib/prism/lex_compat.rb
Move common ``results << token`` outside case-when.
> Simplify DedentingHeredoc#to_a

- README.md
This PR fixes missing Prism logo image in the website. https://ruby.github.io/prism/
> [DOC] Fix missing Prism logo image in the website

- lib/prism/ffi.rb
Only remove const prefix from non-pointer types.
> Avoid unnecessary delete_prefix in LibRubyParser.resolve_type

- include/prism.h
- include/prism/node.h
- src/prism.c
Amend ScopeNode to point to previous ScopeNode, and to have void* pointers to constants and index_lookup_table
> Change ScopeNode to point to previous ScopeNode

- src/prism.c
- test/prism/regexp_test.rb
You can't encoding a string with more than one encoding so ensure that the last one wins.
> Ensure last encoding flag wins

- include/prism/util/pm_constant_pool.h
- lib/prism/debug.rb
- src/prism.c
- src/util/pm_constant_pool.c
- templates/src/serialize.c.erb
- test/prism/errors_test.rb
- test/prism/snapshots/methods.txt
- test/prism/snapshots/seattlerb/defn_arg_forward_args.txt
- test/prism/snapshots/seattlerb/defn_args_forward_args.txt
- test/prism/snapshots/seattlerb/defn_forward_args.txt
- test/prism/snapshots/seattlerb/defn_forward_args__no_parens.txt
- test/prism/snapshots/whitequark/endless_method_forwarded_args_legacy.txt
- test/prism/snapshots/whitequark/forward_arg.txt
- test/prism/snapshots/whitequark/forward_arg_with_open_args.txt
- test/prism/snapshots/whitequark/forward_args_legacy.txt
- test/prism/snapshots/whitequark/trailing_forward_arg.txt
* The constant pool didn't have the concept of a constant string like `pm_string_t`, meaning it allocated memory even if the value was known at compile time. This has been fixed.
* When `...` is present in a method definition, you can use `*` and `&` to forward subsets of all of the parameters. This has been fixed.
* I changed the way the `Debug` module worked when comparing locals in the locals test. This makes it much more obvious where we need anonymous locals to handle specific values.
> Some constant pool fixes and enhancements

- java/org/prism/ParseResult.java
- templates/java/org/prism/Loader.java.erb
- templates/src/serialize.c.erb
I don't think there is any value to have comments serialized for the Java Loader, it's just making the serialized size bigger.
Before:
```
be rake serialized_size:topgems
Total sizes for top 100 gems:
total source size:      90207647
total serialized size:  56131852
total serialized/total source: 0.622
Stats of ratio serialized/source per file:
average: 0.745
median:  0.724
1st quartile: 0.537
3rd quartile: 0.924
min - max: 0.036 - 3.532
```
After:
```
be rake serialized_size:topgems
Total sizes for top 100 gems:
total source size:      90207647
total serialized size:  53065393
total serialized/total source: 0.588
Stats of ratio serialized/source per file:
average: 0.716
median:  0.702
1st quartile: 0.496
3rd quartile: 0.913
min - max: 0.019 - 3.519
```
So that's quite a big saving in …
> Exclude comments when only serializing semantic fields

- lib/prism/lex_compat.rb
> Avoid String#chars in DedentingHeredoc#to_a

- bin/lex
This adds lex output to bin/lex, but does not use it in comparison.
Useful for cases where the the compat layer changes details about what Prism is actually lexing.
> Add uncompat lex output

- .github/workflows/rust-bindings.yml
- rust/prism-sys/build.rs
- rust/prism-sys/rustfmt.toml
- rust/prism-sys/tests/node_tests.rs
- rust/prism-sys/tests/pack_tests.rs
- rust/prism-sys/tests/parser_tests.rs
- rust/prism-sys/tests/utils_tests.rs
- rust/prism/build.rs
- rust/prism/rustfmt.toml
- rust/prism/src/lib.rs
Consistent formatting is nice, so let's enable it. I tried to configure `rustfmt.toml` to minimize big diffs to keep the original struct of the code as much as possible, since the default settings made a very noisy diff.
> Use `cargo fmt`

- src/prism.c
Referencing them as constants in case they need to change in the future.
> Allow regexp flags to change

- config.yml
- lib/prism/pattern.rb
- src/prism.c
- test/prism/snapshots/patterns.txt
- test/prism/snapshots/seattlerb/case_in.txt
- test/prism/snapshots/seattlerb/case_in_37.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_assign.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_paren_assign.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_paren_true.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_rest.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_rest_solo.txt
- test/prism/snapshots/seattlerb/parse_pattern_058.txt
- test/prism/snapshots/seattlerb/parse_pattern_058_2.txt
- test/prism/snapshots/seattlerb/parse_pattern_069.txt
- test/prism/snapshots/seattlerb/parse_pattern_076.txt
- test/prism/snapshots/unparser/corpus/literal/pattern.txt
- test/prism/snapshots/whitequark/multiple_pattern_matches.txt
- test/prism/snapshots/whitequark/newline_in_hash_argument.txt
- test/prism/snapshots/whitequark/pattern_matching_single_line_allowed_omission_of_parentheses.txt
Previously `kwrest` was never used and ** got dumped into the regular assoc list when it was the first element in the list.
> Fix parsing ** within hash patterns

- docs/ruby_api.md
- ext/prism/extension.c
- include/prism.h
- lib/prism/ffi.rb
- src/prism.c
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
- test/prism/parse_inline_comments_test.rb
Provide APIs to retrieve _just_ the inline comments of a file, without needing to reify an AST.
> Inline comments

- templates/java/org/prism/Nodes.java.erb
- templates/javascript/src/nodes.js.erb
- templates/lib/prism/node.rb.erb
- templates/rbi/prism.rbi.erb
- templates/sig/prism.rbs.erb
The existing comment generation was hard to read and was making a lot of string manipulation. However, ERB files are already designed to do string manipulation, so we can use that instead.
So, instead of doing a split and a map, I opted to use the `#each_line` method to iterate over the lines of the file.
Also, in order to add an optional space padding at the beginning of the line, I opted to unconditionally pad it with a space and then right trim it. This makes sure that no space is left behind if the line is empty, but a space is added if the line is not empty. It also ensures that the line endings that are kept by `each_lines` are also removed.
> Improve comment generation in templates

- docs/ruby_api.md
- ext/prism/extension.c
- include/prism.h
- lib/prism/ffi.rb
- src/prism.c
- test/prism/parse_comments_test.rb
There was a bug where the serialization API didn't line up with the Ruby API because the serialization API would return all comments. To simplify, just return all comments in both cases, `__END__` and `=begin` are so rare anyway.
> parse_inline_comments -> parse_comments

- .github/workflows/truffleruby.yml
TruffleRuby doesn't intend to rename those, they are debug methods, so let's use their current name.
This should let the truffleruby workflow be green.
FYI @andrykonchin
> Fix debug method names in truffleruby workflow

- Makefile
- src/prism.c
- templates/ext/prism/api_node.c.erb
It's possible for us to parse a constant that is invalid in the current encoding. To fix this, we wrap the intern function in an rb_protect to ensure we always put a valid symbol into the AST.
Fixes #1593
> Handle invalid constants in the constant pool

- ext/prism/extension.c
- lib/prism/parse_result.rb
- rakelib/check_annotations.rake
- rakelib/check_manifest.rake
- rbi/prism_static.rbi
- sig/prism_static.rbs
- templates/lib/prism/serialize.rb.erb
- test/prism/comments_test.rb
We were previously holding a type field on Comment to tell what kind of comment it was. Instead, let's just use actual classes for this. This makes it nicer to work with when you call `Prism.parse_comments` because you can do `Prism.parse_comments(source).grep(Prism::InlineComment)`
> Split comment

- templates/java/org/prism/Nodes.java.erb
Current code was using startLine which was 1-based and adding it to findLine() which was returning a 1-based value.  This PR changes findLine() to be 0-based.
> Fix line calculations in Java Loading

- lib/prism/node_ext.rb
- test/prism/parameters_signature_test.rb
Nice to have for client libraries.
@seven1m I thought you might be able to use this to implement `Method#parameters`
> Provide Parameters#signature for mirroring Method#parameters

- Gemfile.lock
ruby_memcheck 2.2.1 has Shopify/ruby_memcheck#28 which should fix the CI.
> Bump ruby_memcheck to version 2.2.1 to fix CI

- templates/java/org/prism/Nodes.java.erb
There are cases where prism will run into a syntax error and advance to at least 1 byte past the end of source (beyond just regexps like as described in #1793).  There are many places this can happen so this PR fixes this issue by adjusting the offset we are trying to determine the line for to the last valid byteoffset in the source.
> Fix #1793.  offsets off of end of source should not assert.

- templates/java/org/prism/Nodes.java.erb
`setStartLine(int line)` should not have an assert to only accept positive values.  start line can be negative.
> Partial fix for #1783 for Java Loader

- templates/java/org/prism/Loader.java.erb
The original work nearly worked but 3 fields needed to be accessed by the extended type JRuby needs to create to properly have `getName()` return RubySymbol instead of j.l.String.
This PR additional removes an unused field when generating JRuby version of Loader.java because it is only needed for `getName()` when it returns j.l.String.
> Fix template generation of Loader.java for JRuby

- prism.gemspec
This should fix #1738
It simply specifies the uri for the source code in the gemspec and also adds the uri for the changelog, as per @kddnewton's suggestion.
> Add source code and changelog metadata to gemspec

- lib/prism/debug.rb
- src/prism.c
- test/prism/errors_test.rb
- test/prism/snapshots/methods.txt
- test/prism/snapshots/seattlerb/defn_arg_forward_args.txt
- test/prism/snapshots/seattlerb/defn_args_forward_args.txt
- test/prism/snapshots/seattlerb/defn_forward_args.txt
- test/prism/snapshots/seattlerb/defn_forward_args__no_parens.txt
- test/prism/snapshots/unparser/corpus/literal/block.txt
- test/prism/snapshots/whitequark/blockargs.txt
- test/prism/snapshots/whitequark/endless_method_forwarded_args_legacy.txt
- test/prism/snapshots/whitequark/forward_arg.txt
- test/prism/snapshots/whitequark/forward_arg_with_open_args.txt
- test/prism/snapshots/whitequark/forward_args_legacy.txt
- test/prism/snapshots/whitequark/send_lambda.txt
- test/prism/snapshots/whitequark/trailing_forward_arg.txt
Previously, we were adding `*` and `&` to locals when `...` was found in a block parameter list. This was my mistake, I didn't realize this didn't work. Fixes #1739. Fixes #1785.
Previously, because we were adding those values, it allowed forwarding when it shouldn't have. For example, `def foo(...); bar(*); end` was allowed by prism, but shouldn't have been. Fixes #1776.
> Forwarding parameter fixes

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/fixtures/until.txt
- test/prism/fixtures/while.txt
- test/prism/snapshots/patterns.txt
- test/prism/snapshots/until.txt
- test/prism/snapshots/while.txt
Fix #1596
Fix #1771
Close #1773
This PR adds a `nonassoc` attribute to `pm_binding_powers_t`.
This value is used for handling non-ascciativility of `in` and `=>` correctly.
Usually, non-associativility can be handled by using `left` and `right` binding powers, but that is hard for `in` and `=>` since they do not call `parse_expression` recursively on parsing.
`foo => bar => baz` and `foo in bar => baz` is syntax valid, however, `in` and `=>` are not left associative.
Actually, `foo => bar => baz` is parsed as `foo => (bar => baz)` and the right hand side is a pattern (`CapturePatternNode`). `foo in bar => baz` is the same and `foo in bar in baz` and `foo => bar in baz` is syntax invalid.
This fix solves #1596.
Additionally, this modifies the binding power of `in` correctly, so it solves …
> Introduce non-associativility to `in` and `=>`

- .gitignore
- docs/javascript.md
- javascript/README.md
- javascript/src/index.js
- templates/javascript/src/nodes.js.erb
- templates/javascript/src/visitor.js.erb
- templates/template.rb
This pull request adds a new template for a `visitor.js` file in `javascript/src/`. This file implements a `BasicVisitor` and a `Visitor` class, very similar to the Ruby visitors which allow to traverse the Ruby AST in JavaScript.
An example of a custom `FooCalls` visitor in JavaScript would look like:
```js
import { loadPrism, Visitor } from "@ruby/prism"
class FooCalls extends Visitor {
visitCallNode(node) {
if (node.name === "foo") {
// Do something with the node
}
// Call super so that the visitor continues walking the tree
super.visitCallNode(node);
}
}
const fooVisitor = new FooCalls()
const parse = await loadPrism()
const parseResult = parse("foo()")
parseResult.value.accept(fooVisitor)
```
> Implement JavaScript visitors

- test/prism/errors_test.rb
Sorry, I forgot to add tests for error cases on previous PRs.
> Add tests for error cases on #1791, #1807, and #1810

- src/prism.c
- test/prism/fuzzer_test.rb
> fix: Handle zero-length block parameters in invalid Ruby

- include/prism/parser.h
- src/prism.c
- test/prism/fixtures/heredocs_nested.txt
- test/prism/snapshots/heredocs_nested.txt
Because the lex mode may be freed when popped, we need to store off this value for dedentation.
Co-authored-by: Kevin Newton <kddnewton@gmail.com>
> fix: nested heredoc use-after-free

- bin/encodings
- docs/encoding.md
- include/prism/enc/pm_encoding.h
- src/enc/pm_tables.c
- src/prism.c
- test/prism/encoding_test.rb
aka cp874. 
874 is a derivative of ISO-8859-11 but functionally equivalent for the required use case.
https://github.com/ruby/prism/issues/1843
Fixes #1857
> add Windows-874 encoding

- src/prism.c
clang analyzer reports two false positives about leaking memory. This PR silences these since we know that these are not actual memory leaks.
> Silence clang analyzer warnings for the memory leaks

- ext/prism/extconf.rb
It's causing issues with Gentoo builds and we're not testing this path anyway. Instead, require that the C extension statically links libprism.
Fixes #1719
> Remove disable static option

- include/prism/defines.h
- templates/java/org/prism/Loader.java.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
Reverts ruby/prism#1822
Apparently WORDS_BIGENDIAN is not being set automatically on s390x. We'll need a better feature detection to get this right, but in the meantime we'll revert to get CRuby CI back to green.
> Revert "Ensure serialized file is little endian"

- src/prism.c
- Instead of testing `parser->current.start + vlen <= parser->end` every time in `lex_keyword`, I moved the test to `lex_identifier`.
- Pass already cached value of `parser->current.start` to `lex_keyword` instead of accessing it directly within `lex_keyword`.
- Updated documentation comment for `lex_keyword`.
These changes seem to bring ~3% improvement.
> Optimize `lex_keyword`

- include/prism/enc/pm_encoding.h
- prism.gemspec
- src/enc/pm_big5_hkscs.c
- src/prism.c
- test/prism/encoding_test.rb
Attempting to make a dent on https://github.com/ruby/prism/issues/1843
This is the first time I've touched C code in over 10 years. Be gentle.
I attempted to match the overall end-point of the existing Ruby implementation for this. This is not much different from the Big5 encoding.
This compiles and passes tests for me, but I'm not particularly familiar with encodings or modern C so I'm sure I missed something.
> Big5 HKSCS encoding

- docs/heredocs.md
- src/prism.c
> Fix typos in comments and docs

- bin/lex
When encountering a situation where there is a mismatch at the very end of a file, and when `Prism.lex` produces a shorter output than `.lex_compat` and/or `.lex_ripper`, `bin/lex` itself fails with NoMethodError when calling `[0]` on `new` which is `nil`. This prevents outputting the actual mismatch.
This fix allows `new` to be `nil`, outputing `nil` in the 3rd column of `bin/lex` in this situation. (I can update this output approach if needed.)
> Fix `bin/lex` when encountering mismatch at EOF.

- lib/prism/ffi.rb
- lib/prism/parse_result.rb
- templates/lib/prism/serialize.rb.erb
- test/prism/ruby_api_test.rb
Fixes #1788 by introducing:
* `Location#start_character_offset`
* `Location#end_character_offset`
* `Location#start_character_column`
* `Location#end_character_column`
> Add character APIs for locations

- src/prism.c
- test/prism/snapshots/super.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/unparser/corpus/literal/super.txt
Fixes the locations of a few nodes where the location is derived from `pm_arguments_t`.
Closes #1895
> Fix locations derived from arguments

- include/prism/diagnostic.h
- src/diagnostic.c
- src/prism.c
- test/prism/errors_test.rb
Previously, we only supported error messages that were constant strings. This works for the most part, but there are some times where we want to include some part of the source in the error message to make it better.
For example, instead of "Token is reserved" it's better to write "_1 is reserved".
To do this, we now support allocating error messages at runtime that are built around format strings.
I don't actually think this should be the real solution here. Ideally we would provide the ability for these fields to be described so that we could template out some nice Ruby syntax error classes. But for now, this gets us closer to passing Ruby spec so I'd like to build this intermediate step.
cc @enebo this should allow us to start fixing some specific error message assertions. Now that we …
> Build the ability to format errors

- src/prism.c
- test/prism/errors_test.rb
> Check a token after targets more strictly

- lib/prism/node_ext.rb
- test/prism/constant_path_node_test.rb
When we introduced `full_name`, we forgot that Ruby allows you to do `self::Foo::Bar` or even `var::Foo::Bar`. The code currently breaks in those scenarios when trying to invoke `name`, since the nodes that represent the beginning of the path don't implement it (like `SelfNode`).
There are a few options on how we might fix this. This PR is just using `node.slice` if the node is not a constant read. We can omit the first part when it's not a constant. Or we can add a `name` field to the nodes that don't have it, just returning the slice.
Let me know how you prefer to deal with this scenario.
> Fix constant path full name when parent is not a constant

- src/prism.c
- test/prism/fixtures/methods.txt
- test/prism/snapshots/methods.txt
>  Fix `lex_state_beg_p`

- templates/java/org/prism/Nodes.java.erb
- templates/lib/prism/node.rb.erb
~A `Node#set_newline_flag` template for `OptionalNodeField` seems buggy.
If an `OptionalNodeField` is marked as a newline field, `NoMethodError` is raised at runtime.
Since there is no such field so far, it is not a problem.
This PR is for preventing the potential of bugs in the future.~
Because they are buggy, and actually they are dead code.
> Remove handling OptionalNodeField in set_newline_flag template

- templates/java/org/prism/Nodes.java.erb
* This is useful when desugaring and creating new nodes to not lose the newLineFlag.
For example when desugaring InterpolatedStringNode(StringNode StringNode) into a single StringNode.
I was thinking
```java
public void copyNewLineFlag(Nodes.Node to) {
if (newLineFlag) {
to.newLineFlag = true;
}
}
```
might be nice but it's actually pretty inconvenient for that example, so keep things simple.
> Add setNewLineFlag(boolean) for Java nodes

- templates/javascript/src/deserialize.js.erb
The `startOffset` variable is reassigned on line 93 and should therefore be declared using `let` instead of `const`.
> Use let declaration in scanConstant

- src/prism.c
- test/prism/errors_test.rb
- test/prism/fixtures/arrays.txt
- test/prism/snapshots/arrays.txt
Fix #1925
Fix #1927
Previously `pm_call_node_index_p` does not check about a block argument correctly and is not used in `parse_write` to check an index call node.
> Fix and reuse `pm_call_node_index_p`

- src/prism.c
- Introduced `fast_char_is_identifier` which assumes `parser->encoding_changed` is `false`.
- Use `fast_char_is_identifier` inside `lex_identifier`.
I see a ~10% improvement, but it would be great if someone can confirm this too.
> Optimize `lex_identifier`

- bin/parse
- docs/serialization.md
- ext/prism/extension.c
- include/prism/parser.h
- java/org/prism/ParseResult.java
- lib/prism/ffi.rb
- lib/prism/lex_compat.rb
- lib/prism/parse_result.rb
- src/prism.c
- templates/java/org/prism/Loader.java.erb
- templates/javascript/src/deserialize.js.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
- test/prism/comments_test.rb
It's not really a comment anyway. This removes it from the types of comments and instead makes it its own field on parse result and serialization as an optional location.
Fixes #1824.
> Move DATA parsing into its own parse result field

- src/prism.c
- test/prism/fixtures/arrays.txt
- test/prism/snapshots/arrays.txt
> Fix to parse `*` as forwarding in `foo[*]` case

- config.yml
- lib/prism/debug.rb
- src/prism.c
- test/prism/location_test.rb
- test/prism/snapshots/blocks.txt
- test/prism/snapshots/seattlerb/bug236.txt
- test/prism/snapshots/seattlerb/masgn_command_call.txt
- test/prism/snapshots/seattlerb/parse_pattern_051.txt
- test/prism/snapshots/unparser/corpus/literal/assignment.txt
- test/prism/snapshots/unparser/corpus/literal/block.txt
- test/prism/snapshots/unparser/corpus/literal/pattern.txt
- test/prism/snapshots/variables.txt
- test/prism/snapshots/whitequark/blockargs.txt
- test/prism/snapshots/whitequark/masgn_nested.txt
Fundamentally, `foo { |bar,| }` is different from `foo { |bar, *| }` because of arity checks. This PR introduces a new node to handle that, `ImplicitRestNode`, which goes in the `rest` slot of parameter nodes instead of `RestParameterNode` instances.
This is also used in a couple of other places, namely:
* pattern matching: `foo in [bar,]`
* multi target: `for foo, in bar do end`
* multi write: `foo, = bar`
Now the only splat nodes with a `NULL` value are when you're forwarding, as in: `def foo(*) = bar(*)`.
Fixes #1823
Fixes #1722
cc @enebo, @andrykonchin
> Implicit rest nodes

- docs/serialization.md
- ext/prism/extension.c
- include/prism/options.h
- include/prism/parser.h
- include/prism/util/pm_buffer.h
- src/options.c
- src/prism.c
- src/util/pm_buffer.c
- templates/ext/prism/api_node.c.erb
- templates/java/org/prism/Loader.java.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
- test/prism/parse_test.rb
Fix: https://github.com/ruby/prism/issues/1783
Ruby allows for 0 or negative line start, this is often used with `eval` calls to get a correct offset when prefixing a snippet.
e.g.
```ruby
caller = caller_locations(1, 1).first
class_eval <<~RUBY, caller.path, caller.line - 2
def some_method
#{caller_provided_code_snippet}
end
RUBY
```
The first commit rename all `varint` stuff to `varuint` to avoid confusion.
The second commit introduce the `varsint` (signed) type, and change `line` to be signed.
> Implement negative line numbers

- lib/prism/lex_compat.rb
- test/prism/fixtures/heredoc_with_comment.txt
- test/prism/snapshots/heredoc_with_comment_at_start.txt
Fixes a special case of the `:on_nl` token after a comment. When the token immediately preceding the comment is a `:HEREDOC_END` then the `:on_nl` is _not_ added. 
~~I had posted this fix in the issue, but let's just try opening a PR and see if the solution works for everyone.~~
UPDATE: This is now a different fix. I found the underlying problem.
When a comment follows a heredoc end, the end_offset of the comment at the _start_ of the heredoc end token. We must use the heredoc_end token's `end_offset` for the offset to be in the correct location.
The bug is caused when `if start_offset < end_offset` returns true because start_offset is at the end of the comment. It always finds the end of the heredoc, `"HEREDOC"` and thinks it's trailing whitespace. With the correct offset, it is not …
> Fix lex_compat for `<<HEREDOC # comment` at EOF

- src/prism.c
Just removing an unnecessary assignment in `parse_targets`.
> Remove no-op assignment

- src/prism.c
I don't know when it is changed, but the `not_provided` signature is changed.
> Fix `not_provided` comment

- src/prism.c
Now, `PM_DEBUG_LOGGING` can be available.
> Add missing context names to the switch in `debug_context`

- lib/prism/lex_compat.rb
- test/prism/fixtures/heredoc_with_comment.txt
The problem was deeper than just looking back a single token. You can push the heredoc_end token way back into the list. 
Unfortunately, we need to save the last location of a heredoc_end to see if it's the last token in the file. I feel like this is pretty inelegant, but it solve the problem more generally.
Fixes #1954 and all of the versions of this error that I brought up there.
> Fix comments after HEREDOCs again.

- docs/ruby_api.md
- ext/prism/extension.c
- include/prism.h
- lib/prism.rb
- lib/prism/ffi.rb
- templates/src/serialize.c.erb
- test/prism/ruby_api_test.rb
A lot of tools use Ripper/RubyVM::AbstractSyntaxTree to determine if a source is valid. These tools both create an AST instead of providing an API that will return a boolean only.
This new API only creates the C structs, but doesn't bother reifying them into Ruby/the serialization API. Instead it only returns true/false, which is significantly more efficient.
> Prism.parse_success?(source)

- rakelib/cargo.rake
This is a pretty minor cleanup, but a little more consistency is nice.  And if for some reason there's a third crate needed, everything will just start magically working with the `Rakefile` targets.
> [rust] be consistent about using `CRATES` in `cargo.rake`

- src/prism.c
- test/prism/errors_test.rb
- test/prism/fixtures/command_method_call.txt
- test/prism/snapshots/command_method_call.txt
Fix #1468
Fix #1575
To decide whether command-style method calls are allowed, this introduces a new parameter `accepts_command_call` to `parse_expression` and some functions.
Although one thinks this can be solved by operator precedence, it is hard or impossible, because the precedence of command-style calls is skewed (e.g. `! bar 1 ` is accepted, but `foo = ! bar 1` and `!! bar 1` are rejected.)
One of the most complex examples is that:
1. Even though `foo = bar = baz 1` and `foo, bar = baz 1` are accepted,
2. `foo, bar = baz = fuzz 1` is rejected.
To implement this behavior, this introduces a new binding power `PM_BINDING_POWER_MULTI_ASSIGNMENT` and uses it to distinguish which single assignments or multi assignments at their RHS.
> Fix to parse command-style method calls more correctly

- src/prism.c
We are testing the type of the current token but there is no way the current token can be changed before the test.
> Remove unnecessary match in `parse_arguments`

- README.md
Added an environment variable `PRISM_MAKE_FLAGS` so we can pass arguments to `make` while running `rake compile`. I find this useful to speed up the build process by passing the `-j` flag.
> Mention about `MAKEFLAGS` in `README.md`

- src/prism.c
- test/prism/fixtures/defined.txt
- test/prism/snapshots/defined.txt
It's possible to write the following and have it be valid Ruby:
```
defined?("foo"
)
```
But Prism wasn't taking the new line into account. This adds an `accept1` for a `PM_TOKEN_NEWLINE` to account for this. I've also updated the fixtures and snapshots to test this.
> Fix defined with new line

- config.yml
- src/prism.c
- test/prism/location_test.rb
- test/prism/snapshots/arrays.txt
- test/prism/snapshots/method_calls.txt
- test/prism/snapshots/seattlerb/masgn_arg_colon_arg.txt
- test/prism/snapshots/seattlerb/masgn_arg_ident.txt
- test/prism/snapshots/unparser/corpus/literal/assignment.txt
- test/prism/snapshots/whitequark/masgn_attr.txt
In this commit we're splitting up the call nodes that were in target positions (that is, for loop indices, rescue error captures, and multi assign targets).
Previously, we would simply leave the call nodes in place. This had the benefit of keeping the AST relatively simple, but had the downside of not being very explicit. If a static analysis tool wanted to only look at call nodes, it could easily be confused because the method would have 1 fewer argument than it would actually be called with.
This also brings some consistency to the AST. All of the nodes in a target position are now *TargetNode nodes. These should all be treated the same, and the call nodes can now be treated the same.
Finally, there is benefit to memory. Because being in a target position ensures we don't have some …
> Split up CallNode in target position

- src/prism.c
- test/prism/snapshots/seattlerb/bug190.txt
I don't pretend to understand what is going on here, but basically if you use a regular expression opening/closing that is not `/` then sometimes you need an escape and sometimes you don't. I derived these rules by running every value in US-ASCII until it matched.
Fixes #2031.
> Regexp terminator escapes

- src/prism.c
- templates/include/prism/ast.h.erb
The current way of setting/unsetting and testing flags on node was very verbose, and, as a result, was error prone.
This PR introduces the public macro `PM_NODE_FLAG_P(node, flag)` (exported from `ast.h`) to check if `flag` is set on `node`.
It also adds two methods in `prism.c` to set/unset flags on nodes: `pm_node_flag_set` and `pm_node_flag_unset`.
These make the code easier to read and less error-prone.
> Add public macro and internal functions for working with node flags

- src/prism.c
The previous implementation of hash deopt in #2016 was based on clearing the static literal flag on a hash node if the element that was being added was an array, hash or range node, or if the element was not a static literal in the first place.
However, this is not correct. First of all, the elements added to a hash node will primarily be assoc nodes, but never array, hash or range nodes. Secondly, the static literal flag is set on assoc nodes, only if the value in an assoc node is a static literal, so the key is never checked. As a result, the static literal flag on a hash node would never be cleared if the key wasn't a static literal.
This commit fixes this by clearing the static literal flag if:
1. the element is not an assoc node,
2. the element is an assoc node, but the key is not a …
> Fix hash deopt based on contents

- include/prism.h
`pm_node_destroy` accepts not only `root`, but also pointer to parser
> Fix typo in docs

- include/prism/parser.h
- src/prism.c
- test/prism/snapshots/seattlerb/aref_args_assocs.txt
- test/prism/snapshots/seattlerb/aref_args_lit_assocs.txt
- test/prism/snapshots/seattlerb/call_arg_assoc.txt
- test/prism/snapshots/seattlerb/call_args_assoc_trailing_comma.txt
- test/prism/snapshots/seattlerb/call_assoc.txt
- test/prism/snapshots/seattlerb/call_assoc_trailing_comma.txt
- test/prism/snapshots/seattlerb/method_call_assoc_trailing_comma.txt
- test/prism/snapshots/seattlerb/parse_opt_call_args_assocs_comma.txt
- test/prism/snapshots/whitequark/array_assocs.txt
The previous implementation in #2046 was incorrect since it was just checking for all keys in assoc nodes to be static literals but the actual check is that all keys in assoc nodes must be symbol nodes (Ref: https://github.com/ruby/ruby/blob/2f1d6da8c45590bf3461ed4bf051a4e1009eaf85/compile.c#L4577-L4578).
This commit fixes that implementation, and, also, aliases the flag to `PM_KEYWORD_HASH_NODE_FLAGS_SYMBOL_KEYS` so that ruby/ruby can start using the new flag name.
I intend to later change the real flag name to `PM_KEYWORD_HASH_NODE_FLAGS_SYMBOL_KEYS` and remove the alias.
> Fix the implementation of the flag on keyword hash nodes

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
This would impact `Object[{x:}]`
Fixes #2050
> Fix parse result for nesting pattern matching

- docs/ruby_api.md
Link: https://github.com/ruby/www.ruby-lang.org/pull/3156
function def: https://github.com/ruby/prism/blob/53ef1e8a193cc24d4ce3e0d2d2eade450125ce19/ext/prism/extension.c#L254-L258
From https://github.com/ruby/prism/pull/1763, filepath args of Prism.dump seems to moved in kwargs.
> Update args of Prism.dump on document

- src/prism.c
- test/prism/ruby_api_test.rb
Previously we would always push a new scope, which was inaccurate because eval can introduce locals in the caller's scope.
> Fix eval parsing depth

- src/prism.c
- test/prism/snapshots/unparser/corpus/literal/literal.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
String literal hash keys can't be mutated by the user so we should mark them as frozen. We were seeing instructions for hashes with string literal keys using two `putstring` instructions when it should be a `putobject` and `putstring`.
Code example:
```ruby
{ "a" => "b" }
```
Instructions before:
```
"********* Ruby *************"
== disasm: #<ISeq:<compiled>@<compiled>:1 (1,0)-(2,14)>
0000 putobject                              "a"                       (   2)[Li]
0002 putstring                              "b"
0004 newhash                                2
0006 leave
"********* PRISM *************"
== disasm: #<ISeq:<compiled>@<compiled>:1 (1,0)-(1,14)>
0000 putstring                              "a"                       (   1)[Li]
0002 putstring                              "b"
0004 …
```
> String literal hash keys should be frozen

- sig/prism_static.rbs
- templates/lib/prism/node.rb.erb
- templates/sig/prism.rbs.erb
Hello, I noticed there was mismatches between definitions of Node methods which used positional parameters and the RBS definitions which used keyword. This PR adjusts the templates to emit positional. I also updated prism_static.rbs based on the changes I saw in the other classes.
Question: I used steep to figure out what needed work. Do you want to add tests to prevent stuff from going out of sync, or is it too soon?
> RBS type fixes for positional parameters

- templates/javascript/src/visitor.js.erb
When I tried to use npm's `@ruby/prism` package in my TypeScript project, I encountered the following error in tsc:
```
$ npm run compile
> vscode-ruby-light@0.5.2 compile
> npm run compile:tsc
> vscode-ruby-light@0.5.2 compile:tsc
> tsc -b
server/node_modules/@ruby/prism/types/visitor.d.ts:15:17 - error TS2304: Cannot find name 'Node'.
15     visit(node: Node): void;
~~~~
server/node_modules/@ruby/prism/types/visitor.d.ts:27:27 - error TS2304: Cannot find name 'Node'.
27     visitChildNodes(node: Node): void;
~~~~
Found 2 errors.
```
After a little investigation, it appears that some type names described in jsdoc are incorrect. I changed this part locally from `Node` to `nodes.Node` and confirmed that this tsc compilation passes.
> Fix `Cannot find name 'Node'` error in types/visitor.d.ts

- ext/prism/extension.c
- include/prism/options.h
- include/prism/parser.h
- lib/prism/ffi.rb
- src/options.c
- src/prism.c
- test/prism/snapshots/arrays.txt
- test/prism/snapshots/unparser/corpus/literal/assignment.txt
- test/prism/snapshots/whitequark/masgn_attr.txt
Fixes #2102
Because this is a user-facing change, we also need to deal with the fact that CRuby 3.3.0 was just released.
In order to support workflows that want to parse exactly as CRuby parses in a specific version, this PR introduces a new option to the options struct that is "version". This allows you to specify that you want "3.3.0" parsing.
I'm not sure if this is the correct solution. Another solution is to just fork and keep around the old branch for security patches. Or we could keep around a copy of the source files within this repository as another directory and only update when necessary. There are a lot of potential solutions here.
Because this change is so small and the check for it is so minimal, I've decided to go with this enum. If this ends up entirely cluttering the …
> IndexTargetNode should always have ATTRIBUTE_WRITE

- config.yml
- rust/ruby-prism-sys/build/main.rs
- templates/include/prism/ast.h.erb
- templates/lib/prism/node.rb.erb
- templates/template.rb
In an effort to further improve our documentation, this commit introduces the concept of templating comments onto fields. I hope to get more documentation above the nuances of specific fields this way going forward.
With this, we template the comments into C and Ruby. I haven't done JS/Rust/Java yet, but we can touch those in the future, especially once their documentation is published.
> Introduce field comments

- src/prism.c
- test/prism/fixtures/case.txt
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/case.txt
- test/prism/snapshots/patterns.txt
Fix #2094
The part of `parse_variable_call` for variables was split into a new function `parse_variable` and used it.
> Fix parsing pinned local variable pattern for numbered parameter

- templates/include/prism/ast.h.erb
- templates/java/org/prism/Nodes.java.erb
- templates/lib/prism/node.rb.erb
- templates/template.rb
* Also use `field.each_comment_line` to simplify other usages of field comments.
> Include field comments in Java source

- config.yml
This PR adds documentation comments in `config.yml` for `HashNode`, `AssocNode` and `AssocSplatNode`.
> Document `HashNode`, `AssocNode` and `AssocSplatNode` fields.

- ext/prism/extension.c
- include/prism.h
- include/prism/util/pm_buffer.h
- src/prism.c
- src/util/pm_buffer.c
Adds `pm_parser_errors_format`, which can be used to format the list of errors on a parser into a given buffer.
> Provide the ability to format errors

- javascript/src/parsePrism.js
- lib/prism/ffi.rb
This PR makes it possible to pass a set of options to `parsePrism`. It replicates the behavior present in the Ruby `dump_options` method in ffi.rb by packing the options into a binary string and passing a pointer as the last argument to `pm_serialize_parse`.
> Add ability to pass options to JavaScript's parsePrism function

- rbi/prism_static.rbi
- templates/lib/prism/node.rb.erb
@st0012 I agree with your assessment here, I don't think we should be adding signatures for methods that don't exist. That feels pretty wrong.
I assume this was added because people wanted to work with multiple nodes and treat them the same, but sorbet's typing system makes interfaces very difficult without including a module. For that reason this PR introduces `Prism::AnyNode`, a type alias for all of the existing node types. Hopefully that should solve the root of the issue, because people can use that signature instead.
@vinistock sorry I didn't catch this in the initial code review when you first introduced the RBI. Can this solution work for your needs? I would really prefer to not provide signatures for methods that don't exist.
> Provide abstract methods in Prism::Node

- include/prism/options.h
- src/prism.c
> Remove flag gating for 3.3.0 bug fixes

- docs/serialization.md
- ext/prism/extension.c
- include/prism/options.h
`pm_serialize_parse` and similar functions/methods accept options as a Hash or char array and order of scopes (local variable) isn't specified explicitly.
> Document order of scopes in parsing options

- bin/parse
Previously, if you called `bin/parse` without `-e` or a file, you would get the following confusing error:
```
$ bin/parse
open: No such file or directory
bin/parse:20:in `<main>': undefined method `value' for nil:NilClass (NoMethodError)
value = result.value
^^^^^^
```
Now you get an `ArgumentError`:
```
$ bin/parse
open: No such file or directory
bin/parse:17:in `<main>': There was nothing to parse. You must pass source code with `-e` or a Ruby file. (ArgumentError)
```
> Raise error from bin/parse for missing source code and file

- docs/build_system.md
Previously it was hardcoded to a specific commit in the Ruby repo that still referred to "yarp".
Now it is pointing to the Ruby 3.3.0 release commit from 2023-12-25
> Update the link to the sync_default_gems script

- java/org/prism/Parser.java
- java/org/prism/ParsingOptions.java
It's needed to implement `Kernel#eval` correctly and make local variables in outer scopes visible.
> Add Java class `Parser.ParsingOptions` to serialise parsing options into byte array

- include/prism/defines.h
- src/prism.c
- templates/src/prettyprint.c.erb
A follow-up to https://github.com/ruby/prism/pull/2171
> Use inttypes for more accurate printf formatting

- config.yml
- docs/lexing.md
- prism.gemspec
This PR adds documentation comments in `config.yml` for:
- `InstanceVariableReadNode`
- `ClassVariableReadNode`
- `GlobalVariableReadNode`
- `BackReferencedReadNode`
- `NumberedReferenceReadNode`
- `LocalVariableReadNode`
- `ConstantReadNode`
> Document `*ReadNode` fields

- lib/prism/node_ext.rb
- test/prism/constant_path_node_test.rb
this prevents prism from raising `Constant path contains dynamic parts. Cannot compute full name` when a constant path starts with `::`.
> Handle stovetop start in constant path full_name

- src/prism.c
- test/prism/snapshots/seattlerb/defn_unary_not.txt
This PR removes the trailing `@` from the Method name in the prism AST for `DefNode`s that define unary methods.
CRuby's parser removes the `@` from the `mid` of `def !@; true; end` as seen here
```
```
I've opted to handle it inside Prism so that method names in the AST match what CRubys parser generates, rather than handling it in the compiler.
Fixes #2226
> Unescape method name for unary methods.

- Gemfile.lock
- config.yml
- src/prism.c
- test/prism/snapshots/patterns.txt
- test/prism/snapshots/seattlerb/case_in.txt
- test/prism/snapshots/seattlerb/case_in_hash_pat_assign.txt
- test/prism/snapshots/seattlerb/parse_pattern_058.txt
- test/prism/snapshots/seattlerb/parse_pattern_058_2.txt
- test/prism/snapshots/unparser/corpus/literal/pattern.txt
- test/prism/snapshots/whitequark/multiple_pattern_matches.txt
- test/prism/snapshots/whitequark/newline_in_hash_argument.txt
- test/prism/snapshots/whitequark/pattern_matching_single_line_allowed_omission_of_parentheses.txt
This simplifies compiling it, since you can now compile the value as if it were always there. It also means you don't have to reparse the symbol to get the constant name.
This also makes `AssocNode#value` non-null, since there will now always be an explicit value or implicit value.
> Add an implicit node for the target of a hash pattern

- src/prism.c
- test/prism/fixtures/case.txt
- test/prism/snapshots/case.txt
pattern matching snippets like:
```
case a
in b if c and d
e
end
```
fail with
```
Errors:
[#<Prism::ParseError @message="expected a delimiter after the predicates of a `when` clause" @location=#<Prism::Location @start_offset=18 @length=0 start_line=2>>, #<Prism::ParseError @message="cannot parse the expression" @location=#<Prism::Location @start_offset=18 @length=0 start_line=2>>]
```
because `PM_BINDING_POWER_DEFINED` goes after `PM_BINDING_POWER_COMPOSITION`, so `parse_value_expression()` only catches the `c` part and not the `and d`.
Switching to `PM_BINDING_POWER_COMPOSITION` fixed that.
I also wonder if we should change the error message to mention `in` instead of `when`? (since at the point of error I think we already know the type of node)
> Change binding power for modifiers in case-in nodes

- src/prism.c
- test/prism/fixtures/method_calls.txt
- test/prism/snapshots/method_calls.txt
Fixes code like:
```ruby
@a.b "c#{name}": 42
```
It looks like calls to `lex_state_p` with `or`ed parameters is not producing the expected results. I recall that that was also a problem with `lex_state_beg_p` before.
> Fix parsing calls with labels

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
Fixes parsing code like:
```ruby
(
a,
b
) = c
```
> Fix multiple assigns with newlines

- src/prism.c
- test/prism/snapshots/undef.txt
- test/prism/snapshots/unparser/corpus/semantic/undef.txt
- test/prism/snapshots/whitequark/undef.txt
Ensure we don't accidentally parse the symbol encoding twice, and ensure we parse it in every circumstance we need to by requiring it as a parameter.
> Symbol encoding follow-up

- lib/prism/parse_result.rb
* So it's clear it is a Symbol.
Before:
... @level=warning_verbose_true>
After:
... @level=:warning_verbose_true>
> Call #inspect on diagnostic levels

- java/org/prism/ParsingOptions.java
Add `ParsingOptions.SyntaxVersion` Java enum to use it instead of literals (e.g. `(byte) 1`) to serialise parsing options.
> Add SyntaxVersion Java enum

- .github/workflows/java-wasm-bindings.yml
- Makefile
- java-wasm/pom.xml
Thanks to the work done by @mariofusco on perfecting the Control Flow we are now able to run the optimized version of `prism.wasm` in Chicory.
> Optimize also java

- include/prism/encoding.h
- src/encoding.c
- src/prism.c
* This is also faster than calling pm_encoding_utf_8_alpha_char/pm_encoding_utf_8_alnum_char as those compute the character width and do extra checks.
> Always return the character width for char_is_identifier_start() and char_is_identifier_utf8()

- templates/include/prism/ast.h.erb
Unblocks https://github.com/ruby/ruby/pull/9806
```
../src/prism_compile.c: In function 'pm_compile_node':
../src/prism/ast.h:1045:53: error: 'struct pm_arguments_node' has no member named 'type'
1045 | #define PM_NODE_TYPE(node) ((enum pm_node_type) node->type)
|                                                     ^~
../src/prism/ast.h:1050:37: note: in expansion of macro 'PM_NODE_TYPE'
1050 | #define PM_NODE_TYPE_P(node, type) (PM_NODE_TYPE(node) == (type))
|                                     ^~~~~~~~~~~~
../src/prism_compile.c:4150:17: note: in expansion of macro 'PM_NODE_TYPE_P'
4150 |                 PM_NODE_TYPE_P((pm_node_t *)call_node->arguments, PM_ARGUMENTS_NODE) &&
|                 ^~~~~~~~~~~~~~
../src/compile.c: At top level:
```
> Add parentheses around macro arguments

- include/prism/parser.h
- src/prism.c
We don't list the type in any other fields, renaming for consistency.
> filepath_string -> filepath

- src/encoding.c
- test/prism/format_errors_test.rb
This assert used to trip in the included test:
```
./miniruby --parser=prism -e ' "%W"\u" '
```
> Amend assert in pm_utf_8_codepoint(), n=0 is fine

- src/prism.c
It's UB to use memcpy with overlapping source and destination. This
might be causing crashes on 32 bit platforms and on OpenBSD. Use memmove
instead. Add a bounds check while we're at it since it's unclear whether
one-past-end pointer with n=0 is UB.
> Fix overlapping memcpy

- lib/prism/translation/parser.rb
- lib/prism/translation/parser/compiler.rb
* Fix for `NumberedParametersNode`
* Ensure all errors are flowing through the diagnostics consumer like the parser gem
* Report the correct Ruby version
* Only try `builder.index` if there's no call operator
* Handle invalidly encoded heredocs
Fixes https://github.com/ruby/prism/issues/2345
> Small fixes for the parser translator

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
This fixes an issue found in https://github.com/ruby/prism/issues/2309#issuecomment-1921624040
~~I can't just add the fixture in test/prism/fixtures/patterns-eof.txt because it requires an EOF to show up. Is it OK to start adding new fixture files?~~
~~I've run the rake task with an added semicolon which makes parsing work, then manually edited the snapshot to remove the last character from the various locations.~~
For `test_individual_snippets_` tests, the fixtures are split on two consecutive newlines and the newline is removed to create the snippets, so we can add a snippet for the issue.
https://github.com/etiennebarrie/prism/blob/3f6d57fd98f9a28a38c30bb43ba98efe56766a72/test/prism/parse_test.rb#L225-L226
But `test_filepath_patterns.txt` parses the whole file at once, so I had to add …
> Fix Array pattern with command at end-of-file

- .travis.yml
- rakelib/check_manifest.rake
This PR is to add Travis arm64/ppc64le/s390x cases to this repository. Because this repository's commits are synchronized to ruby/ruby repository (automatically?). Then I recently saw 2 issues on Travis CI on ruby/ruby that are related to non-x86_64 CPU architectures. The 1st issue was s390x issue https://github.com/ruby/ruby/commit/34c688b163aa44ff319575c3b3d7d6a5c0dc5260, and the 2nd issue was that maybe the https://github.com/ruby/ruby/commit/770b5499a550956001b879abb5bbd205eabda19f - [the Travis CI log](https://app.travis-ci.com/github/ruby/ruby/builds/268685089) made Travis CI ppc64le/s390x/arm32 cases fail.
The [ruby/ruby Travis CI arm32](https://github.com/ruby/ruby/blob/master/.travis.yml) is emulated by specifying the arm32 compiler `arm-linux-gnueabihf-gcc`, and using `setarch …
> .travis.yml: Add Travis Ubuntu jammy arm64/ppc64le/s390x cases.

- bin/parse
- ext/prism/extension.c
- lib/prism/ffi.rb
- src/util/pm_string.c
- test/prism/parse_test.rb
Implement file parsing error handling
This PR implements proper file parsing error handling. Previously
`file_options` would call `pm_string_mapped_init` which would print an
error from `perror`. However this wouldn't raise a proper Ruby error so
it was just a string output. I've done the following:
- Raise an error from `rb_syserr_fail` with the filepath in
`file_options`.
- No longer return `Qnil` if `file_options` returns false (because now 
it will raise)
- Update `file_options` to return `static void` instead of `static
bool`.
- Update `file_options` and `profile_file` to check the type so when
passing `nil` we see a `TypeError`.
- Delete `perror` from `pm_string_mapped_init`
- Update `FFI` backend to raise appropriate errors when calling
`pm_string_mapped_init`.
- Add tests for …
> Implement file parsing error handling

- lib/prism/ripper_compat.rb
- test/prism/ripper_compat_test.rb
Part of issue #2354
More support for operators. Add basic support for ranges, parentheses and negative integers. Tests for each of these.
Full Ripper compatibility will require a lot more, but it seems good to start simple.
> More visitors and tests for RipperCompat

- lib/prism/ripper_compat.rb
- test/prism/ripper_compat_test.rb
There are a few cases we don't correctly support yet ("foo bar 1") and the argument handling is messy here. I'm working on it. But we're supporting a few fixture files correctly now.
This is part of fixing issue #2354.
> RipperCompat: support method calls with blocks

- bin/prism
- lib/prism/ripper_compat.rb
- test/prism/ripper_compat_test.rb
* add bin/prism ripper to compare Ripper output
* block arg handling is quirky, do it per-call-site
* required params for blocks
* boolean values
* various assign-operator support
* breaks
* early fragile begin/rescue/end
* more fixtures being checked
Part of #2354.
> RipperCompat: support for more features.

- lib/prism/translation/parser.rb
Before:
```
ruby 3.4.0dev (2024-02-07T11:34:48Z master 9ebaf7a8ef) [arm64-darwin23]
Warming up --------------------------------------
Parser::CurrentRuby     1.000 i/100ms
Prism::Translation::Parser
1.000 i/100ms
Calculating -------------------------------------
Parser::CurrentRuby      1.203 (± 0.0%) i/s -      7.000 in   5.821395s
Prism::Translation::Parser
0.245 (± 0.0%) i/s -      2.000 in   8.219212s
Comparison:
Parser::CurrentRuby:        1.2 i/s
Prism::Translation::Parser:        0.2 i/s - 4.91x  slower
```
after:
```
ruby 3.4.0dev (2024-02-07T11:34:48Z master 9ebaf7a8ef) [arm64-darwin23]
Warming up --------------------------------------
Parser::CurrentRuby     1.000 i/100ms
Prism::Translation::Parser
1.000 i/100ms
Calculating ------------------------------------- …
```
> Significantly faster offset cache for parser translation with multibyte characters

- lib/prism/ripper_compat.rb
- test/prism/ripper_compat_test.rb
More Ripper support:
* assignment for variables
* array-refs
* assignment for array-refs
* simple and slightly-dynamic symbols
* plain and embedded strings
> RipperCompat: add array-refs, assigns, symbols, strings

- .travis.yml
This PR is to use the same version of GCC with the ruby/ruby's one in Travis CI.
The used gcc-11 version is 11.4.0, the same as the one used in ruby/ruby.
https://app.travis-ci.com/github/junaruga/ruby-prism/jobs/617607554#L172
> gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
---
However in the `rake compile`, the `cc` is used in the actual command line. That is not expected. I don't know why.
https://app.travis-ci.com/github/junaruga/ruby-prism/jobs/617607554#L219
Edit: solved the issue.
> Use gcc-11 to align with the ruby/ruby Travis CI.

- README.md
It seems that due to https://github.com/ruby/prism/pull/2364, Ruby 2.7.0 is now accepted as a runtime.
```ruby
$ gem i prism
$ ruby -rprism -ve "p Prism.parse_success?('42')"
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
true
```
The requirements could be updated from Ruby 3.0.0 to Ruby 2.7.0.
> [Doc] Update the required runtime Ruby version in README

- lib/prism/node_ext.rb
- test/prism/constant_path_node_test.rb
We noticed that `full_name` was not working for constant targets. We probably forgot to add handling for them in the original PR.
> Fix `full_name` for constant path targets

- src/options.c
- test/prism/location_test.rb
This PR fixes following error when using `version: latest` argument.
```console
$ ruby -rprism -e "p Prism.parse('-> { it }', version: 'latest')"
-e:1:in `parse': invalid version: latest (ArgumentError)
p Prism.parse('-> { it }', version: 'latest')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
from -e:1:in `<main>'
```
The argument `version: latest` in the added test is commented as potentially being better replaced with `version: 3.4.0` in the future.
> Fix an error when specifying the parsing version `latest`

- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- src/options.c
- test/prism/location_test.rb
This is effectively an alias for "latest" right now. In the future it will change to be its own enum value.
> Introduce `version: "3.4.0"`

- lib/prism/parse_result.rb
- test/prism/ruby_api_test.rb
LSPs need this because the protocol dictates that you return code units for offsets. None of our existing APIs provided that information, and since we hid the source it's not nearly as useful for them. Now they can pass an encoding directly to:
* Location#start_code_units_offset
* Location#end_code_units_offset
* Location#start_code_units_column
* Location#end_code_units_column
> Add code unit APIs to location

- docs/serialization.md
- ext/prism/extension.c
- ext/prism/extension.h
- java-wasm/src/test/java/org/prism/DummyTest.java
- java/org/prism/ParseResult.java
- lib/prism/parse_result.rb
- rakelib/serialization.rake
- templates/ext/prism/api_node.c.erb
- templates/java/org/prism/Loader.java.erb
- templates/java/org/prism/Nodes.java.erb
- templates/javascript/src/deserialize.js.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
- test/prism/parse_test.rb
* Fixes https://github.com/ruby/prism/issues/2380
Related: https://github.com/ruby/prism/issues/2402
> Serialize the newline_list to avoid recomputing it again later

- templates/lib/prism/serialize.rb.erb
On top of https://github.com/ruby/prism/pull/2381.
Part of #2402, hard to measure given the noise on the full benchmark but in a micro benchmark it's very clear:
* It is quite a bit faster:
ruby -rbenchmark/ips -e 'Benchmark.ips { |x| x.report("times.map") { 1000.times.map {} }; x.report("Array.new") { Array.new(1000) {} }; x.compare! }'
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
Warming up --------------------------------------
times.map   976.000 i/100ms
Array.new     1.641k i/100ms
Calculating -------------------------------------
times.map      9.808k (± 0.3%) i/s -     49.776k in   5.075013s
Array.new     16.601k (± 1.0%) i/s -     83.691k in   5.041970s
Comparison:
Array.new:    16600.8 i/s
times.map:     9808.2 i/s - 1.69x  slower
> Prefer `Array.new(n) {}` to `n.times.map {}`

- src/prism.c
Build was failing when `PM_DEBUG_LOGGING` is `1`, this PR fixes it.
> Fix debug logging

- lib/prism/translation/parser.rb
- lib/prism/translation/parser/rubocop.rb
- lib/prism/translation/parser33.rb
- lib/prism/translation/parser34.rb
- prism.gemspec
Fixes #2356
I'm working on integrating Prism into RuboCop.
This PR introduces `Prism::Translation::Parser33` and `Prism::Translation::Parser34`, named in accordance with the following comments.
https://github.com/rubocop/rubocop/issues/12600#issuecomment-1932707748
Currently, `Prism::Translation::Parser` always operates in Ruby 3.4 mode. This means it will not parse as Ruby 3.3 even if `TargetRubyVersion: 80_82_73_83_77.33` is specified.
Therefore, the `it` introduced in Ruby 3.4 is parsed incompatibly with Ruby 3.3. In Ruby 3.3, the expected name for an `lvar` is `:it`, not `:"0it"`.
The following is an expected AST when parsing Ruby 3.3 code:
```console
$ bundle exec ruby -rprism -rprism/translation/parser33 -ve "p Prism::Translation::Parser33.parse('items.map { it.do_something }')" …
```
> Support multi-versioning for `Prism::Translation::Parser`

- lib/prism/ffi.rb
* For Prism.parse_file the file contents would be read as native, then converted to a Ruby String, then converted to a native String for pm_serialize_parse().
* Refactor the logic to always use a pm_string for the source code and pass that to other native functions.
* Part of #2402
> Avoid extra String copies in the FFI backend

- bin/prism
- lib/prism/translation/ripper.rb
- test/prism/ripper_test.rb
Handle more aliases, including fully handling aliases.txt.
As part of handling more aliases, handle symbols that are keywords, constants or operations. Handle interpolated symbols. Handle global variable references.
<s>Better testing of prism ripper CLI and a test for it. I had broken it in renaming Translation::Ripper. Now it's tested.</s> It also prints better output when Prism or Ripper Translation gets an exception during parsing.
> Aliases for Ripper Translation

- src/prism.c
- test/prism/location_test.rb
Consider two examples: `{'a':1}` and `{'':1}` and let's run `parse` for them:
```
irb(test_parse(Prism::ParserTest)):001:0> p = Prism::Translation::Parser.parse("{'a':1}")
=>
s(:hash,
s(:pair,
s(:sym, :a),
s(:int, 1)))
irb(test_parse(Prism::ParserTest)):002:0> p.children.first.children.first.loc.expression.source
=> "'a'"
irb(test_parse(Prism::ParserTest)):001:0> p = Prism::Translation::Parser.parse("{'':1}")
=>
s(:hash,
s(:pair,
s(:sym, :""),
s(:int, 1)))
irb(test_parse(Prism::ParserTest)):002:0> p.children.first.children.first.loc.expression.source
=> "'"
```
I would expect the last result to be an empty string`"''"` instead of the single quote.
I'm not sure why in case of an empty symbol node the location was reset, but all the tests seems to be green ❇️ 
I also compared it to the …
> Fix opening loc for an empty symbol

- lib/prism/desugar_compiler.rb
- lib/prism/parse_result.rb
- lib/prism/translation/parser/compiler.rb
- templates/ext/prism/api_node.c.erb
- templates/lib/prism/dsl.rb.erb
- templates/lib/prism/node.rb.erb
- templates/lib/prism/serialize.rb.erb
- test/prism/newline_test.rb
When creating the Ruby AST, we were previously allocating Location objects for every node and every inner location. Instead, this commit changes it to pack both the start offset and length into a single u64 and pass that into the nodes. Then, when the locations are requested via a reader method, we lazily allocate the Location objects.
This pretty drastically improves speed and memory. With this script:
```ruby
require "bundler/setup"
require "prism"
filepaths = Dir[File.expand_path("path/to/extremely/large/ruby/codebase/**/*.rb", __dir__)]
filepaths.each { |filepath| Prism.parse_file(filepath) }
puts `ps -o rss= -p #{$$}`
```
We get the following results. On `main`:
```
145152
ruby bin/bench  26.96s user 2.53s system 94% cpu 31.059 total
146016
ruby bin/bench  27.00s user 2.58s system …
```
> Speed up creating Ruby AST

- include/prism/diagnostic.h
- src/diagnostic.c
- src/prism.c
- test/prism/errors_test.rb
Add warning for code like:
```ruby
if (a = 2); end
if ($a = 2); end
if (@a = 2); end
if (@@a = 2); end
if a elsif b = 2; end
unless (a = 2); end
unless ($a = 2); end
unless (@a = 2); end
unless (@@a = 2); end
while (a = 2); end
while ($a = 2); end
while (@a = 2); end
while (@@a = 2); end
until (a = 2); end
until ($a = 2); end
until (@a = 2); end
until (@@a = 2); end
foo if a = 2
foo if (a, b = 2)
(@foo = 1) ? a : b
!(a = 2)
not a = 2
```
> Warn for `=` in conditional predicates

- Rakefile
This check turns out to be annoying in practice, I think it's fine it just prints/warns without exiting.
Not being able to run the test suite just because there are extra files seems rather extreme.
FWIW my extra files are flamegraphs and profile data from optimizing Prism (#2402).
> Do not abort `bundle exec rake` if there are extra files

- include/prism/parser.h
- src/prism.c
Fixes https://github.com/ruby/prism/issues/2275
> Disallow numbered parameters within given scopes

- src/prism.c
And destructured required parameters.
Fixes https://github.com/ruby/prism/issues/2445
> Accept newlines before ) in patterns

- lib/prism/parse_result.rb
- lib/prism/parse_result/comments.rb
- test/prism/magic_comment_test.rb
Also make them lazy to allocate the array, and also expose ParseResult#encoding.
> Split up comments between leading and trailing

- docs/build_system.md
- include/prism/defines.h
- include/prism/util/pm_string.h
- src/util/pm_string.c
- templates/src/serialize.c.erb
This is to know if the memory map interface is available in the target platform by using `_POSIX_MAPPED_FILES` and `_WIN32`
ref #2217
> Introduce `PRISM_HAS_MMAP` macro

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2145
> Fix eval encoding switching to UTF-8

- lib/prism/translation/parser.rb
- test/prism/parser_test.rb
We weren't registering warnings, just errors.
As a side effect, this will cause "bin/prism parser" to die when it sees a warning because we're running the Parser gem in that mode. I think that's probably fine, but it seems worth mentioning.
Should fix #2454
> Translation::Parser should process warnings, not just errors

- lib/prism/node_ext.rb
In reference to https://github.com/ruby/prism/discussions/2434#discussioncomment-8549837
There's no specific test for node extensions, it seems? Not sure where I'd add a test for this.
> all constant nodes should have full_name and full_name_parts methods

- templates/java/org/prism/Loader.java.erb
* It was non-optimal for -2**31 and -2**63, where it returned respectiely long and BigInteger instead of int and long.
* There was a missing negation for the wordsLength > 2 case.
Found while adopting it in TruffleRuby which asserts the optimal representation is always used.
> Fix loadInteger() to always return the most optimal representation

- lib/prism/translation/parser/compiler.rb
Fixes https://github.com/ruby/prism/issues/2501
> Handle negated numeric in parser translation

- docs/serialization.md
- ext/prism/extension.c
- include/prism/node.h
- include/prism/options.h
- include/prism/parser.h
- java-wasm/src/test/java/org/prism/DummyTest.java
- java/org/prism/ParsingOptions.java
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- src/options.c
- src/prism.c
- templates/src/node.c.erb
- test/prism/command_line_test.rb
The current CRuby parser supports these options by mutating the AST. I don't want to do that, and instead would prefer to do it in the compiler. But that work is for another day, and this will be far easier than wading into those waters. So instead, we now support the following options:
* `command_line_p`
* `command_line_n`
* `command_line_a`
* `command_line_l`
These correspond with the respective command line flags. They mutate the AST such that you get back what would be executed (this pretty much exactly matches what the current parser does).
cc @enebo, @eregon, @seven1m — you may want to use these or you may not. I'm assuming all of you currently have your own solutions for this. It's not that much code at the end of the day so entirely up to you.
Fixes …
> Support -p, -n, -a, and -l command line options

- lib/prism/translation/parser/rubocop.rb
With the introduction of `Prism::Translation::Parser` to RuboCop (RuboCop AST), the number of arguments for `RuboCop::AST::ProcessedSource#parser_class` internal API will be changed:
https://github.com/rubocop/rubocop-ast/pull/277
As a result, the following error will occur starting from the next release of RuboCop AST (< 1.30.0) :
```console
$ bundle exec ruby -rrubocop/ast -rprism -rprism/translation/parser/rubocop -ve "p RuboCop::AST::ProcessedSource.new('42', 80_82_73_83_77.33).ast"
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser/rubocop.rb:25:in `parser_class':
wrong number of arguments (given 2, expected 1) (ArgumentError)
from /Users/koic/src/github.com/rubocop/rubocop-ast/lib/rubocop/ast/processed_sour …
```
> Follow RuboCop's parser engine support

- rust/ruby-prism/build.rs
- rust/ruby-prism/src/lib.rs
This PR is sort of the opposite of #1625: here, the code currently returns structures that are bound to the lifetime of `&self`.  But that's not correct; the structures are actually bound to `'pr`, the lifetime of the parse result.  There's no reason that they should be bound to the lifetime of `&self`; doing so makes some kinds of programs difficult to write.
e.g. The added test gets errors like:
```
error[E0597]: `path` does not live long enough
--> ruby-prism/src/lib.rs:804:38
|
802 |         impl<'pr> Extract<'pr> {
|              --- lifetime `'pr` defined here
803 |             fn push_scope(&mut self, path: Node<'pr>) {
|                                      ---- binding `path` declared here
804 |                 if let Some(cread) = path.as_constant_read_node() {
| …
```
> [rust] give node downcasts the proper lifetimes

- include/prism/static_literals.h
- src/static_literals.c
Switch from binary search to hash lookup.
Before:
```
irb(main):001> measure
TIME is added.
=> nil
irb(main):002> code = 1000000.times.to_h{[_1,1]}.inspect;
processing time: 0.323862s
irb(main):003> Prism.parse_success? code
processing time: 0.312201s
=> true
irb(main):004> code = 1000000.times.reverse_each.to_h{[_1,1]}.inspect;
processing time: 0.329255s
irb(main):005> Prism.parse_success? code
processing time: 85.215507s
=> true
irb(main):006>
```
After:
```
irb(main):001> measure
TIME is added.
=> nil
irb(main):002> code = 1000000.times.to_h{[_1,1]}.inspect;
processing time: 0.327138s
irb(main):003> Prism.parse_success? code
processing time: 0.329897s
=> true
irb(main):004> code = 1000000.times.reverse_each.to_h{[_1,1]}.inspect;
processing time: 0.339055s
irb(main):005> …
```
> Static literal hash

- .editorconfig
- .github/workflows/main.yml
- config.yml
- templates/java/org/prism/Loader.java.erb
- templates/java/org/prism/Nodes.java.erb
- templates/lib/prism/node.rb.erb
- templates/template.rb
* Fixes https://github.com/ruby/prism/issues/2058
> Give a kind to all node[] fields and better types in Java-generated code

- lib/prism/translation/parser/compiler.rb
- test/prism/parser_test.rb
This PR fixes an incorrect parsing for `Prism::Translation::Parser` when one-line pattern mathing with Ruby 2.7 runtime.
Parsing should be done based on the specified Ruby parsing version, independent of the Ruby runtime version. When parsing for Ruby 3.3, it should return `:match_pattern_p` node:
```console
$ ruby -rprism -rprism/translation/parser33 -ve 'p Prism::Translation::Parser33.parse("foo in bar")'
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-darwin19]
s(:match_pattern_p,
s(:send, nil, :foo),
s(:match_var, :bar))
```
When parsing with Ruby 2.7 runtime, `match_pattern` node is returned, even though it is expected to parse for Ruby 3.3:
```console
$ ruby -rprism -rprism/translation/parser33 -ve 'p Prism::Translation::Parser33.parse("foo in bar")'
ruby 2.7.8p225 …
```
> Fix an incorrect parsing for `Prism::Translation::Parser`

- lib/prism.rb
- templates/lib/prism/serialize.rb.erb
* Following the changes in #2428.
* `PRISM_FFI_BACKEND=true ruby -v -Ilib -rprism -rbenchmark -e '10.times { p Benchmark.realtime { Dir.glob("lib/**/*.rb") { |f| Prism.parse_file(f) } } }'`
ruby 3.3.0:      0.255 => 0.210
ruby 3.3.0 YJIT: 0.150 => 0.120
From https://github.com/ruby/prism/issues/2402#issuecomment-1951376375
> Lazily create Location objects in Prism::Serialize::Loader#load_location

- templates/javascript/src/deserialize.js.erb
This seems to have snuck in recently.
> Fix typo in JavaScript deserialization template

- BSDmakefile
- README.md
- prism.gemspec
Fixes https://github.com/ruby/prism/issues/2527
Includes the https://github.com/neosmart/gmake-proxy BSDmakefile to proxy all commands through gmake. Change the README to reflect that we require GNU make.
> Include BSDmakefile

- lib/prism/translation/parser/compiler.rb
This PR fixes the following incompatibility AST for regexp match between Parser gem and Prism:
Returns an `match_with_lvasgn` node:
```console
$ bundle exec ruby -rparser/ruby33 -ve 'p Parser::Ruby33.parse("/foo/ =~ bar")'
s(:match_with_lvasgn,
s(:regexp,
s(:str, "foo"),
s(:regopt)),
s(:send, nil, :bar))
```
Returns an `send` node:
```console
$ bundle exec ruby -rprism -rprism/translation/parser33 -ve 'p Prism::Translation::Parser33.parse("/foo/ =~ bar")'
s(:send,
s(:regexp,
s(:str, "foo"),
s(:regopt)), :=~,
s(:send, nil, :bar))
```
Returns an `match_with_lvasgn` node:
```console
$ bundle exec ruby -rprism -rprism/translation/parser33 -ve 'p …
```
> Fix incompatibility AST for regexp match in `Prism::Translation::Parser`

- templates/lib/prism/serialize.rb.erb
* The stdlib StringIO is synchronized and this occurs a high overhead.
* This is about twice as fast on TruffleRuby but surprisingly it is slower on JRuby. I am not sure why but probably `@ivar` access and Ruby integer arithmetic is much slower than Java field access/arithmetic on JRuby.
* On CRuby interpreter it is slower, which is expected as the GVL already protects StringIO.
* So we enable this only on TruffleRuby to not slow down other Rubies.
```
* PRISM_FFI_BACKEND=true ruby -v -Ilib -rprism -rbenchmark -e '300.times { p Benchmark.realtime { Dir.glob("lib/**/*.rb") { |f| Prism.parse_file(f) } } }'
ruby 3.3.0:         0.215 => 0.251 (cext: 0.062)
ruby 3.3.0 YJIT:    0.118 => 0.113 (cext: 0.053)
truffleruby JVM:    0.101 => 0.054
jruby 9.4.6.0:      0.162 => 0.219
jruby 9.4.6.0 indy: …
```
> Use a more efficient StringIO on TruffleRuby

- templates/template.rb
The required ruby version is 2.7.0 or later.
> Drop support for old ERB

- docs/ruby_api.md
- ext/prism/extension.c
- include/prism.h
- lib/prism/ffi.rb
- rakelib/test.rake
- rbi/prism.rbi
- src/prism.c
- templates/sig/prism.rbs.erb
- test/prism/parse_stream_test.rb
Closes https://github.com/ruby/prism/issues/1247 (our second-oldest open issue!)
Prism can now parse streams. In the C API you can use it like this:
```c
#include "prism.h"
int main(void) {
pm_parser_t parser;
pm_options_t options = { .line = 1, 0 };
pm_node_t *node = pm_parse_stream(&parser, stdin, (pm_parse_stream_fgets_t *) fgets, &options);
pm_buffer_t buffer;
pm_prettyprint(&buffer, &parser, node);
printf("%.*s\n", (int) pm_buffer_length(&buffer), pm_buffer_value(&buffer));
pm_node_destroy(&parser, node);
pm_parser_free(&parser);
pm_buffer_free(&buffer);
}
```
Relevant signatures are:
```c
typedef char * (pm_parse_stream_fgets_t)(char *restrict string, int size, void *restrict stream);
PRISM_EXPORTED_FUNCTION pm_node_t *
pm_parse_stream(pm_parser_t *parser, void *stream, …
```
> Support parsing streams

- ext/prism/extension.c
- ext/prism/extension.h
- include/prism/util/pm_integer.h
- rust/ruby-prism/build.rs
- src/prism.c
- src/static_literals.c
- src/util/pm_integer.c
- src/util/pm_string.c
- templates/ext/prism/api_node.c.erb
- templates/src/serialize.c.erb
- test/prism/integer_parse_test.rb
Parsing huge integer literal is a bit slow.
`Prism.parse('1'*1000000)` takes about 67.8s, `eval('1'*1000000)` takes only 0.32s. This pull request improves it to 1.46s.
Constructing a bigint with `digits.each{v=v*10+_1}` is `O(n^2)`.
To make it faster, I think we need a fast bigint multiplication algorithm.
(I'm not sure this is worth introducing complexity)
Implement karatsuba algorithm that ruby's Bignum uses internally.
Implement radix conversion using fast multiplication.
If base is power of two, just pack bits to bigint.
If base is 10, peform radix conversion.
`"0x...".to_i`  is  faster than `|` `<<` for large integer.
Use radix conversion
| Prism.parse(code) | before | after | ratio |
| --- | --- | --- | --- |
| '1'*1000000 | 67.798872s | 1.462340s | x46.3 |
| '1'*100000 | 0.723387s …
> Parse huge integer faster

- lib/prism/translation/parser/lexer.rb
This PR fixes the following error for `Prism::Translation::Parser::Lexer` on the main branch:
```console
$ cat example.rb
'a' # aあ
"
#{x}
"
$ bundle exec rubocop
Parser::Source::Range: end_pos must not be less than begin_pos
/Users/koic/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parser-3.3.0.5/lib/parser/source/range.rb:39:in `initialize'
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser/lexer.rb:299:in `new'
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser/lexer.rb:299:in `block in to_a'
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser/lexer.rb:297:in `map'
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser/lexer.rb:297:in `to_a'
/Users/koic/src/github.com/ruby/prism/lib/prism/translation/parser.rb:263:in …
```
> Fix an error for `Prism::Translation::Parser::Lexer`

- lib/prism/translation/parser/lexer.rb
- test/prism/fixtures/heredoc.txt
- test/prism/fixtures/heredoc_with_carriage_returns.txt
- test/prism/snapshots/heredoc.txt
- test/prism/snapshots/heredoc_with_carriage_returns.txt
Fixes #2512.
This PR fixes a token incompatibility between Parser gem and `Prism::Translation::Parser` for `HEREDOC_END` with a newline.
> Fix a token incompatibility for `Prism::Translation::Parser`

- README.md
RuboCop 1.62 supports Prism directly, so I think it's best to just point to the relevant section of RuboCop's docs. (https://docs.rubocop.org/rubocop/configuration.html#setting-the-parser-engine)
> Update the RuboCop link

- config.yml
- src/prism.c
This PR adds documentation comments to `config.yml` for the fields of `ClassVariableWriteNode`.
While doing this, I noticed that `operator_loc` had type `location?`, but I was unable to find any situation where the `=` operator wouldn't be present. The tests & the `parse:topgems` task still pass when using `PM_LOCATION_TOKEN_VALUE` instead of `PM_OPTIONAL_LOCATION_TOKEN_VALUE`, so I added that change in a separate commit, on the assumption that the optionality was in error. If that's not correct let me know & I'll drop that commit & amend the documentation with an example that lacks the `=` location.
> Document `ClassVariableWriteNode` fields

- config.yml
This PR adds documentation comments in `config.yml` to the fields of `InstanceVariableWriteNode`.
> Document `InstanceVariableWriteNode` fields

- lib/prism/translation/parser/lexer.rb
- test/prism/parser_test.rb
This PR fixes a token incompatibility between Parser gem and `Prism::Translation::Parser` for beginless range:
Returns `tBDOT2` token:
```console
$ bundle exec ruby -Ilib -rparser/ruby33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); buf.source = "..42"; p Parser::Ruby33.new.tokenize(buf)[2]'
[[:tBDOT2, ["..", #<Parser::Source::Range example.rb 0...2>]], [:tINTEGER, [42, #<Parser::Source::Range example.rb 2...4>]]]
```
Previously, the parser returned `tDOT2` token when parsing the following:
```console
$ bundle exec ruby -Ilib -rprism -rprism/translation/parser33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); buf.source = "..42"; p Prism::Translation::Parser33.new.tokenize(buf)[2]'
ruby 3.3.0 (2023-12-25 …
```
> Fix a token incompatibility for `Prism::Translation::Parser::Lexer`

- test/prism/parser_test.rb
This PR restores some heredoc tests that have already passed for `Prism::Translation::Parser`.
> Restore some skipped heredoc tests for `Prism::Translation::Parser`

- test/prism/parser_test.rb
Due to #2579, the test case for range_begin_open_inclusive.txt has also been restored.
> Follow #2579

- test/prism/parser_test.rb
Due to ruby/prism#2581, the test case for non_alphanumeric_methods.txt has also been restored. It also solved issues with `def self.`' not limited to constants for `tBACK_REF2` token.
```console
$ bundle exec ruby -Ilib -rprism -rprism/translation/parser33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); buf.source = "def self.`; end"; p Prism::Translation::Parser33.new.tokenize(buf)[2]'
[[:kDEF, ["def", #<Parser::Source::Range example.rb 0...3>]], [:kSELF, ["self", #<Parser::Source::Range example.rb 4...8>]],
[:tDOT, [".", #<Parser::Source::Range example.rb 8...9>]], [:tBACK_REF2, ["`", #<Parser::Source::Range example.rb 9...10>]],
[:tSEMI, [";", #<Parser::Source::Range example.rb 10...11>]], [:kEND, ["end", …
```
> Follow ruby/prism#2581

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2588
> Allow newline before block locals

- lib/prism/translation/parser/compiler.rb
- test/prism/fixtures/xstring.txt
- test/prism/snapshots/xstring.txt
Fixes ruby/prism#2480.
This PR fixes an AST incompatibility between Parser gem and `Prism::Translation::Parser` for xstring literal with line breaks.
The following case in ruby/prism#2480 has already been addressed in ruby/prism#2576:
```ruby
"foo
bar"
```
> Fix an AST incompatibility for `Prism::Translation::Parser`

- config.yml
- ext/prism/extension.c
- include/prism/options.h
- include/prism/parser.h
- rust/ruby-prism/src/lib.rs
- src/options.c
- src/prism.c
An explicit `false` is not equivalent to the comment being missing, because the default can be switched with a runtime flag:
```bash
$ ruby --enable-frozen-string-literal -e 'p "foo".frozen?'
true
```
NB: I chose to make it a second boolean flag as I'm not sure what the API compatibility guarantees are, but maybe a three state enum might be better?
@kddnewton
> Change `frozen_string_literal` to be a tri-state

- test/prism/parser_test.rb
This PR enables the heredocs_nested.txt that was previously skipped testing.
> Turn on heredocs nested test for `Prism::Translation::Parser`

- config.yml
- include/prism/defines.h
- src/prism.c
- templates/src/diagnostic.c.erb
This one will impact implementations. Now `NumberedReferenceReadNode` has `0` as the number if the value is too large. This matches CRuby's expectations. We also use this for adding an appropriate warning.
cc @enebo @eregon @seven1m
> Warn for maximum number variables

- config.yml
- include/prism/parser.h
- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/ripper.rb
- lib/prism/translation/ruby_parser.rb
- src/prism.c
- templates/src/diagnostic.c.erb
- test/prism/location_test.rb
Needed to support the `# shareable_constant_value` magic comments that control ractors. Other implementations should probably just skip right past these nodes.
> Shareable constant nodes

- config.yml
- src/prism.c
- test/prism/snapshots/keyword_method_names.txt
- test/prism/snapshots/keywords.txt
- test/prism/snapshots/patterns.txt
- test/prism/snapshots/unparser/corpus/literal/pragma.txt
- test/prism/snapshots/whitequark/pattern_matching__FILE__LINE_literals.txt
- test/prism/snapshots/whitequark/string___FILE__.txt
- test/prism/static_inspect_test.rb
- test/prism/static_literals_test.rb
For all intent and purposes, `__FILE__` is a string literal subject to the `# frozen_string_literal: true/false` comment and to the global `--enable-frozen-string-literal / --disable-frozen-string-literal` CLI flags.
> Add PM_STRING_FLAGS_FROZEN / PM_STRING_FLAGS_MUTABLE on PM_SOURCE_FILE_NODE

- lib/prism/translation/parser/lexer.rb
This PR fixes token incompatibility for `Prism::Translation::Parser::Lexer` when using escaped backslash in string literal:
```ruby
"\\ foo \\ bar"
```
```console
$ bundle exec ruby -Ilib -rparser/ruby33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); buf.source = File.read("example.rb"); p Parser::Ruby33.new.tokenize(buf)'
[s(:str, "\\ foo \\ bar"), [], [[:tSTRING, ["\\ foo \\ bar", #<Parser::Source::Range example.rb 0...15>]],
[:tNL, [nil, #<Parser::Source::Range example.rb 15...16>]]]]
```
Previously, the tokens returned by the Parser gem were different. The escaped backslash does not match in the `tSTRING` token:
```console
$ bundle exec ruby -Ilib -rprism -rprism/translation/parser33 -ve \
'buf = …
```
> Fix token incompatibility for `Prism::Translation::Parser::Lexer`

- lib/prism/translation/parser/rubocop.rb
- lib/prism/translation/ripper/sexp.rb
- templates/lib/prism/serialize.rb.erb
If there are many searches in the `$LOAD_PATH` in the user environment, require will perform unnecessary searches that are not needed. In contrast, `require_relative` is efficient because it uses a relative path.
> Use `require_relative` in the Prism codebase

- include/prism/defines.h
For better compatibility, this patch suggests using __MINGW_PRINTF_FORMAT that GCC provides for MinGW environment.
> [Compatibility] Improve printf format

- lib/prism/translation/parser.rb
This PR fixes a diagnostic incompatibility for `Prism::Translation::Parser` when using constant argument:
```ruby
def foo(A)
end
```
Displays `formal argument cannot be a constant (Parser::SyntaxError)`:
```console
$ bundle exec ruby -Ilib -rparser/ruby33 -ve 'p Parser::Ruby33.parse("def foo(A) end")'
(string):1:9: error: formal argument cannot be a constant
(string):1: def foo(A) end
(string):1:         ^
/Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-3.3.0.5/lib/parser/diagnostic/engine.rb:72:
in `process': formal argument cannot be a constant (Parser::SyntaxError)
from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-3.3.0.5/lib/parser/base.rb:274:in `diagnostic'
from …
```
> Fix a diagnostic incompatibility for `Prism::Translation::Parser`

- .github/workflows/main.yml
- Makefile
- Rakefile
- docs/build_system.md
- ext/prism/extconf.rb
- ext/prism/extension.c
- gemfiles/truffleruby/Gemfile
- gemfiles/truffleruby/Gemfile.lock
- include/prism.h
- include/prism/encoding.h
- include/prism/pack.h
- include/prism/prettyprint.h
- rakelib/test.rake
- src/encoding.c
- src/pack.c
- src/prism.c
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
- templates/src/serialize.c.erb
- test/prism/encoding_test.rb
- test/prism/fuzzer_test.rb
- test/prism/magic_comment_test.rb
- test/prism/parse_test.rb
- test/prism/ruby_api_test.rb
- test/prism/static_inspect_test.rb
This PR introduces a couple of defines that control what gets compiled into the final binary. These are:
* `PRISM_ENCODING_EXCLUDE_FULL` - Will cause the library to exclude the full encoding API, and only include the minimal number of encodings to support parsing Ruby code without encoding comments. By default this is off.
* `PRISM_EXCLUDE_JSON` - Will cause the library to exclude the JSON API. By default this is off.
* `PRISM_EXCLUDE_PACK` - Will cause the library to exclude the pack API. By default this is off.
* `PRISM_EXCLUDE_PRETTYPRINT` - Will cause the library to exclude the prettyprint API. By default this is off.
* `PRISM_EXCLUDE_SERIALIZATION` - Will cause the library to exclude the serialization API. By default this is off.
Including all of these options results in a pretty …
> Provide options for reducing size

- src/prism.c
- test/prism/errors_test.rb
This PR fixes the following incorrect range of `Prism::Location` when `PM_ERR_RETURN_INVALID`.
It may be hard to tell from the text, but this Ruby error highlights `return`:
```console
$ ruby -e 'class Foo return end'
-e:1: Invalid return in class/module body
class Foo return end
-e: compile error (SyntaxError)
```
Previously, the error's `Prism::Location` pointed to `end`:
```console
$ bundle exec ruby -Ilib -rprism -ve 'p Prism.parse("class Foo return end").errors'
[#<Prism::ParseError @type=:return_invalid @message="invalid `return` in a class or module body"
@location=#<Prism::Location @start_offset=17 @length=3 start_line=1> @level=:fatal>]
After this fix, it will indicate `return`.
```console
$ bundle exec ruby -Ilib …
> Fix an incorrect range of `Prism::Location` when `PM_ERR_RETURN_INVALID`

- src/prism.c
This PR fixes the following build error for C99 and C23 Ruby's CI matrix:
```console
../src/prism/prism.c:1241:19: error: initializing 'char *' with an expression of
type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
1241 |             char *word = unknown_flags_length >= 2 ? "options" : "option";
|                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
assembling ../src/coroutine/amd64/Context.S
```
- c99 ... https://github.com/ruby/ruby/actions/runs/8419905079/job/23053543994#step:10:249
- c23 ... https://github.com/ruby/ruby/actions/runs/8419905079/job/23053544274#step:10:257
This is my mistake. It is an incorrect code introduced in https://github.com/ruby/prism/pull/2618.
> Fix build error for C99 and C23 CI matrix

- src/prism.c
- test/prism/snapshots/dos_endings.txt
- test/prism/snapshots/dstring.txt
- test/prism/snapshots/regex.txt
- test/prism/snapshots/seattlerb/parse_line_evstr_after_break.txt
- test/prism/snapshots/seattlerb/qsymbols_interp.txt
- test/prism/snapshots/seattlerb/str_lit_concat_bad_encodings.txt
- test/prism/snapshots/seattlerb/words_interp.txt
- test/prism/snapshots/spanning_heredoc.txt
- test/prism/snapshots/strings.txt
- test/prism/snapshots/symbols.txt
- test/prism/snapshots/unparser/corpus/literal/literal.txt
- test/prism/snapshots/unparser/corpus/semantic/dstr.txt
- test/prism/snapshots/unparser/corpus/semantic/literal.txt
- test/prism/snapshots/whitequark/array_symbols_interp.txt
- test/prism/snapshots/whitequark/array_words_interp.txt
- test/prism/snapshots/whitequark/non_lvar_injecting_match.txt
- test/prism/snapshots/whitequark/regex_interp.txt
- test/prism/snapshots/whitequark/ruby_bug_11990.txt
- test/prism/snapshots/whitequark/string_concat.txt
- test/prism/snapshots/whitequark/xstring_interp.txt
- test/prism/snapshots/xstring.txt
Fixes https://github.com/ruby/prism/issues/2532
* Mark inner string parts of interpolated* nodes as frozen
* Mark interpolated* nodes as static literal if all of their parts are static literal
> Frozen parts

- src/prism.c
- test/prism/snapshots/dos_endings.txt
- test/prism/snapshots/dstring.txt
- test/prism/snapshots/regex.txt
- test/prism/snapshots/seattlerb/parse_line_evstr_after_break.txt
- test/prism/snapshots/seattlerb/qsymbols_interp.txt
- test/prism/snapshots/seattlerb/str_lit_concat_bad_encodings.txt
- test/prism/snapshots/seattlerb/words_interp.txt
- test/prism/snapshots/spanning_heredoc.txt
- test/prism/snapshots/strings.txt
- test/prism/snapshots/symbols.txt
- test/prism/snapshots/unparser/corpus/literal/literal.txt
- test/prism/snapshots/unparser/corpus/semantic/dstr.txt
- test/prism/snapshots/unparser/corpus/semantic/literal.txt
- test/prism/snapshots/whitequark/array_symbols_interp.txt
- test/prism/snapshots/whitequark/array_words_interp.txt
- test/prism/snapshots/whitequark/non_lvar_injecting_match.txt
- test/prism/snapshots/whitequark/regex_interp.txt
- test/prism/snapshots/whitequark/ruby_bug_11990.txt
- test/prism/snapshots/whitequark/string_concat.txt
- test/prism/snapshots/whitequark/xstring_interp.txt
- test/prism/snapshots/xstring.txt
Reverts ruby/prism#2630
Until we get it merged into CRuby and fixed there.
> Revert "Frozen parts"

- config.yml
Clarify that interpolated String could be frozen only when represents adjacent string literals (e.g. `"a" "b"`). It might be not obvious but interpolated Strings declared in the common way (e.g. `"a #{1} b"`) are never frozen AFAIK.
> Improve description for InterpolatedStringNodeFlags

- java/org/prism/ParsingOptions.java
Explicitly convert command line options `int` representation to `byte`.
Implicit convertion leads to the following error in TruffleRuby:
```
/b/b/e/main/src/yarp/java/org/prism/ParsingOptions.java:103: warning: [lossy-conversions] implicit cast from int to byte in compound assignment is possibly lossy
result |= 1 << value.ordinal();
^
error: warnings found and -Werror specified
1 error
```
> Fix serialization of a command line parsing option

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2646
> Handle NULL byte terminators for strings, regexps, and lists

- rbi/prism.rbi
It seems the `offset` parameter for `parse_failure?` is duplicated. Looking at the signature the first one should be `filepath` instead.
I wasn't sure if this file was generated or manually edited?
> Fix signature mismatch with `parse_failure?` parameters

- bin/prism
- src/prism.c
- test/prism/warnings_test.rb
```ruby
a = a = 1
```
no longer warns.
> Reduce locals variables per CRuby

- lib/prism/translation/parser/compiler.rb
- test/prism/parser_test.rb
Given this example:
```rb
<<~HEREDOC
#{1} a
HEREDOC
```
Both the parser gem and Prism's translation layer would generate the following AST:
```
s(:dstr,
s(:begin,
s(:int, 1)),
s(:str, " a\n"))
```
However, the parser gem inserts a empty string node into this node's location, like:
```
<Parser::Source::Map::Heredoc:0x0000000104ce73b8
@expression=#<Parser::Source::Range (string) 0...10>,
@heredoc_body=#<Parser::Source::Range (string) 11...20>,
@heredoc_end=#<Parser::Source::Range (string) 20...27>,
@node=s(:dstr,
s(:str, ""),
s(:begin,
s(:int, 1)),
s(:str, " a\n"))>
```
This is required to calculate the correct whitespace for the heredoc body.
We need to adjust the translation layer to account for this.
With this fix, we also won't need to ignore the tilde heredoc fixture anymore.
Closes …
> Fix parser translation's heredoc whitespace calculation

- lib/prism/translation/parser/compiler.rb
Not a real fix, just a band-aid until it's actually fixed
> "Fix" transpose issue in parser compiler

- rbi/prism/parse_result.rbi
- rbi/prism/reflection.rbi
- templates/rbi/prism/node.rbi.erb
Tapioca currently rewrites `attr_reader` methods in RBI files to normal method definitions when merging signatures, but doesn't include the annotations in the merged result.
Related issue: https://github.com/Shopify/tapioca/issues/1709
This means that current methods typed with `attr_reader` in RBI files are actually untyped in the merged RBI files. So this commit declares those methods with normal method definitions in the RBI files to work around this issue.
> Use normal method definition instead of `attr_reader` in RBI files

- bin/prism
Follow up https://github.com/ruby/prism/pull/2717.
This PR updates the `bin/prism parser` command to use `Parser::Ruby34`. This aligns both Parser gem and `Prism::Translation::Parser` with the same version, Ruby 3.4. Although Parser gem does not yet support Ruby 3.4's `it` parameter, it makes sense to align the versions since preparations for Ruby 3.4 have already begun.
> Use `Parser::Ruby34` for `bin/prism parser` command

- config.yml
Add documentation for the `AliasGlobalVariableNode` fields.
```
irb(main):006> Prism.parse("alias $foo $bar")
=> 
#<Prism::ParseResult:0x0000000122cb6a60
@comments=[],
@data_loc=nil,
@errors=[],
@magic_comments=[],
@source=#<Prism::Source:0x0000000122df93a0 @offsets=[0], @source="alias $foo $bar", @start_line=1>,
@value=
@ ProgramNode (location: (1,0)-(1,15))
├── locals: []
└── statements:
@ StatementsNode (location: (1,0)-(1,15))
└── body: (length: 1)
└── @ AliasGlobalVariableNode (location: (1,0)-(1,15))
├── new_name:
│   @ GlobalVariableReadNode (location: (1,6)-(1,10))
│   └── name: :$foo
├── old_name:
│   @ GlobalVariableReadNode (location: (1,11)-(1,15))
│   └── name: :$bar
└── keyword_loc: (1,0)-(1,5) = "alias",
@warnings=[]>
```
> Document the `AliasGlobalVariableNode` fields

- templates/lib/prism/node.rb.erb
- test/prism/ruby_api_test.rb
Fix https://github.com/ruby/prism/issues/2465
I was hoping that deconstruct would be sufficiently specific, but it doesn't look like it (at least it doesn't include `value` for `IntegerNode`).
Looking at lib/prism/node_ext.rb, #value seems to be the only relevant property that is not a field.
It is derived from slice, but I don't want to do an exact comparison on slice since that would make formatting significant for the comparison.
So now I can either add value to the comparison in Node through a respond_to, or I can make it part of node_ext... which seems better. You can see both options in this PR (see the commits)
> implement value equality and case equality on nodes

- config.yml
- Adds documentation for the fields of the `IfNode`. Also updates the overall description to mention ternary expressions.
- Part of #2123
> Document `IfNode` fields

- config.yml
This PR adds documentation comments in `config.yml` for:
- `GlobalVariableWriteNode`
- `LocalVariableWriteNode`
- `ConstantWriteNode`
- `ConstantPathWriteNode`
> Document remaining `*WriteNode` fields

- ext/prism/extension.c
- include/prism/parser.h
- include/prism/static_literals.h
- src/prism.c
- src/static_literals.c
- test/prism/warnings_test.rb
Fixes https://github.com/ruby/prism/issues/2005
> Warn for duplicated keys in nested hashes as well

- javascript/package.json
It looks like the types for the NPM package were rearranged in https://github.com/ruby/prism/pull/2117.
The `types` field in the `package.json` is currently pointing to a non-existing file resulting in an error like:
```
❯ tsc -w
[5:10:39 PM] Starting compilation in watch mode...
src/importmap_file.ts:1:107 - error TS7016: Could not find a declaration file for module '@ruby/prism'. '/Users/marcoroth/Development/stimulus-parser/node_modules/@ruby/prism/src/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/ruby__prism` if it exists or add a new declaration (.d.ts) file containing `declare module '@ruby/prism';`
1 import { loadPrism, Visitor, CallNode, KeywordHashNode, TrueNode, FalseNode, StringNode, AssocNode } from "@ruby/prism";
~~~~~~~~~~~~~
[5:10:42 PM] Found 1 …
```
> Fix `types` path in `package.json` for NPM package

- src/prism.c
- test/prism/snapshots/heredocs_nested.txt
- test/prism/snapshots/seattlerb/dstr_evstr.txt
- test/prism/snapshots/seattlerb/dstr_str.txt
- test/prism/snapshots/seattlerb/heredoc_nested.txt
- test/prism/snapshots/seattlerb/pct_w_heredoc_interp_nested.txt
- test/prism/snapshots/seattlerb/str_str.txt
- test/prism/snapshots/seattlerb/str_str_str.txt
- test/prism/snapshots/unparser/corpus/literal/literal.txt
- test/prism/snapshots/whitequark/dedenting_heredoc.txt
If a single string that is a static literal is interpolated, it does not impact whether or not the parent is a static literal. In this way, if you have something like a regular expression that interpolates a string literal, it's possible that you will end up pushing just a single regexp onto the stack as opposed to calling out to toregexp.
> Match CRuby interpolation semantics

- ext/prism/extension.c
- lib/prism/ffi.rb
- lib/prism/lex_compat.rb
- lib/prism/parse_result.rb
- rbi/prism/parse_result.rbi
- sig/prism/parse_result.rbs
- templates/ext/prism/api_node.c.erb
- templates/lib/prism/dsl.rb.erb
- templates/lib/prism/serialize.rb.erb
The new code unit APIs work really well and they achieved the behaviour we wanted in the Ruby LSP. Unfortunately, they are significantly slower than the much simpler computation for columns. Invoking `byteslice` repeatedly for large documents slows down the LSP by a lot.
Thankfully, we don't have to pay this price unnecessarily. If we specialize the implementation of the code unit API for ASCII-only sources, then we can take the simpler route which is about 5x faster on my machine.
I created a specialized version of `Source` called `ASCIISource`. Creating an equivalent `MultiByteSource` felt unnecessary, since we can have that as the default behaviour of `Source` (or we can flip if we prefer the faster option as the default).
To decide which kind of source to create, I introduced a …
> Specialize code unit computing for ASCII only sources

- lib/prism/ffi.rb
- lib/prism/translation/parser.rb
Follow up https://github.com/ruby/prism/pull/2760.
This PR updates the `Translation::Parser` to use version 3.3.1 when the version 3.3 is specified. The Parser gem is structured to support the latest patch versions, hence this aligns with Parser-compatible versioning. As noted in https://github.com/ruby/prism/pull/2760, the behavior remains unchanged with this switch from 3.3.0 to 3.3.1.
> Use `version: 3.3.1` against `Translation::Parser`

- ext/prism/extconf.rb
* Notably, RbConfig::CONFIG["CC"] would be the GraalVM LLVM toolchain on TruffleRuby < 24.0 and we specifically do not want to use that as already explained in comments.
Related: #2705 #2725
cc FYI @ParadoxV5
> Do not use values from RbConfig if we are not building a C extension

- lib/prism.rb
- lib/prism/parse_result.rb
- lib/prism/parse_result/comments.rb
- lib/prism/parse_result/newlines.rb
- templates/lib/prism/inspect_visitor.rb.erb
- templates/lib/prism/node.rb.erb
Having the @newline instance variable in every node adds up, and since it is so rarely used, we only want to add it when necessary.
Moving this into an autoloaded file and moving the instance variable out of the default initializers reduces allocated memory because the nodes are now smaller and some fit into the compact list. On my machine, I'm seeing about an 8% drop.
> Autoload newlines and comment visitors

- lib/prism/translation/parser.rb
Resolves #2803.
This PR adds error handling for missing `parser` gem in `Prism::Translation`.
The `parser` gem is a required runtime dependency when using `Prism::Translation::Parser`. But it is not required for other uses of Prism. To avoid unnecessary dependencies, it is not added as a `runtime_dependency` in the prism.gemspec. Instead, if the dependency is missing, instructions are given to add it to Gemfile.
```console
$ bundle exec ruby -e 'require "prism"; require "prism/translation/parser33"'
/Users/koic/.rbenv/versions/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- parser (LoadError)
from /Users/koic/.rbenv/versions/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
from …
```
> Add error handling for missing `parser` gem in `Prism::Translation`

- src/prism.c
These same code in `prism.c`.
```c
{ .start = parser->start, .end = parser->start }
```
And, already defined `PM_LOCATION_NULL_VALUE` macro in `prism.c` that was same these code.
```c
#define PM_LOCATION_NULL_VALUE(parser) ((pm_location_t) { .start = (parser)->start, .end = (parser)->start })
```
May be simpler replace these code to `PM_LOCATION_NULL_VALUE` macro.
> Replace and Use `PM_LOCATION_NULL_VALUE` macro

- .github/workflows/main.yml
I was looking at the GitHub Actions configuration and saw that using a slightly older version of valgrind, so I upgraded valgrind to the latest version, 3.23.0.
If using a fixed version of valgrind for some reason, free to close this pull request as it is.
> Bump up valgrind version to 3.23.0

- config.yml
- include/prism/util/pm_integer.h
- lib/prism/node_ext.rb
- lib/prism/translation/parser/compiler.rb
- src/prism.c
- src/static_literals.c
- src/util/pm_integer.c
- test/prism/snapshots/numbers.txt
- test/prism/snapshots/patterns.txt
- test/prism/snapshots/seattlerb/ruby21_numbers.txt
- test/prism/snapshots/symbols.txt
- test/prism/snapshots/unparser/corpus/literal/literal.txt
- test/prism/snapshots/unparser/corpus/semantic/literal.txt
- test/prism/snapshots/whitequark/complex.txt
- test/prism/snapshots/whitequark/rational.txt
- test/prism/snapshots/whitequark/ruby_bug_11873_a.txt
This eliminates the subnode on RationalNode and replaces it with two integer fields, which represent the ratio for the rational. It also reduces those two integers if they both fit into 32 bits.
Importantly, this PR does not implement bignum reduction. That's something I'd like to consider for the future, but it's simple enough for now to leave them unreduced, which makes it more useful than it used to be.
Fixes https://github.com/ruby/prism/pull/2796.
> Reconfigure rationals

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2834
> Only accept command call when specified for constant path

- src/prism.c
- test/prism/errors_test.rb
In some cases Prism was either not raising an appropriate `void value
expression` error, or raising that error when the syntax is considered
valid.
To fix this Prism needs to check whether we have other clauses on the
`begin` rather than just returning `cast->statements`.
* If the `cast->statements` are null and the `cast->ensure_clause` is
not null, set the code to `cast->ensure_clause`
* else
* If there is a `cast->rescue_clause`
* Check if `cast->statements` are null and `cast->rescue_clause->statements`
are null, and return `NULL`
* Check if there is an `else_clause`, and set the node to
`cast->else_clause`.
* Otherwise return `cast->statements` as the node
* return `cast->statements` as the node
See tests for test cases. Note I took these directly from CRuby so if
desired I can …
> Raise `void value expression` in begin

- templates/sig/prism/node.rbs.erb
Add `Prism::Node#deprecated` method type and supress `deprecated` method type error.
> Add Prism::Node#deprecated method type

- templates/sig/prism/node.rbs.erb
Add `Prism::Node#newline!`method type and supress `newline!` method type error.
> Add Prism::Node#newline! method type

- rust/ruby-prism/src/lib.rs
Closes https://github.com/ruby/prism/discussions/2621
Currently Prism recognizes the `__END__` content and provides a way to access it in Ruby, C, and Java APIs, but Rust bindings does not have it. This PR adds the `data_loc` method to Rust API.
> Add `data_loc` method to Rust bindings

- rakelib/test.rake
After upgrading to ruby_memcheck 3.0.0, on Ruby >= 3.4.0, it disables the heuristics in favor of using RUBY_FREE_AT_EXIT. This caused the issues below to start showing up on CI. This commit changes it to use the original heuristics even for versions that support RUBY_FREE_AT_EXIT.
2,712 bytes in 1 blocks are definitely lost in loss record 1 of 3
malloc (vg_replace_malloc.c:446)
bfd_simple_get_relocated_section_contents (at /usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so)
<unknown stack frame>
<unknown stack frame>
<unknown stack frame>
<unknown stack frame>
<unknown stack frame>
<unknown stack frame>
(below main) (libc_start_call_main.h:58)
8,192 bytes in 1 blocks are definitely lost in loss record 3 of 3
malloc (vg_replace_malloc.c:446)
xrealloc (at …
> Disable use_only_ruby_free_at_exit in ruby_memcheck

- config.yml
This should check off another box in #2123.
According to https://en.wikipedia.org/wiki/Bracket#Parentheses the singular form of parentheses in EN-US is parenthesis, I'm not sure if this is the form we should standardi{s,z}e. I tried looking for other examples with the name of `(` or `)`, but couldn't find anything except for `paren`.
I think the example code covers all use cases.
> Document MultiTargetNode fields

- templates/ext/prism/api_node.c.erb
- templates/src/node.c.erb
- templates/src/serialize.c.erb
ruby/ruby measures test coverage of C code, but the `#line` directive generated by prism points to a file that does not exist, so coverage is not taken properly.
This changeset specifies the location of the source files as a relative path in terms of ruby/ruby repo.
> Set `#line" directives to respect the path in ruby/ruby repo

- Rakefile
- ext/prism/extconf.rb
This is similar to #2550, fixing the same issue as #2527 but on FreeBSD.
I feel like there should be a better way to handle this, or maybe change the Makefile to not use gmake-specific features, but this changes fixed the issue for now.
Tested on FreeBSD 14 with gmake, the gem builds correctly.
> Use gmake on FreeBSD

- src/prism.c
- test/prism/locals_test.rb
In the case that we're parsing invalid local variable writes, we still need to add the name to the local table, otherwise it could fail to find the local later when modifying it.
> When parsing an invalid write, still add to the local table

- templates/lib/prism/dispatcher.rb.erb
This PR tweaked the documentation to correct an error encountered when running the example code of `Prism::Dispatcher`. This aims to make understanding the example smoother.
> [Doc] Tweak example of `Prism::Dispatcher`

- ext/prism/extension.c
- src/prism.c
- test/prism/api/parse_stream_test.rb
Previously `parse_stream` would fail when the input contained `NUL` bytes because it was using `strlen`. We really should use `getline`, but it's POSIX-only, and until I have time to get a window-alternative, I'm going with this slightly hacky solution of filling the buffer with all newline characters and then looking backward for the last non-newline character.
> Have parse_stream handle NUL bytes

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2947
> Ignore shebangs in evals

- templates/java/org/prism/Loader.java.erb
- templates/java/org/prism/Nodes.java.erb
- templates/src/serialize.c.erb
From https://github.com/ruby/prism/pull/2924#issuecomment-2248749015, `average` went from 0.799 before #2924 to 0.950 after, with this PR it goes back to 0.800.
As an aside this makes the `flags` field public again, which is necessary as TruffleRuby uses it like that (the error can be seen at https://github.com/oracle/truffleruby/actions/workflows/prism.yml).
> Optimize serialized size for PRISM_SERIALIZE_ONLY_SEMANTICS_FIELDS=1

- ext/prism/extension.c
`Prism.lex` and `Prism.lex_file` return `ParseLexResult` instead of `Array`. `Prism::parse_lex` and `Prism::parse_lex_file` return `ParseLexResult` instead of `ParseResult`. This PR updates the documentation to reflect these return values.
> [Doc] Tweak the docs for lex APIs

- lib/prism/parse_result.rb
This PR tweaks inspect representation of `Prism::Location`.
During debugging, the meaning of `@location=21474836481` was unclear:
```console
$ ruby -Ilib -rprism -e 'p Prism.lex("puts :hi").value.map(&:first)[1]'
#<Prism::Token:0x000000010cd74e40 @source=#<Prism::ASCIISource:0x000000010cb5f808 @source="puts :hi", @start_line=1, @offsets=[0]>,
@type=:SYMBOL_BEGIN, @value=":", @location=21474836481>
```
This PR clarifies the contents of the location object, aligning with what I think user expects:
```console
$ ruby -Ilib -rprism -e 'p Prism.lex("puts :hi").value.map(&:first)[1]'
#<Prism::Token:0x000000010e174d50 @source=#<Prism::ASCIISource:0x000000010df5efe8 @source="puts :hi", @start_line=1, @offsets=[0]>,
@type=:SYMBOL_BEGIN, @value=":", @location=#<Prism::Location @start_offset=5 …
```
> Tweak inspect representation of `Prism::Location`

- include/prism/options.h
- src/options.c
- src/prism.c
Add the ability to receive a callback when the parser encounters a shebang that contains additional switches after the Ruby engine. This is necessary because some command-line flags may be present there that will alter the parse.
> Callback on shebang switches

- .travis.yml
Allow failures for ppc64le/s390x due to the following infra errors.
https://app.travis-ci.com/github/ruby/prism/builds/271968231
> No output has been received in the last 10m0s, this potentially indicates
> a stalled build or something wrong with the build itself.
> Allow failures for arm64/ppc64le/s390x due to infra errors.

- templates/include/prism/ast.h.erb
The `config.yml` file contains nodes with comments, but none of those are surfaced in the header docs `ast.h`, and thus don't get rendered into the doxygen site.
This PR fixes that, and greatly improves the quality of the docsite. Compare:
|          | Before | After |
|----------|--------|-------|
| Overview | <img width="475" alt="Before overview" src="https://github.com/user-attachments/assets/8b6f1760-47bf-44d7-b24b-90550173666c"> | <img width="460" alt="Before details" src="https://github.com/user-attachments/assets/a0948944-addb-495c-9dfe-3273c5393642"> |
| Details  | <img width="478" alt="After overview" src="https://github.com/user-attachments/assets/8a27610e-f3d3-4b1a-9b57-c45ae81bb355"> | <img width="479" alt="After detais" …
> Render node comments into their `ast.h`

- include/prism/util/pm_integer.h
- src/util/pm_integer.c
Low priority. Just a quick little optimization I found.
Before:
```
| uint32_t value |   32 bit pad   |
|     64 bit   size_t  length     |
|     64 bit uint32_t *values     |
| b |       56 bit padding        | <- waste
^ bool negative
```
After:
```
|     64 bit   size_t  length     |
|     64 bit uint32_t *values     |
| uint32_t value | b | 32 bit pad |
```
We can shrink this down to 16 bytes, and use fewer allocations:
* We can use a `union` to combine the `uint32_t value` and `uint32_t *values` together.
* At that point, we can widen the `value` to `int` and make it word-sized (`uint64_t` on 64 bit machines), so we'd can fit more integers inline without allocations
* Can use `length == 0` as a discriminator
* We can tuck the `negative` bit into the `length` field.
> Shrink `pm_integer_t` (32 bytes → 24)

- src/prism.c
- test/prism/result/warnings_test.rb
Related to #2996
Fixes the second of the two assertion failures here:
```
TestRubyOptions#test_shebang [/Users/alex/src/github.com/Ruby/ruby/test/ruby/test_rubyoptions.rb:514]:
pid 49518 exit 0.
1. [1/2] Assertion for "stdout"
| <["\"あ\""]> expected but was
| <["\"\\u3042\""]>.
2. [2/2] Assertion for "stderr"
| Expected /shebang line ending with \\r/ to match "".
Finished tests in 0.030572s, 32.7097 tests/s, 359.8064 assertions/s.
1 tests, 11 assertions, 1 failures, 0 errors, 0 skips
ruby -v: ruby 3.4.0dev (2024-08-22T14:01:55Z master 56a34b5af5) +PRISM [arm64-darwin23]
make: *** [yes-test-all] Error 1
```
The "string" (pointer+length combo) given to `pm_parser_warn_shebang_carriage_return` ended on the `\r`, right before the `\n`. So the check for `\r\n` actually found `8\r` instead. …
> Fix bug when `#!` ends with carriage return

- ext/prism/extension.c
- src/util/pm_string.c
- test/prism/api/parse_test.rb
> UTF-8 characters in file name

- templates/include/prism/ast.h.erb
- templates/java/org/prism/Nodes.java.erb
- templates/javascript/src/nodes.js.erb
- templates/lib/prism/node.rb.erb
- templates/rbi/prism/node.rbi.erb
- templates/template.rb
Recently common flags were added for every node in #2924. So each flag value was increased by 2. There were changes for Ruby and JS but not for Java.
Also I have found helpful to have similar formatting/code style in templates (at least for the code to generate flags) to easily find difference. So I changed it a bit in several templates what is quite subjective.
> Fix node flags values for Java

- include/prism/util/pm_string.h
- src/util/pm_string.c
- test/prism/api/parse_test.rb
Fixes https://github.com/ruby/prism/issues/3059
> Stat file first to check directory

- lib/prism/translation/ruby_parser.rb
- src/prism.c
- test/prism/fixtures/regex_escape_encoding.txt
- test/prism/locals_test.rb
- test/prism/snapshots/regex_escape_encoding.txt
- test/prism/test_helper.rb
Fixes [Bug #20744]
Fixes https://github.com/ruby/prism/issues/3067
> Do not leak explicit encoding

- ext/prism/extension.c
- include/prism/options.h
- include/prism/parser.h
- java-wasm/src/test/java/org/prism/DummyTest.java
- java/org/prism/ParsingOptions.java
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- src/options.c
- src/prism.c
- test/prism/api/parse_test.rb
Unfortunately since https://github.com/ruby/ruby/pull/11099 the trick of passing scopes to mark jumps as being okay doesn't work anymore. So introducing `partial_script` to make it possible to parsing ERB templates without having to worry about the errors.
> Introduce partial_script option

- lib/prism/translation/parser/lexer.rb
- test/prism/ruby/parser_test.rb
This PR fixes `kDO_LAMBDA` token incompatibility between Parser gem and `Prism::Translation::Parser` for lambda `do` block.
Returns `kDO_LAMBDA` token:
```console
$ bundle exec ruby -Ilib -rparser/ruby33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); buf.source = "-> do end"; p Parser::Ruby33.new.tokenize(buf)[2]'
ruby 3.4.0dev (2024-09-01T11:00:13Z master eb144ef91e) [x86_64-darwin23]
[[:tLAMBDA, ["->", #<Parser::Source::Range example.rb 0...2>]], [:kDO_LAMBDA, ["do", #<Parser::Source::Range example.rb 3...5>]],
[:kEND, ["end", #<Parser::Source::Range example.rb 6...9>]]]
```
Previously, the parser returned `kDO` token when parsing the following:
```console
$ bundle exec ruby -Ilib -rprism -rprism/translation/parser33 -ve \
'buf = Parser::Source::Buffer.new("example.rb"); …
```
> Fix `kDO_LAMBDA` token incompatibility for `Prism::Translation::Parser::Lexer`

- ext/prism/extension.c
- lib/prism/ffi.rb
- src/options.c
- test/prism/version_test.rb
> Accept all 3.3.x and 3.4.x Ruby versions for Prism.parse

- config.yml
- docs/parsing_rules.md
- rakelib/typecheck.rake
- rust/ruby-prism/build.rs
- src/prism.c
- templates/include/prism/ast.h.erb
- templates/java/org/prism/Loader.java.erb
- templates/lib/prism/dsl.rb.erb
- templates/lib/prism/node.rb.erb
- templates/rbi/prism/dsl.rbi.erb
- templates/template.rb
* For Loader.java, do not deserialize the AST if there are errors, so then Java nodes only have non-error types for fields.
> Type every node field and mark on-error-only types explicitly

- lib/prism/lex_compat.rb
Fixes https://github.com/ruby/prism/issues/2842
> Fix up lex difference when ~ heredoc with 0 dedent and line continuation

- config.yml
This adds some documentation to the fields for `AliasMethodNode` and `AlternationPatternNode`. I was going to go through and do more, but wanted to get a pull-request up for review before moving forward with any others just incase. I'm trying to get more familiar with all of the node types and fields for a project that utilizes Prism, so this looks like a better (and more productive!) way to do it.
I also wanted to check if there was any other smaller intro issues/tickets where there might be an opportunity to jump in on. I took a brief look through and wasn't too sure on the scope of the existing ones on the issues board. If there was any other high-level ideas thrown around for more examples/guides for Prism I'd be happy to explore those too!
> Add fields documentation for AliasMethodNode and AlternationPatternNode

- src/prism.c
- test/prism/errors/amperand_dot_after_endless_range.txt
Fixes https://github.com/ruby/prism/issues/3105
> Disallow &. after endless range

- src/prism.c
- test/prism/errors/infix_after_label.txt
Partially addresses https://github.com/ruby/prism/issues/3098
> Disallow infix operators after label

- src/prism.c
- test/prism/errors/dynamic_label_pattern.txt
Fixes https://github.com/ruby/prism/issues/3098
> Disallow dynamic patterns in labels at top level followed by pipes

- src/prism.c
- test/prism/errors/range_doubled.txt
Fixes https://github.com/ruby/prism/issues/3121
> Fix up doubled range in arguments

- src/prism.c
- test/prism/magic_comment_test.rb
Fixes https://github.com/ruby/prism/issues/3129
> Handle single global variable character name

- src/prism.c
- test/prism/api/command_line_test.rb
I suppose the `contains_keywords` flag is missing here because arguments contain keyword arguments `chomp: true` .
Examples before and after:
```shell
bin/prism parse -n -l -e 'puts $_.end_with?("\n")'
```
AST before:
```
@ ProgramNode (location: (1,0)-(1,0))
├── flags: ∅
├── locals: []
└── statements:
@ StatementsNode (location: (1,0)-(1,0))
├── flags: ∅
└── body: (length: 1)
└── @ WhileNode (location: (1,0)-(1,0))
├── flags: newline
├── keyword_loc: (1,0)-(1,0) = ""
├── closing_loc: (1,0)-(1,0) = ""
├── predicate:
│   @ CallNode (location: (1,0)-(1,0))
│   ├── flags: ignore_visibility
│   ├── receiver: ∅
│   ├── call_operator_loc: ∅
│   ├── name: :gets
│   ├── message_loc: ∅
│   ├── opening_loc: ∅
│   ├── arguments:
│   │   @ ArgumentsNode (location: (1,0)-(1,23))
│   │   ├── flags: ∅
│ …
```
> Set contains_keywords flag for implicit gets($/, chomp: true) method to handle -l CLI option

- src/prism.c
- test/prism/errors/binary_range_with_left_unary_range.txt
- test/prism/errors/non_assoc_equality.txt
- test/prism/errors/range_and_bin_op.txt
- test/prism/errors/range_and_bin_op_2.txt
Fixes https://github.com/ruby/prism/issues/3008
> Properly handle non-assoc operators

- lib/prism/parse_result.rb
- test/prism/ruby/location_test.rb
When a file is using binary encoding and contains multibyte characters, trying to call `encode` with one of the accepted LSP encodings (UTF-8, UTF-16 or UTF-32) will fail because it's not a valid conversion.
In situations like these, we want to avoid breaking, even if we can't provide the correct locations for nodes. In the included test, you can see that the locations are all using the number of bytes, rather than the code units.
> Avoid breaking code units offset on binary encoding

- config.yml
Its `exception` field was renamed to `reference` in #1204 but the documentation was not updated.
> Update rescue node doc

- src/prism.c
- test/prism/errors/invalid_splat.txt
Fixes https://github.com/ruby/prism/issues/3169
> Reject invalid splat as last statement of parentheses

- src/prism.c
- test/prism/result/warnings_test.rb
> Do not warn for unused variables on negative lines

- lib/prism/parse_result.rb
- rbi/prism/parse_result.rbi
- sig/prism/_private/parse_result.rbs
- sig/prism/parse_result.rbs
- test/prism/ruby/location_test.rb
Calculating code unit offsets for a source can be very expensive, especially when the source is large. This commit introduces a new class that wraps the source and desired encoding into a cache that reuses pre-computed offsets. It performs quite a bit better.
There are still some problems with this approach, namely character boundaries and the fact that the cache is unbounded, but both of these may be addressed in subsequent commits.
Some benchmarks, using the following script:
```ruby
require "bundler/setup"
require "prism"
require "benchmark"
code = "😀😀😀😀😀😀😀😀" * Integer(ARGV.first)
result = Prism.parse(code)
source = result.source
bytesize = code.bytesize
Benchmark.bm do |x|
x.report("old") do
1000.times { source.code_units_offset(rand(bytesize), Encoding::UTF_16LE) }
end …
```
> Prism::CodeUnitsCache

- ext/prism/extension.c
Supress this warning for string_query function.
```console
compiling ../../../../ext/prism/extension.c
../../../../ext/prism/extension.c: In function ‘string_query’:
../../../../ext/prism/extension.c:1156:1: warning: control reaches end of non-void function [-Wreturn-type]
1156 | }
| ^
../../../../ext/prism/extension.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
```
> Supress string_query function warning

- .github/workflows/main.yml
* By using ubuntu-24.04 which has a recent enough valgrind: https://github.com/ruby/prism/pull/3182#issuecomment-2420294315
cc @peterzhu2118
> Speedup memcheck job

- src/util/pm_char.c
It looks like we can possibly do an out of bounds read if size is equal to 0.  This commit adds a conditional to ensure size is actually greater than 0 before looking backwards in the buffer
> Only read from buffer if `size` is greater than 0

- java/org/prism/Parser.java
* We intentionally load a native library here and need it.
* I also tried `@SuppressWarnings("all")` but that still emitted the warning.
> Suppress restricted warnings from JDK 24

- java-wasm/pom.xml
- java-wasm/src/test/java/org/prism/DummyTest.java
:wave: we just released a first Milestone for Chicory, since it's breaking in many ways, I wanted to check that everything remains aligned.
Notes:
- we now have a `wasi` implementation, so, some more code-paths should be usable (for filesystem operation we suggest to use Jimfs though)
- we have a new AOT compiler, I would be happy to set up here, basically we can ship a "ready to run" Jar package for Prism, wdyt? (example: [wabt](https://github.com/dylibso/chicory/tree/main/wabt))
> Bump Chicory to 1.0.0-M1

- .travis.yml
This PR includes 2 commits.
* .travis.yml: Add @junaruga's email address to receive notifications.
* .travis.yml: Drop arm64 case as a temporary workaround.
It's the same issue with the ruby/ruby, See <https://bugs.ruby-lang.org/issues/20013#note-48> for details.
> .travis.yml: Add @junaruga's email address to receive notifications.

- src/regexp.c
- test/prism/regexp_test.rb
Parsing the regexp /\A{/ causes uses an uninitialized value because it tries to parse it as a range quantifier, so it reads the character after the closing curly bracket. This is using uninitialized values because prism strings are not null terminated. This can be seen in the Valgrind output:
==834710== Conditional jump or move depends on uninitialised value(s)
==834710==    at 0x5DA010: pm_regexp_parse_range_quantifier (regexp.c:163)
==834710==    by 0x5DA010: pm_regexp_parse_quantifier (regexp.c:243)
==834710==    by 0x5DAD69: pm_regexp_parse_expression (regexp.c:738)
==834710==    by 0x5DAD69: pm_regexp_parse_pattern (regexp.c:761)
==834710==    by 0x5DAD69: pm_regexp_parse (regexp.c:773)
==834710==    by 0x5A2EE7: parse_regular_expression_named_captures (prism.c:20886)
==834710== …
> Fix use of uninitialized value when parsing regexp

- lib/prism/ffi.rb
* This is notably necessary on TruffleRuby, which is updating to Ruby 3.3 which introduces Prism as a default gem.
* Using the existing path is not an option as it would end up in truffleruby/lib/build/libprism.so and "truffleruby/lib/include/#{header}" which are not good places for such files.
> Use RbConfig to locate libprism and headers when it is a default gem

- Gemfile
- Gemfile.lock
RDoc has started receiving more updates, especially around the default theme. By having it as a development dependency, we can use the latest theme for Prism's Ruby documentation too.
> Add RDoc to development dependencies to use its new theme

- src/util/pm_string.c
When mmap fails for any reason, the fd must be closed.
Coverity Scan found this issue.
> Fix a possible leak of a file descriptor

- src/prism.c
This is not important because of the path of `assert(false)`, but just in case.
Coverity Scan found this issue.
> Fix a copy-paste error

- config.yml
> Add document CallNode fields

- config.yml
> Add document BlockParameterNode fields

- config.yml
> Add document AliasMethodNode fields

- config.yml
> Add document ArrayPatternNode fields

- config.yml
> Add document BeginNode fields

- src/prism.c
- test/prism/errors/array_with_double_commas.txt
- test/prism/errors/double_splat_with_double_commas.txt
Fixes: https://github.com/ruby/prism/issues/3109
> Reject extra comma in array after keyword argument

- src/prism.c
- test/prism/errors/match_predicate_after_and_with_dot_method_call.txt
- test/prism/errors/match_predicate_after_or_with_dot_method_call.txt
- test/prism/errors/match_predicate_after_rescue_with_dot_method_call.txt
- test/prism/errors/match_required_after_and_with_dot_method_call.txt
- test/prism/errors/match_required_after_or_with_dot_method_call.txt
- test/prism/errors/match_required_after_rescue_with_dot_method_call.txt
Partially fixes:  https://github.com/ruby/prism/issues/3171
> Reject invalid dot method call after match predicate or after match required

- src/prism.c
- test/prism/errors/match_predicate_after_and_with_opreator.txt
- test/prism/errors/match_predicate_after_or_with_opreator.txt
- test/prism/errors/match_predicate_after_rescue_with_opreator.txt
- test/prism/errors/match_required_after_and_with_opreator.txt
- test/prism/errors/match_required_after_or_with_opreator.txt
- test/prism/errors/match_required_after_rescue_with_opreator.txt
> Reject invalid operator after match predicate or after match required

- include/prism/defines.h
- src/prism.c
- src/static_literals.c
Instead cast it inline to a double on Windows.
Fixes https://github.com/ruby/prism/issues/3260
> _finitef is unavailable on Windows x86

- config.yml
> Add document CallTargetNode fields

- config.yml
> Add document CallOrWriteNode fields

- config.yml
> Add document CallOperatorWriteNode fields

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
Partially: https://bugs.ruby-lang.org/issues/20785
> [Bug #20785] Allow `, and` and `, or`  after patterns

- .github/workflows/build-artifacts.yml
This GitHub Action builds Prism for Linux and MacOS and then uploads the builds to the latest release.
I am working on adopting Prism in a third-party library (Sorbet) where Ruby is not available during the build process. In order to avoid adding Ruby to the Sorbet build pipeline, I would like to have access to pre-built Prism binaries that Sorbet can pull and use in its build process.
> GitHub Action that uploads builds as release artifacts

- config.yml
> Add document CaseNode fields

- config.yml
> Add document CaseMatchNode fields

- ext/prism/extconf.rb
This commit teaches mkmf about the libprism sources and allows it to compile them directly
Fixes #3273
I was able to teach `mkmf` about the `libprism` source files without copying them in to the ext folder.  The code isn't particularly nice, you have to know about global variables internal to `mkmf`, but it does eliminate calling `make` during the gem build process.
@mame do you think this will work on mswin64?  I don't have a machine handy to test with.
> Don't use `make` while building Prism

- src/prism.c
- test/prism/errors/unterminated_block.txt
- test/prism/errors/unterminated_method_parameters.txt
- test/prism/errors_test.rb
If we hit an EOF token, and the character before the EOF is a newline, we need to rewind the error to the newline so that error messages contain the correct newline.
Before this commit, we would report an error on the "line of the EOF" which would come right after the newline
https://bugs.ruby-lang.org/issues/20918
> Fix error messages for unterminated ( and {

- src/prism.c
- test/prism/percent_delimiter_string_test.rb
parse.y treats CRLF as a LF and basically "normalizes" them before parsing.  That means a string like `%\nfoo\r\n` is actually treated as `%\nfoo\n` for the purposes of parsing.  This happens on both the opening side of the percent string as well as on the closing side.  So for example `%\r\nfoo\n` must be treated as `%\nfoo\n`.
To handle this in Prism, when we start a % string, we check if it starts with `\r\n`, and then consider the terminator to actually be `\n`.  Then we check if there are `\r\n` as we lex the string and treat those as `\n`, but only in the case the start was a `\n`.
Fixes: #3230
[Bug #20938]
> Fix percent delimiter strings with crlfs

- src/prism.c
- test/prism/errors/double_scope_repeated_numbered_parameters.txt
Raise an exception when the same numbered param is used inside a child block.  For example, the following code should be a syntax error:
```ruby
-> { _1 + -> { _1 } }
```
Fixes #3291
> Same numbered param cannot be used in child blocks

- src/prism.c
- test/prism/percent_delimiter_string_test.rb
%r regular expressions need to be decoded like strings.  This commit fixes %r decoding so it works like strings.
> Decode %r like % strings

- include/prism/defines.h
- src/prism.c
- src/static_literals.c
Supersedes https://github.com/ruby/prism/pull/3274
> Use isinf on non-mingw windows

- src/prism.c
- test/prism/errors/block_args_in_array_assignment.txt
- test/prism/errors/keyword_args_in_array_assignment.txt
- test/prism/errors_test.rb
This PR is replicating the changes made in ruby/ruby#12343 and ruby/ruby#12342 in order to sync them to the upstream Prism repo.
I was under the impression that Prism was set up with a bi-directional sync, so that changes made to Prism inside the ruby repo would be mirrored here - but that doesn't seem to be the case?
> Blocks & kwargs are not valid in index assignments

- Makefile
- include/prism/defines.h
- src/prism.c
- src/regexp.c
This PR enables [`-Wimplicit-fallthrough`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough) to catch any potentially unintended fall-through between `case` bodies.
The exiting `/* fallthrough */` comments are now formalized with a new `PRISM_FALLTHROUGH` macro which:
* Uses C23's standardized `[[fallthrough]]` attribute, if available,
* Uses `__attribute__((fallthrough))` on GCC and Clang
* Uses to `__fallthrough` on MSVC
> Enable implicit fall-through errors

- src/prism.c
- test/prism/unescape_test.rb
> Handle escaped characters after controls

- .github/dependabot.yml
- .github/workflows/main.yml
- bin/prism
- gemfiles/3.5/Gemfile
- gemfiles/3.5/Gemfile.lock
Current CI fails because head now refers to 3.5-dev.
Edit: Seems it's not yet available for windows
> Add Ruby 3.5-dev to CI

- include/prism/defines.h
This PR fixes a cross-compile issue of PicoRuby.
I'm trying to build PicoRuby, which uses Prism, on Ubuntu 24.04. But it causes the following build error.
```
$ rake pico --trace
(snip)
CC    build/repos/r2p2-cortex-m0plus/mruby-compiler2/lib/prism/src/util/pm_integer.c -> build/r2p2-cortex-m0plus/mrbgems/mruby-compiler2/lib/pm_integer.o
/home/pocke/ghq/github.com/picoruby/R2P2/lib/picoruby/build/repos/r2p2-cortex-m0plus/mruby-compiler2/lib/prism/src/util/pm_integer.c: In function 'pm_integer_string':
/home/pocke/ghq/github.com/picoruby/R2P2/lib/picoruby/build/repos/r2p2-cortex-m0plus/mruby-compiler2/lib/prism/src/util/pm_integer.c:623:44: error: expected ')' before 'PRIu64'
623 |         pm_buffer_append_format(buffer, "%" PRIu64, value);
|                                ~ …
```
> Fix cross-compile issue with newlib on Ubuntu 24.04

- lib/prism/translation/parser/compiler.rb
- test/prism/fixtures/lambda.txt
- test/prism/fixtures/methods.txt
- test/prism/snapshots/lambda.txt
- test/prism/snapshots/methods.txt
Blocks and lambdas inherit anonymous arguments from the method they are a part of. They themselves don't allow to introduce new anonymous arguments. While you can write this:
```rb
def foo(*)
bar { |**| }
end
```
referecing the new parameter inside of the block will always be a syntax error.
I actually thought that the code snippet above would be a syntax error but apparently not. It seems a bit inconsistent but whatever :shrug:
> Fix parser translator ast when using anonymous forwarding in blocks/lambda

- src/prism.c
Fixes https://github.com/ruby/prism/pull/3365
> Fix global variable read off end

- lib/prism/translation/parser/compiler.rb
- test/prism/ruby/parser_test.rb
Heredocs don't don't start a new string node when encountering "\\\n".
Builds on top of #3343, but only because the tokens would otherwise not line up. It's otherwise totally standalone. Will actually fix https://github.com/rubocop/rubocop/issues/12878
> Fix parser translator ast for heredoc with written newlines

- sig/prism/parse_result.rbs
`Prism::Comment` has an instance method `#slice`.
https://github.com/ruby/prism/blob/7262d09d220966c6902e8b8514909b08bb5f8c0c/lib/prism/parse_result.rb#L522-L524
> Add rbs signature for `Prism::Comment#slice`

- src/prism.c
- test/prism/errors/setter_method_cannot_be_defined_in_an_endless_method_definition.txt
Prism shoudld throw a syntax error for endless methods when the method name uses brackets. Previously it would not. This matches the behavior of parse.y.
Fixes https://bugs.ruby-lang.org/issues/21010
> Throw syntax error for endless method with `[]=`

- lib/prism/translation/parser/compiler.rb
- test/prism/ruby/parser_test.rb
Fixes https://github.com/rubocop/rubocop/issues/12870
For example:
```rb
"a
#{}
c
"
```
The parser gem produces
```rb
s(:dstr,
s(:str, "a\n"),
s(:begin),
s(:str, "\n"),
s(:str, "c\n"))
```
While the translator wraps the last two string nodes in a dstr. There was already logic that kinda was supposed to handle this but it was too specific, applying only when the interpolation contains a single string node.
Much of this logic should be shared between interpolated symbols and regexps. It's also incorrect when the node contains a literal `\\n` (same as for plain string nodes at the moment).
After https://github.com/ruby/prism/pull/3373 is merged, the added method for creating string nodes can be used to make it more correct in all of these cases.
> Better handle multiline interpolated strings in the parser translator

- src/prism.c
- test/prism/errors/defs_endless_method.txt
Fixes: https://bugs.ruby-lang.org/issues/20785
> [Bug #21010] Reject endless method definition of `[]=`

- .github/workflows/main.yml
It was omitted from https://github.com/ruby/prism/pull/3348 because it was not available yet at that time
> Reenable 3.4 windows CI

- .github/workflows/build-artifacts.yml
- .github/workflows/cruby-bindings.yml
- .github/workflows/documentation.yml
- .github/workflows/main.yml
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
This way, if a bunch of stuff gets merged one after the other, CI on main is not often displayed red.
`build-artifacts.yml` doesn't run on PRs but I don't think it hurt to have this uniform in case it gets copied around
> Only cancel in-progress workflows for pull requests

- src/prism.c
- test/prism/errors/pattern_match_with_unexpected_splat_inside_arraytxt
`a => [-2**b]` should be SyntaxError
Fixes: https://github.com/ruby/prism/issues/3381
> Reject pattern match with unexpected double splat inside array

- .github/workflows/build-artifacts.yml
Instead of uploading the built `libprism.so` and `libprism.dylib`, which still requires headers files to be built, Prism can upload the full source, headers, and the Makefile as a tarball that can be used to build `libprism` from source.
The reason default release artifacts are not enough is because some source and header files are generated through Prism's rake tasks.
Example release: https://github.com/Shopify/prism/releases/tag/v1.3.2
Note: This is @paracycle's brilliant idea 🚀
> Modify `build-artifacts.yml` to package libprism source instead

- lib/prism/translation/parser/lexer.rb
Similar to what the compiler already has.
> Add a range helper to the parser translator lexer

- lib/prism/translation/parser/lexer.rb
- test/prism/fixtures/strings.txt
- test/prism/ruby/parser_test.rb
- test/prism/snapshots/strings.txt
```rb
'foo\
bar\\
baz
'
```
Before:
```
0...1: tSTRING_BEG     => "'"
1...12: tSTRING_CONTENT => "foobar\\\n"
12...16: tSTRING_CONTENT => "baz\n"
16...17: tSTRING_END     => "'"
17...18: tNL             => nil
```
After:
```
0...1: tSTRING_BEG     => "'"
1...6: tSTRING_CONTENT => "foo\\\n"
6...12: tSTRING_CONTENT => "bar\\\n"
12...16: tSTRING_CONTENT => "baz\n"
16...17: tSTRING_END     => "'"
17...18: tNL             => nil
```
Additionally, a trailing backslash in a word array is not a line continuation, but rather makes the following newline part of the string/symbol.
> Fix parser translator tokens for backslashes in single-quoted strings and word arrays

- lib/prism/translation/ripper.rb
- src/prism.c
- test/prism/snapshots/whitequark/not.txt
`not foo` should be `!foo`
`not()` should be `!nil`
Fixes [Bug #21027]
Fixes https://github.com/ruby/prism/issues/3392
> Fix `not` receiver

- lib/prism/translation/parser.rb
- test/prism/fixtures/encoding_binary.txt
- test/prism/fixtures/encoding_euc_jp.txt
- test/prism/ruby/parser_test.rb
- test/prism/ruby/ruby_parser_test.rb
- test/prism/snapshots/encoding_binary.txt
- test/prism/snapshots/encoding_euc_jp.txt
- test/prism/snippets_test.rb
Skipping detecting the encoding is almost always right, just for binary it should actually happen.
A symbol containing escapes that are invalid in utf-8 would fail to parse since symbols must be valid in the script encoding.
Additionally, the parser gem would raise an exception somewhere during string handling.
The parser gem reject code where a string is invalid in the script encoding. RuboCop however monkey-patches that behaviour out, I have mirrored that logic for the tests here.
> Fix binary encoding for parser translator

- lib/prism/translation/parser/lexer.rb
A rather silly issue with a rather simple fix.
The ranges already use the offset cache, this effectivly double-encoded them.
Properly fixes https://github.com/rubocop/rubocop/issues/12982
Fixes https://github.com/rubocop/rubocop/issues/13204
I didn't at tests since it seems highly specific but I can add one if you prefer.
> Fix parser translator ranges for mulltiline strings with multiline bytes

- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/ruby_parser.rb
- templates/ext/prism/api_node.c.erb
- templates/lib/prism/serialize.rb.erb
- test/prism/encoding/regular_expression_encoding_test.rb
- test/prism/result/string_test.rb
Fixes https://github.com/ruby/prism/issues/3309
> Frozen strings in the AST

- lib/prism/translation/parser/lexer.rb
- test/prism/ruby/parser_test.rb
Tests worked around this but the incompatibility is not hard to fix. This fixes 17 token incompatibilies in tests here that were previously passing
> Fix parser translator tSPACE tokens for percent arrays

- lib/prism/translation/parser/lexer.rb
- test/prism/ruby/parser_test.rb
```rb
<<~F
foo
#{}
bar
F
```
has zero common whitespace.
> Fix parser translator heredoc dedention with leading interpolation

- .github/workflows/build-artifacts.yml
Run `bundle exec rake templates` instead of `bundle exec rake compile` because the only generated code needed for release are the headers.
> Simplify build-artifacts GitHub workflow

- lib/prism/translation/parser/lexer.rb
- test/prism/ruby/parser_test.rb
It falsely considered it to be a single backtick command
> Fix parser translator tokens for `%x(#{})`

- lib/prism/translation/ruby_parser.rb
- test/prism/fixtures/it.txt
- test/prism/snapshots/it.txt
Testing with `x { it } `:
**Before:**
RubyParser:
```ruby
s(:iter, s(:call, nil, :x), 0, s(:call, nil, :it))
```
Prism:
```ruby
s(:iter, s(:call, nil, :x), [], s(:call, nil, :it))
```
**After:**
RubyParser:
```ruby
s(:iter, s(:call, nil, :x), 0, s(:call, nil, :it))
```
Prism:
```ruby
s(:iter, s(:call, nil, :x), 0, s(:call, nil, :it))
```
> Fix block paremeters and `it` for RubyParser

- test/prism/ruby/parser_test.rb
Now it's possible to receive an assertion like this:
```
expected: []
actual: [:tNL, [nil, #<Parser::Source::Range comment_single.txt 8...9>]]
<[]> expected but was
<[:tNL, [nil, #<Parser::Source::Range comment_single.txt 8...9>]]>
```
All tests pass so it's no big deal but in https://github.com/ruby/prism/pull/3399 I almost introduced a different bug where this check would then have failed like this instead of silently passing.
> Be a bit stricter when comparing parser translator tokens

- lib/prism/translation/parser/lexer.rb
- test/prism/fixtures/strings.txt
- test/prism/ruby/parser_test.rb
- test/prism/snapshots/strings.txt
Also fixes a token incompatibility for the word separator. parser only considers whitespace until the first newline
> Fix parser translator tokens for %-arrays with whitespace escapes

- ext/prism/extension.c
- include/prism/options.h
- java/org/prism/ParsingOptions.java
- javascript/src/index.js
- javascript/src/parsePrism.js
- javascript/test.js
- lib/prism/ffi.rb
- lib/prism/parse_result.rb
- rbi/prism.rbi
- rbi/prism/parse_result.rbi
- sig/prism/parse_result.rbs
- src/options.c
- src/prism.c
- templates/sig/prism.rbs.erb
- test/prism/api/parse_test.rb
When parent scopes around an eval are forwarding parameters (like *, **, &, or ...) we need to know that information when we are in the parser. As such, we need to support passing that information into the scopes option. In order to do this, unfortunately we need a bunch of changes.
The scopes option was previously an array of array of strings. These corresponded to the names of the locals in the parent scopes. We still support this, but now additionally support passing in a Prism::Scope instance at each index in the array. This Prism::Scope class holds both the names of the locals as well as an array of forwarding parameter names (symbols corresponding to the forwarding parameters). There is convenience function on the Prism module that creates a Prism::Scope object using Prism.scope.
In …
> Support forwarding flags on scopes

- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/parser/lexer.rb
- test/prism/ruby/parser_test.rb
Turns out, it was already almost correct. If you disregard \c and \M style escapes, only a single character is allowed to be escaped in a regex so most tests passed already.
There was also a mistake where the wrong value was constructed for the ast, this is now fixed. One test fails because of this, but I'm fairly sure it is because of a parser bug. For `/\“/`, the backslash is supposed to be removed because it is a multibyte character. But tbh, I don't entirely understand all the rules.
Fixes more than half of the remaining ast differences for rubocop tests
> Better handle regexp in the parser translator

- test/prism/ruby/parser_test.rb
Without a change from `parser`, this is impossible to correctly handle.
I played around with the following:
```diff
diff --git a/lib/prism/translation/parser.rb b/lib/prism/translation/parser.rb
index 6b417be4..92525bd4 100644
--- a/lib/prism/translation/parser.rb
+++ b/lib/prism/translation/parser.rb
@@ -76,9 +76,9 @@ module Prism
-      def tokenize(source_buffer, recover = false)
+      def tokenize(source_buffer, recover = false, raw_source: source_buffer.source)
@source_buffer = source_buffer
-        source = source_buffer.source
+        source = raw_source
offset_cache = build_offset_cache(source)
result =
diff --git a/test/prism/ruby/parser_test.rb b/test/prism/ruby/parser_test.rb
index 0a2ca196..9df3c48e 100644
--- a/test/prism/ruby/parser_test.rb
+++ …
```
> Mark some parser translator tests as being known failures

- include/prism/defines.h
The previous value of 1_000 was added with [a reference to the Bison parser](https://www.gnu.org/software/bison/manual/html_node/Memory-Management.html), but the value of YYMAXDEPTH in the Bison docs is 10_000, not 1_000.
See https://github.com/ruby/prism/issues/1774#issuecomment-2593716858 cc @kddnewton
> Increase value of PRISM_DEPTH_MAXIMUM to 10000

- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/parser/lexer.rb
- test/prism/fixtures/heredocs_with_fake_newlines.txt
- test/prism/fixtures/strings.txt
- test/prism/lex_test.rb
- test/prism/ruby/parser_test.rb
- test/prism/ruby/ripper_test.rb
- test/prism/ruby/ruby_parser_test.rb
- test/prism/snapshots/heredocs_with_fake_newlines.txt
- test/prism/snapshots/strings.txt
Mostly around newlines and line continuation.
* percent arrays need special backslash handling in the ast
* Fix offset issue for heredocs with many line continuations (used wrong variable as index access)
* More refined rules on when to simplify string tokens
* Handle line continuations in squiggly heredocs
* Correctly dedent squiggly heredocs with interpolation
* Consider `':foo:` and `%s[foo]` to not be interpolation
Appologies for the amount of stuff
I sincerely hope this is the last of it for string handling. I'm not particularly proud of how this code evolved over the last PRs. It seems to handle a large chunk correctly and there are now an appropriate amount of tests so I might come back and try to clean it up a bit in the future.
https://github.com/ruby/prism/issues/2539 can now be …
> Further refine string handling in the parser translator

- test/prism/ruby/parser_test.rb
These are both affected by the same issue and I would argue that this is a parser bug. Either way, there is really no point to aligning these in my opinion.
> Move remaining parser translator ast failures to know failures

- lib/prism/translation/parser/compiler.rb
- test/prism/fixtures/begin_rescue.txt
- test/prism/snapshots/begin_rescue.txt
There are a few other locations that should be included in that check. I think the end location must always be present but I left the fallback in to be safe (maybe implicit begin somehow?)
> Fix parser translator rescue location with semicolon body

- lib/prism/translation/parser/compiler.rb
`builder.pair_label` is no good since it makes use of variables that the parser gem encountered. Since the prism translator doesn't keep proper track of that information, the following code interprets the implicit value as a local variable, even though it is not in scope:
```rb
def foo
bar = 123
end
{ bar: }
```
> Fix parser translator scope issues for implicit hash values

- src/prism.c
> Do not put empty statements in while because of -n

- src/prism.c
Expressions joined with `&&` are better asserted separately, so that it is clear from the failure message which expression is false.
Also, `unsigned long` may not be enough for `ptrdiff_t`, e.g., Windows.
Saying that `ptrdiff_t` can be larger than `SIZE_MAX` means that `PTRDIFF_MAX` is larger than `SIZE_MAX` and `ptrdiff_t` is sufficient to represent `SIZE_MAX`, otherwise if `PTRDIFF_MAX` is smaller than `SIZE_MAX`, `diff` will always be smaller than `SIZE_MAX` as well.
`diff` could be equal to `SIZE_MAX` only if `PTRDIFF_MAX` is equal to `SIZE_MAX` and these assertions would pass, but I don't think there is any platform where that is the case.
> Split assertion per expressions

- rust/ruby-prism-sys/build/main.rs
- rust/ruby-prism/src/lib.rs
This is useful, and easier than scanning through the entire comments list.
> [rust] add an API for accessing magic comments

- src/prism.c
- test/prism/errors/block_beginning_with_brace_and_ending_with_end.txt
When recovering from a depth error that occurs at the end of the file, we need to break out of parsing statements.
Fixes [Bug #21114]
> Fix infinite loop in error recovery

- src/util/pm_constant_pool.c
According to the calloc(3) man page, when nmemb or size is 0, `calloc()` can either return NULL or a unique pointer that can be passed to free(): https://manpages.org/calloc/3
While gcc (13.3.0) and clang (15.0.7), in my environment, return *a unique pointer* in this case, mruby's `mrb_calloc` returns *NULL*.
See https://github.com/mruby/mruby/blob/3.3.0/src/gc.c#L253
Since `pm_constant_pool_init()` is commonly called with capacity=0 during normal operation of Prism, `xcalloc()` needs to handle NULL returns to integrate with mruby.
Per free()'s and realloc()'s specifications, passing a NULL pointer is a valid operation, so this change should be safe.
> Allow xcalloc() to return NULL when size is 0 for portability

- lib/prism/translation/parser.rb
Follow-up to https://github.com/Shopify/ruby-lsp/pull/1849.
This is an extension of `Prism::Translation::Parser` to implement https://github.com/Shopify/ruby-lsp/pull/1849. It is based on the comments in https://github.com/Shopify/ruby-lsp/pull/1849#pullrequestreview-1966020868, but also adds a default argument for delegation to `Parser::Base` super class.
Using this API, https://github.com/rubocop/rubocop-ast/pull/359 has been implemented in RuboCop AST.
As detailed in https://github.com/rubocop/rubocop-ast/pull/359, this change is expected to improve performance by 1.3x for some source code.
Achieving a 1.3x speedup with such this simple modification is a significant improvement for Ruby LSP and its users.
cc @kddnewton @vinistock
> Support custom parser in `Prism::Translation::Parser`

- lib/prism/translation/parser.rb
- lib/prism/translation/parser/builder.rb
- prism.gemspec
- test/prism/ruby/parser_test.rb
I want to be able to add new node types to the parser translator, for example `itblock`. The bulk of the work is already done by prism itself. In the `parser` builder, this would be a 5-line change at most but we don't control that here.
Instead, we can add our own builder and either overwrite the few methods we need, or just inline the complete builder. I'm not sure yet which would be better.
`rubocop-ast` uses its own custom builder for `parser`. For this to correctly work with RuboCop, it must explicitly choose to extend the prism builder and use it, same as it currently chooses to use a different parser when prism is used: https://github.com/rubocop/rubocop-ast/blob/02b8d0faeeebc3ba6b5284c9e66569bbae836941/lib/rubocop/ast/processed_source.rb#L330
I'd like to enforce that the builder …
> Add a custom builder class for the parser translator

- lib/prism/translation/parser.rb
Caused by https://github.com/ruby/prism/pull/3478 and https://github.com/ruby/prism/pull/3443
I also made the builder reference more explicit to clearly distinquish between `::Parser` and `Prism::Translation::Parser`
> Fix merge mishap

- lib/prism/translation/parser.rb
This restores the missing method comments in https://github.com/ruby/prism/pull/3479.
> Restore a comment for `Prism::Translation::Parser#initialize`

- src/util/pm_strncasecmp.c
[[Bug #21161]](https://bugs.ruby-lang.org/issues/21161)
The `tolower` function provided by the libc is locale dependent and can behave in ways you wouldn't expect for some value of `LC_CTYPE`.
> Use a locale-insensitive version of tolower

- lib/prism/translation/parser/builder.rb
- lib/prism/translation/parser/compiler.rb
- test/prism/ruby/parser_test.rb
`itblock` node is added to support the `it` block parameter syntax introduced in Ruby 3.4.
```console
$ ruby -Ilib -rprism -rprism/translation/parser34 -e 'buffer = Parser::Source::Buffer.new("path"); buffer.source = "proc { it }"; \
p Prism::Translation::Parser34.new.tokenize(buffer)[0]'
s(:itblock,
s(:send, nil, :proc), :it,
s(:lvar, :it))
```
This node design is similar to the `numblock` node, which was introduced for the numbered parameter syntax in Ruby 2.7.
```
$ ruby -Ilib -rprism -rprism/translation/parser34 -e 'buffer = Parser::Source::Buffer.new("path"); buffer.source = "proc { _1 }"; \
p Prism::Translation::Parser34.new.tokenize(buffer)[0]'
s(:numblock,
s(:send, nil, :proc), 1,
s(:lvar, :_1))
```
The difference is that while numbered parameters can have multiple parameters, the …
> Support `itblock` for `Prism::Translation::Parser`

- lib/prism/translation/parser/compiler.rb
Temoprary backwards-compat code so that current users don't break. I noticed this by accident while doing some testing
Eventually the `Translation::Parser` initializer should asser that the correct class is passed in. I would start with a warning after https://github.com/rubocop/rubocop-ast/pull/354 is merged and released.
cc @koic
> Ensure backwards compatibility with the custom parser builder

- lib/prism/translation/parser/lexer.rb
I ran it over the RuboCop codebase. Here are some numbers:
Before:
```
hyperfine -w 2 -r 10 "bundle exec ruby test.rb"
Benchmark 1: bundle exec ruby test.rb
Time (mean ± σ):     24.055 s ±  0.410 s    [User: 23.661 s, System: 0.305 s]
Range (min … max):   23.464 s … 24.610 s    10 runs
```
After:
```
$ hyperfine -w 2 -r 10 "bundle exec ruby test.rb"
Benchmark 1: bundle exec ruby test.rb
Time (mean ± σ):     21.464 s ±  0.447 s    [User: 21.156 s, System: 0.220 s]
Range (min … max):   20.888 s … 22.240 s    10 runs
```
So, about 11% faster just with this. The majority of the time is still spent translating, only ~10% is actually spend by prism parsing/lexing it.
Benchmark file:
```rb
require "prism"
require "prism/translation/parser"
Dir.glob("../rubocop/**/*.rb").each do
buffer = …
```
> Trivial parser translator optimizations

- config.yml
- src/prism.c
- test/prism/snapshots/break.txt
- test/prism/snapshots/methods.txt
- test/prism/snapshots/next.txt
- test/prism/snapshots/nils.txt
- test/prism/snapshots/return.txt
- test/prism/snapshots/unparser/corpus/literal/def.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/variables.txt
- test/prism/snapshots/whitequark/cond_begin_masgn.txt
- test/prism/snapshots/whitequark/ruby_bug_19281.txt
This can get triggered even if the list of statements only contains a single statement. This is necessary to properly support compiling
```ruby
defined? (;a)
defined? (a;)
```
as "expression". Previously these were parsed as statements lists with single statements in them.
> Add a multiple statements flag to parentheses

- config.yml
- src/prism.c
- test/prism/errors/xstring_concat.txt
Fixes https://github.com/ruby/prism/issues/3497
> Make xstrings concat syntax error

- lib/prism.rb
- lib/prism/node_ext.rb
- lib/prism/polyfill/warn.rb
- lib/prism/translation/parser.rb
- prism.gemspec
- test/prism/ruby/parser_test.rb
- test/prism/test_helper.rb
In https://github.com/ruby/prism/pull/3494 I added a bit of code so that using the new builder doesn't break stuff. This code can be dropped when it is enforced that builder is _always_ the correct subclass (and makes future issues like that unlikely).
> Warn when the parser translator receives an incompatible builder class

- sig/prism/dispatcher.rbs
- templates/lib/prism/dispatcher.rb.erb
- test/prism/ruby/dispatcher_test.rb
> [!NOTE]
> This draft PR is a companion to https://github.com/Shopify/ruby-lsp/pull/3291, which proposes this approach. Tests and other things have been omitted for now in the interest of getting feedback on the approach first, and will be added if we decide to move forward.
Instead of requiring the consumer to provide a list of all events which they wish to handle, we can give them to option of dynamically detecting them, by scanning the listener's public methods.
This approach is similar to that used by Minitest (scanning for `test_` methods) and Rails generators (running all public methods in the order they are defined).
While this is slower than specifying a hard coded list, the penalty is only during registration. There is no change the the behaviour of dispatching the events. It is …
>  Dynamically register events to dispatch

- docs/parser_translation.md
- lib/prism/translation.rb
- lib/prism/translation/parser_current.rb
- prism.gemspec
- test/prism/ruby/parser_test.rb
It's not my favorite api but for users that currently use the same thing from `parser`, moving over is more difficult
than it needs to be.
If you plan to support both old and new ruby versions, you definitly need to branch somewhere on the ruby version
to either choose prism or parser.
But with prism you then need to enumerate all the versions again and choose the correct one.
Also, don't recommend to use `Prism::Translation::Parser` in docs. It's version-less but actually always just uses Ruby 3.4 which is probably not what the user intended.
Note: parser also warns when the patch version doesn't match what it expects. But I don't think prism has such a concept, and anyways it would require releases anytime ruby releases, which I don't think is very desirable.
I wrote something on how to …
> Add `Prism::Translation::ParserCurrent`

- lib/prism/translation/parser_current.rb
There will be a bunch of other problems should 3.10 ever exists, but I guess why not fix this one now.
> Don't use `RUBY_VERSION.to_f`

- Gemfile.lock
- gemfiles/2.7/Gemfile.lock
- gemfiles/3.0/Gemfile.lock
- gemfiles/3.1/Gemfile.lock
- gemfiles/3.2/Gemfile.lock
- gemfiles/3.3/Gemfile.lock
- gemfiles/3.4/Gemfile.lock
- gemfiles/3.5/Gemfile.lock
- gemfiles/jruby/Gemfile.lock
- gemfiles/truffleruby/Gemfile.lock
- gemfiles/typecheck/Gemfile.lock
- lib/prism/translation/parser.rb
There hasn't been much that would actually affect parsers usage of it. But, when adding new node types, these usually appear in the `Parser::Meta::NODE_TYPES`.
`itblock` was added, gets emitted by prism, and then `rubocop-ast` blindly delegates to `on_itblock`. These methods are dynamically created through `NODE_TYPES`, which means that it will error if it doesn't contain `itblock`. Ref https://github.com/rubocop/rubocop-ast/issues/366
This is unfortunate because in `rubocop-ast` these methods are eagerly defined but the prism translator is lazily loaded on demand.
The simplest solution is to add them on the `parser` side (even if they are not emitted directly), and require that a version that contains those be used.
In summary when adding a new node type:
* Add it to …
> Enforce a minimum `parser` version for the parser translator

- rust/ruby-prism/build.rs
- rust/ruby-prism/src/lib.rs
Hi!
This PR fixes undefined behavior caused by passing a NULL pointer to `std::slice::from_raw_parts` which manifests in the following test:
```rust
#[test]
fn regex_value_test() {
let result = parse(b"//");
let node = result.node().as_program_node().unwrap().statements().body().iter().next().unwrap().as_regular_expression_node().unwrap();
assert_eq!(node.unescaped(), b"");
}
```
with the following error:
```
running 1 test
thread 'tests::regex_value_test' panicked at core/src/panicking.rs:223:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
error: test …
```
> fix(rust): ub on empty slices

- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/parser/lexer.rb
- snapshots/patterns.txt
- test/prism/fixtures/patterns.txt
- test/prism/ruby/parser_test.rb
Closes #3527
`StringNode` and `SymbolNode` don't have the same shape (`content` vs `value`) and that wasn't handled.
I believe the logic for the common case can be reused. I simply left the special handling for implicit nodes in pattern matching and fall through otherwise.
NOTE: patterns.txt is not actually tested at the moment, because it contains syntax that `parser` mistakenly rejects. But I checked manually that this doesn't introduce other failures. https://github.com/whitequark/parser/pull/1060
> Fix parser translator when pinning hash with string keys

- src/prism.c
This was just a tiny oversight from #2796.
This PR is functionally equivalent unless you're using a custom allocator (`PRISM_XALLOCATOR`). See #2542
> Use `xmalloc()`/`xfree()`

- java-wasm/pom.xml
- java-wasm/src/main/java-templates/org/prism/WasmResource.java
- java-wasm/src/main/java/org/prism/Prism.java
- java-wasm/src/test/java/org/prism/DummyTest.java
Tightening up the Java Wasm integration.
Here we are using `WasmModuleInterface` to generate an easy to use API(it's generated on the fly you need to compile the project to actually see it) out of Prism.
After this PR gets merged we are ready to publish to Maven Central a self contained package of about ~550Kb that can be used as a direct dependency from Java projects.
To do it I'll need a bit of guidance (choosing maintainers/links/licensing etc. in the `pom.xml`), I can start by opening a WIP PR and I can work together with a maintainer to bring it home if that's something you would like to pursue.
Alternatively I'd like to ask permission to publish from an organization I own.
> Java prism finalization

- .github/workflows/cruby-bindings.yml
- .github/workflows/main.yml
We experienced failures due to the GH brownout, this should be the fix. ( cc. @enebo )
> Bump deprecated Ubuntu runners

- lib/prism/translation/parser/compiler.rb
- snapshots/patterns.txt
- test/prism/fixtures/patterns.txt
Fixes https://github.com/rubocop/rubocop/issues/14056 because it ends up treating it as a local variable, and `a.x` is not a valid local variable name.
I'm not big on pattern matching, but conceptually it makes sense to me to treat anything inside ^() to not be
pattern matching syntax?
> Fix parser translator when splatting in pattern matching pin

- Gemfile.lock
- gemfiles/2.7/Gemfile.lock
- gemfiles/3.0/Gemfile.lock
- gemfiles/3.1/Gemfile.lock
- gemfiles/3.2/Gemfile.lock
- gemfiles/3.3/Gemfile.lock
- gemfiles/3.4/Gemfile.lock
- gemfiles/3.5/Gemfile.lock
- gemfiles/jruby/Gemfile.lock
- gemfiles/truffleruby/Gemfile.lock
- gemfiles/typecheck/Gemfile.lock
- test/prism/ruby/parser_test.rb
It also updates to latest `parser`, which allows numbered parameters in pattern matching pin, passing `patterns.txt` and `case.txt`.
This threw me off in my last two PRs because the tests seemed to just pass. Turns out, it just wasn't doing anything.
> Be explicit in tests which files `parser` can't parse

- java-wasm/src/main/java/org/prism/Prism.java
JRuby internally uses loader differently and also encodes options differently.
Also added MemoryPages options since in testing one file complained about memory usage.
Lastly, original method was making a String from bytes so allow serialize to accept bytes and
sourceLength since sometimes you have source smaller than the byte[] backing store.
> [java-wasm] Allow serialize to be called separately from serializeParse.

- rust/ruby-prism/src/lib.rs
This PR adds `Integer::to_u32_digits`, which is similar to [BigInt::to_u32_digits](https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#method.to_u32_digits) from the `num_bigint` crate, except it does not allocate a vector for digits and returns a boolean for the sign part to be more in line with the current set of types in the `prism` crate.
The main benefit of this change is that it allows for almost direct construction of `BigInt`
> feat(rust): add `Integer::to_u32_digits`

- lib/prism/translation/parser/compiler.rb
- snapshots/rescue.txt
- test/prism/fixtures/rescue.txt
Prism is unable to traverse the tree when using the translation parser
Given this code
```ruby
begin
raise '42'
rescue => A[]
end
```
Prism fails with this backtrace
```
Error: test_unparser/corpus/literal/rescue.txt(Prism::ParserTest): NoMethodError: undefined method `arguments' for nil
prism/lib/prism/translation/parser/compiler.rb:1055:in `visit_index_target_node'
prism/lib/prism/node.rb:9636:in `accept'
prism/lib/prism/compiler.rb:30:in `visit'
prism/lib/prism/translation/parser/compiler.rb:218:in `visit_begin_node'
```
Seems like
```diff
-            visit_all(node.arguments.arguments),
+            visit_all(node.arguments&.arguments || []),
```
fixes the problem; however, I'm not sure where to place this test.
An MRE:
```bash
$ cat /tmp/prism.rb
ruby = <<~RUBY
begin
raise '42' …
```
> Fix visiting the AST (using translation parser) when there's a rescued via indexed assignment exception

- templates/lib/prism/compiler.rb.erb
- templates/lib/prism/visitor.rb.erb
The current implementation of the visitor pattern in Prism uses a single method (`visit_child_nodes`) to handle all node types. This can lead to performance issues since the `node` argument will end up being polymorphic, and will prevent effective use of inline caches, which in CRuby are monomorphic.
This commit generates an inlined version of the previous code for each node type, thus making the calls inside visitor methods monomorphic. This should improve performance, especially in cases where the visitor is called frequently.
Thanks to @tenderlove for finding that this was slower than it needed to be.
Benchmark results:
```
❯ ruby bench.rb
ruby 3.4.3 (2025-04-14 revision d0b7e5b6a0) +PRISM [arm64-darwin20]
Warming up --------------------------------------
vanilla     1.000 i/100ms …
```
> Monomorphise visitor methods

- bin/prism
I built this for myself, and found it really useful for faster debugging.
Example usage:
```
$ bin/prism repl
Prism> 1
@ IntegerNode (location: (1,0)-(1,1))
├── flags: newline, static_literal, decimal
└── value: 1
Prism> 1 +
#<Prism::ParseError @type=:expect_expression_after_operator @message="unexpected end-of-input; expected an expression after the operator" @location=#<Prism::Location @start_offset=3 @length=0 start_line=1> @level=:syntax>
#<Prism::ParseError @type=:unexpected_token_close_context @message="unexpected end-of-input, assuming it is closing the parent top level context" @location=#<Prism::Location @start_offset=3 @length=0 start_line=1> @level=:syntax>
@ CallNode (location: (1,0)-(1,3))
├── flags: newline
├── receiver:
│   @ IntegerNode (location: (1,0)-(1,1))
│   ├── …
```
> Add `repl` sub-command

- test/prism/lex_test.rb
> [DOC] Fix a typo in comment

- lib/prism/translation/parser/lexer.rb
- snapshots/strings.txt
- test/prism/fixtures/strings.txt
https://docs.ruby-lang.org/en/master/syntax/literals_rdoc.html#label-25w+and+-25W-3A+String-Array+Literals
> %W allow escape sequences described in Escape Sequences. However the continuation line <newline> is not usable because it is interpreted as the escaped newline described above.
> Fix parser translator with trailing backslash in `%W` /`%I` array

- docs/parser_translation.md
I wrote something up on how to use both if you need to also parse older ruby versions. https://github.com/whitequark/parser/blob/master/doc/PRISM_TRANSLATION.md
> Mention the prism/parser guide from the `parser` gem

- snapshots/endless_methods.txt
- src/prism.c
- test/prism/fixtures/endless_methods.txt
Previously, endless method definitions like `x = def f = p 1` would fail to parse because command calls (method calls without parentheses) were only accepted when the surrounding binding power was less than `PM_BINDING_POWER_COMPOSITION` (8). In assignment contexts with binding power 18, this condition was false, causing parse errors.
This fix ensures command calls are always accepted in endless method bodies by passing `true` for `accepts_command_call`, making the method body parse consistently regardless of where the method is defined.
Fixes #3473
> Allow command calls in endless method bodies regardless of context

- docs/parser_translation.md
Since rubocop 1.75 it just does the right thing, so no need to mention much of the old configuration anymore. See https://github.com/rubocop/rubocop/pull/14035
I'm also open to removing this section entirely, I don't think it provides much value anymore.
> [docs] RuboCop now uses prism as a first-class (translation) parser

- .github/workflows/cruby-bindings.yml
This should prevent Prism from breaking CRuby's CI.
> Add more Prism related tests to cruby-bindings workflow

- include/prism/options.h
- java/org/prism/ParsingOptions.java
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- src/options.c
- src/prism.c
This makes it hard to do version checks against this value. The current version checks work because there are so few possible values, and they are exclusively `!=/`==` checks.
As an example, https://github.com/ruby/prism/pull/3337 introduces new syntax for ruby 3.5 and uses `PM_OPTIONS_VERSION_LATEST` as its version guard. Because what is considered the latest changes every year, it must later be changed to `parser->version == parser->version == PM_OPTIONS_VERSION_CRUBY_3_5 || parser->version == PM_OPTIONS_VERSION_LATEST`, with one extra version each year.
With this change, the PR can instead write `parser->version >= PM_OPTIONS_VERSION_CRUBY_3_5` which is self-explanatory and works for future versions.
> Do not use `0` to indicate the latest ruby version to parse

- snapshots/endless_methods.txt
- src/prism.c
- test/prism/errors/private_endless_method.txt
- test/prism/fixtures/endless_methods.txt
(This is another attempt to solve https://github.com/ruby/prism/issues/3473 as #3598 caused `ruby/ruby` tests to fail and got reverted)
Previously, endless method definitions in assignment contexts like `x = def f = p 1` would fail to parse because command calls (method calls without parentheses) were only accepted when the surrounding binding power was less than `PM_BINDING_POWER_COMPOSITION`.
This fix specifically checks for assignment context and allows command calls in those cases while maintaining the existing behavior for other contexts. This ensures that:
- `x = def f = p 1` parses correctly (previously failed)
- `private def f = puts "Hello"` still produces the expected error
> Allow command calls in endless method bodies within assignments

- ext/prism/extension.c
- include/prism.h
- lib/prism/ffi.rb
- src/prism.c
Checking the return value of `fgets` isn't good enough to determine whether the input stream has reached EOF or not.  `fgets` could have run in to an error and returned NULL.  Additionally, we can't just check the buffer contents for `\n` because `fgets` could have read the maximum buffer size (which may not have ended with a `\n`).
I want to use this callback to implement a fix for:
https://bugs.ruby-lang.org/issues/21188
> Add an `feof` callback to Prism stream parsing

- rakelib/lex.rake
`block.call(queue.shift) until queue.empty?` isn't thread safe.
If there is one element left in the queue, two or more thread may see `queue.empty?` return `false` and call the blocking `shift` ending in a deadlock.
The proper way to synchronize threads with a queue is to close the queue once no more elements need to be added.
This should fix the occasional `fatal: No live threads left. Deadlock? (fatal)` failures on CI. e.g. https://github.com/ruby/prism/actions/runs/17697479732/job/50298732002?pr=3644#step:5:43
> Fix race condition in `rake parse:topgems`

- gemfiles/truffleruby/Gemfile
- gemfiles/truffleruby/Gemfile.lock
Truffleruby 25 got released yesterday.
https://github.com/oracle/truffleruby/releases/tag/graal-25.0.0
> Fix truffleruby CI

- config.yml
I was looking for what to call the thing based to the case keyword.
Is this change correct?
The `case` keyword gets marked below under `case_keyword_loc`.
> Fix example marker for case statement predicate

- README.md
[Unparser](https://github.com/mbj/unparser) now uses Prism (if available) via Parser translator.
> Add `unparser` into README library examples

- .github/workflows/main.yml
This PR is just a small refactoring in the CI's build-ibm job to use the `$(nproc)` instead of hard-coded number `2`. I noticed this was better, and applied it on ruby/openssl repository. So, I want to apply the change to this ruby/prism repository.
https://github.com/ruby/openssl/pull/946/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R44
> CI: build-ibm: Use nproc instead of hard-coded number 2.
