- src/yarp.c
- test/parse_test.rb
> Fix method call equals parsing

- test/parse_test.rb
Tiny follow up for a test I missed.
> Add test for parentheses with multiple statements

- config.yml
- src/yarp.c
- test/parse_test.rb
> Embedded variables

- config.yml
- src/parser.h
- src/yarp.c
- test/parse_test.rb
Please let me know if tree should be different 🙂
Closes #141.
> Rescue keyword

- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
closes: https://github.com/Shopify/yarp/issues/162
> Add support for argument forwarding method calls

- src/yarp.c
- test/parse_test.rb
> Add support for `#[]` and `#[]=` calls

- src/yarp.c
- test/parse_test.rb
> Method calls without parentheses

- src/yarp.c
At the moment we've been passing around a pointer to the token that we want to set to not provided. Instead, let's just return the struct as a whole. Also, the bounds of the unprovided token don't really do anything, so let's stop calculating them.
> not_provided returning a struct

- bin/templates/src/node.c.erb
- ext/yarp/extension.c
- src/util/yp_string.c
- src/util/yp_string.h
- src/yarp.h
- test/memsize_test.rb
> Track memsize

- config.yml
- src/yarp.c
- test/errors_test.rb
- test/parse_test.rb
Closes #148. Please let me know if there are some scenarios missing (or we can add them later)
> Operator arguments

- src/parser.h
- src/yarp.c
- test/parse_test.rb
Heredocs can now accept single quotes, double quotes, and xstring
Closes #295
> Added quotation parsing on heredocs

- .gitignore
- src/parser.h
- src/yarp.c
- test/parse_test.rb
> Implemented dash heredocs

- src/yarp.c
> Only accept newlines in calls, not commands

- src/yarp.c
We should be checking if it's possible to have a label before we check if the identifier is a keyword. This more closely matches CRuby and gets us a couple more files closer.
> Some small label fixes

- Rakefile
- src/yarp.c
- test/parse_test.rb
Also make rake lex skip files with parse errors.
> Handle parsing aset with a multiple assignment

- src/yarp.c
- test/parse_test.rb
Fixes #402.
Please let me know if I miss something.
> Fix parsing empty %w list

- src/yarp.c
- test/parse_test.rb
> Splats on return, next, and break

- src/yarp.c
- test/parse_test.rb
We were passing the wrong lex mode pointer.
Closes #398
> Symbols with immediate interpolation

- src/yarp.c
- test/parse_test.rb
> Bare hashes in arrays

- src/yarp.c
* `def foo((bar,))`
* `def foo((bar, *, baz))`
* `def foo((bar, *baz))`
Closes #394
> Enhancements to destructured parameters

- config.yml
- lib/yarp.rb
- src/yarp.c
- test/parse_test.rb
> Delineate between [ for args and [ for arrays

- config.yml
- src/yarp.c
- test/parse_test.rb
> Predicate-less case statements

- src/parser.h
- src/yarp.c
Do this by pushing a new context when parsing method params and checking it in the lexer.
Closes #383.
> Fix ... state inside method params

- src/yarp.c
> Reuse parse_string_part for dynamic symbols

- src/yarp.c
- test/parse_test.rb
> when clauses with splat node

- src/yarp.c
Give a name to assignment binding powers and prefix everything with YP_ just to be consistent.
> Clean up binding powers

- src/yarp.c
- test/parse_test.rb
> Starred values

- config.yml
- src/yarp.c
- test/parse_test.rb
> Handle splats on rescues

- src/yarp.c
- test/errors_test.rb
There are a lot of places where we parse hashes, and the logic is very intermingled. This refactors it into one place and hopefully elucidates what's going on.
> Refactor the way we parse hashes

- Rakefile
- src/yarp.c
- targets.yml
Also, enhancements to `rake lex`, which will now warn you if there's a file that you've fixed that is still listed as `TODO`.
> [] should allow do blocks to be accepted

- Rakefile
- config.yml
- lib/yarp/lex_compat.rb
- src/yarp.c
- targets.yml
- test/location_test.rb
Delineate between `foo(bar)` and `foo (bar), baz`
> Parentheses

- bin/templates/src/util/yp_strspn.c.erb
- src/util/yp_strspn.h
- src/yarp.c
@eregon this should fix the failures you were seeing. Thanks for the repro branch!
> Do not read anything off the end

- src/yarp.c
- targets.yml
> Fix escaping non-special characters in character literal

- src/yarp.c
- test/fixtures/blocks.rb
- test/fixtures/method_calls.rb
- test/snapshots/blocks.rb
- test/snapshots/method_calls.rb
> Fix parsing method calls with constant paths

- src/unescape.c
- src/unescape.h
- targets.yml
> Unescape errors

- config.yml
- lib/yarp/lex_compat.rb
- src/yarp.c
- targets.yml
- test/errors_test.rb
- test/snapshots/case.rb
- test/snapshots/method_calls.rb
- test/snapshots/methods.rb
- test/snapshots/procs.rb
- test/snapshots/rescue.rb
- test/snapshots/return.rb
- test/snapshots/variables.rb
> Split up * and unary *

- bin/templates/lib/yarp/node.rb.erb
- test/errors_test.rb
- test/parse_test.rb
- test/test_helper.rb
> Remove Node#==

- src/yarp.c
- targets.yml
* Properly lex method name when operator
* Handle segfaults for identifiers followed by parentheses
* Accept newlines in ternaries
> More stuff

- src/unescape.c
Just code formatting for unescape.c file.
> Convert tabs to spaces in unescape.c

- bin/templates/src/util/yp_strspn.c.erb
- config.yml
Changes:
- fixed typos
- added two examples for CallNode in `config.yml`
> Fix typos in comments

- src/yarp.c
> Fix `parse_alias_argument`

- bin/templates/include/yarp/ast.h.erb
- config.yml
- src/yarp.c
> Migrate `AlternationPatternNode`

- bin/template.rb
- bin/templates/ext/yarp/node.c.erb
- bin/templates/include/yarp/ast.h.erb
- bin/templates/src/node.c.erb
- bin/templates/src/prettyprint.c.erb
- bin/templates/src/serialize.c.erb
- config.yml
- src/yarp.c
Related #675
@kddnewton I think this node makes a good example of the effect of returning a specific node type from the `create` functions. I don't have a strong opinion but it looks like we're gonna need more casts.
> Migrate arguments node

- config.yml
- src/yarp.c
> Migrate `ArrayNode`

- bin/templates/src/node.c.erb
- bin/templates/src/prettyprint.c.erb
- bin/templates/src/serialize.c.erb
- config.yml
- src/yarp.c
> Migrate `BeginNode`

- config.yml
- src/yarp.c
> Migrate `ElseNode`

- config.yml
- src/yarp.c
> Migrate `DefinedNode`

- config.yml
- src/yarp.c
> Migrate `EnsureNode`

- config.yml
- src/yarp.c
* Symbol
* Super
* String
* StringInterpolated
* StringConcat
> Migrate more

- config.yml
- src/yarp.c
> Migrate `BlockArgumentNode`, `BlockNode`, `BlockParameterNode`

- src/yarp.c
It feels like it is handier just to cast to `yp_node_t*` instead of using the special macros. So this PR removes them.
> Remove casting macros

- config.yml
- src/yarp.c
> Migrate `KeywordParameterNode`, `KeywordRestParameterNode`, `LambdaNode`

- config.yml
- src/yarp.c
> Migrate `FindPatternNode`

- config.yml
- src/yarp.c
> Migrate `GlobalVariableReadNode`, `GlobalVariableWriteNode`

- config.yml
- src/yarp.c
> Migrate `IfNode`

- config.yml
- src/yarp.c
> Migrate `IntegerNode`

- bin/templates/src/prettyprint.c.erb
- config.yml
- src/yarp.c
> Migrate `CallNode`

- config.yml
- src/yarp.c
> Migrate `InterpolatedRegularExpressionNode`, `InterpolatedStringNode`, `InterpolatedSymbolNode`, `InterpolatedXStringNode`

- config.yml
- src/yarp.c
> Migrate `ConstantReadNode`, `ConstantPathWriteNode`

- config.yml
- src/yarp.c
> Migrate `HashNode`

- src/yarp.c
Similar to `yp_accepts_block_stack_push`, `yp_accepts_block_stack_pop`, etc.
> Move do-loop stack manipulations into own functions

- lib/yarp/lex_compat.rb
- test/fixtures/tilde_heredocs.rb
- test/snapshots/tilde_heredocs.rb
> Fix column alignment for squiggly heredoc on Ruby layer

- .github/workflows/main.yml
- Rakefile
- src/yarp.c
> Add a CI run with assertions off

- .github/workflows/main.yml
@jemmaissroff Could you change the required CI jobs since it's now `build (ubuntu-latest)` instead of `build`?
> Test the build on macOS in CI

- src/regexp.c
- src/unescape.c
- src/yarp.c
Just formatting some code to make the indentation consistent.
> Format the code

- src/yarp.c
- test/fixtures/method_calls.rb
- test/snapshots/method_calls.rb
> Fix parsing calls with blocks inside conditionals

- src/yarp.c
- test/encoding_test.rb
this adds support for cp125{1,2} and extended utf-8 formats
> improve encoding comment support

- src/yarp.c
This PR fixes:
1. possible null reference access in `yp_else_node_create`
2. unused variable `ignored_newline_type`
3. possible memory leaks in `parse_pattern_primitives` and `parse_expression_prefix`
> Fix some clang analyzer problems 

- src/yarp.c
- tasks/lex.rake
- tasks/top-100-gems.yml
- test/fixtures/rescue.rb
- test/snapshots/rescue.rb
- test/snapshots/seattlerb/bug_op_asgn_rescue.rb
- test/snapshots/seattlerb/defn_endless_command_rescue.rb
- test/snapshots/seattlerb/defs_endless_command_rescue.rb
- test/snapshots/seattlerb/lasgn_arg_rescue_arg.rb
- test/snapshots/seattlerb/lasgn_call_bracket_rescue_arg.rb
- test/snapshots/seattlerb/lasgn_call_nobracket_rescue_arg.rb
- test/snapshots/seattlerb/mlhs_rescue.rb
- test/snapshots/whitequark/endless_method_command_syntax.rb
- test/snapshots/whitequark/rescue_mod_asgn.rb
- test/snapshots/whitequark/rescue_mod_masgn.rb
- test/snapshots/whitequark/rescue_mod_op_assign.rb
- test/snapshots/whitequark/ruby_bug_12402.rb
> Fix rescue modifier

- src/yarp.c
- test/fixtures/patterns.rb
- test/snapshots/patterns.rb
> Fix patterns in conditional predicates

- src/yarp.c
- test/fixtures/if.rb
- test/fixtures/rescue.rb
- test/snapshots/if.rb
- test/snapshots/rescue.rb
> Added else, rescue as valid expr begins

- src/yarp.c
- test/fixtures/if.rb
- test/snapshots/if.rb
> Fix pattern matching in elsif predicate

- src/yarp.c
- test/fixtures/ternary_operator.rb
- test/snapshots/ternary_operator.rb
> Lex spaceless squished ternary correctly

- src/yarp.c
- test/location_test.rb
- test/snapshots/alias.rb
- test/snapshots/patterns.rb
- test/snapshots/seattlerb/dstr_evstr_empty_end.rb
- test/snapshots/seattlerb/dsym_esc_to_sym.rb
- test/snapshots/seattlerb/dsym_to_sym.rb
- test/snapshots/seattlerb/qsymbols_interp.rb
- test/snapshots/seattlerb/symbol_list.rb
- test/snapshots/symbols.rb
- test/snapshots/undef.rb
- test/snapshots/unparser/corpus/literal/literal.rb
- test/snapshots/whitequark/array_symbols_interp.rb
- test/snapshots/whitequark/interp_digit_var.rb
- test/snapshots/whitequark/parser_slash_slash_n_escaping_in_literals.rb
- test/snapshots/whitequark/symbol_interp.rb
- test/snapshots/whitequark/undef.rb
> Fix location for `InterpolatedSymbolNode`

- src/yarp.c
- test/location_test.rb
- test/snapshots/dash_heredocs.rb
- test/snapshots/seattlerb/backticks_interpolation_line.rb
- test/snapshots/unparser/corpus/literal/literal.rb
- test/snapshots/whitequark/dedenting_heredoc.rb
- test/snapshots/whitequark/heredoc.rb
- test/snapshots/whitequark/interp_digit_var.rb
- test/snapshots/whitequark/parser_slash_slash_n_escaping_in_literals.rb
- test/snapshots/whitequark/xstring_interp.rb
- test/snapshots/xstring.rb
> Fix location for `InterpolatedXStringNode`

- bin/templates/src/node.c.erb
- include/yarp/node.h
- src/yarp.c
- Change the implementation of `yp_node_list_append` with `yp_node_list_append2`
- Remove `yp_node_list_append2`
- Replace calls to `yp_node_list_append2` with `yp_node_list_append`
> Replace `yp_node_list_append2` with `yp_node_list_append`

- lib/yarp/lex_compat.rb
> Assert we don't lose tokens when performing lex_compat

- src/yarp.c
- test/errors_test.rb
- test/fixtures/methods.rb
- test/snapshots/methods.rb
- test/snapshots/whitequark/arg_duplicate_ignored.rb
> Check argument names for duplication

- .github/workflows/package-vscode.yml
- lib/yarp/language_server.rb
- vscode/README.md
- vscode/package.json
- vscode/src/extension.ts
> Reflect Shopify/yarp -> ruby/yarp changes

- .github/workflows/main.yml
- .github/workflows/truffleruby.yml
- ext/yarp/compile.c
- lib/yarp.rb
- src/yarp.c
- test/compile_test.rb
- test/snapshots/seattlerb/case_in.rb
- test/snapshots/seattlerb/case_in_hash_pat_assign.rb
- test/snapshots/seattlerb/parse_pattern_058.rb
- test/snapshots/seattlerb/parse_pattern_058_2.rb
- test/snapshots/unparser/corpus/literal/pattern.rb
- test/snapshots/whitequark/multiple_pattern_matches.rb
- test/snapshots/whitequark/newline_in_hash_argument.rb
This PR has 3 commits which fix separate issues from bumping to run against Ruby head, and then one final commit which bumps our GitHub CI to run against Ruby head. This is all in preparation for mirroring to ruby/ruby
> Fixing 3.3 errors

- bin/templates/include/yarp/ast.h.erb
- bin/templates/java/org/yarp/Nodes.java.erb
- bin/templates/lib/yarp/node.rb.erb
- config.yml
- src/yarp.c
The generated code is like this:
```java
public static final class RegularExpressionFlags implements Comparable<RegularExpressionFlags> {
public static final int IGNORECASE = 1 << 0;
public static final int MULTILINE = 1 << 1;
public static final int EXTEND = 1 << 2;
public static final int EUCJP = 1 << 3;
public static final int ASCII8BIT = 1 << 4;
public static final int WINDOWS31J = 1 << 5;
public static final int UTF8 = 1 << 6;
public static final int ONCE = 1 << 7;
public static boolean isIgnoreCase(int flags) {
return (flags & IGNORECASE) != 0;
}
public static boolean isMultiLine(int flags) {
return (flags & MULTILINE) != 0;
}
public static boolean isExtend(int flags) {
return (flags & EXTEND) != 0;
}
public static boolean isEUCJP(int flags) {
return (flags & EUCJP) != 0;
}
public …
```
> Generate a Java class for the flags for convenience

- Rakefile
Fix for https://github.com/ruby/yarp/pull/952/files#diff-ee98e028c59b193d58fde56ab4daf54d43c486ae674e63d50ddf300b07943e0f
> Fix logic for libraries extensions in Rakefile

- CONTRIBUTING.md
- Rakefile
- tasks/test.rake
`test:gdb` and `test:lldb` run the test suite under those debuggers
Also update CONTRIBUTING.md with a note on the debugging tasks.
> Add `test:gdb` and `test:lldb` rake tasks

- include/yarp/parser.h
- src/yarp.c
Consolidates the places where we push lex modes and also pre-computes the breakpoints for yp_strpbrk since they don't change between tokens.
> Lex mode updates

- src/regexp.c
> Don't read past the end of input parsing regex group

- .gitignore
- src/regexp.c
Fixes #1056 
Thanks @stevenjohnstone!!
> Fix infinite loop while parsing regexp comments

- Rakefile
Fixes https://github.com/ruby/yarp/issues/1080
> Clean .o files on `rake clobber`

- src/yarp.c
> Fix overflow reads with heredoc identifier

- src/unescape.c
> Handle bad input for ascii printable

- ext/yarp/extension.c
- include/yarp.h
- include/yarp/unescape.h
- include/yarp/util/yp_memchr.h
- src/unescape.c
- src/util/yp_memchr.c
- src/yarp.c
> Encoding-aware memchr

- ext/yarp/extension.c
- ext/yarp/extension.h
> Use demand paging on windows

- src/yarp.c
> Prevent strncmp/strncasecmp reading oob

- src/yarp.c
> Fix two memory leaks.

- bin/insns
- config.yml
- templates/java/org/yarp/Loader.java.erb
- templates/java/org/yarp/Nodes.java.erb
- templates/template.rb
For https://github.com/ruby/yarp/issues/1099, useful until YARP provides this information in C struct and/or in the serialized form.
> Set newline flag for Java nodes by walking the AST after deserialization

- bin/parse
- config.yml
- java/org/yarp/MarkNewlinesVisitor.java
- lib/yarp.rb
- tasks/check_manifest.rake
- templates/java/org/yarp/Loader.java.erb
- templates/java/org/yarp/Nodes.java.erb
- templates/lib/yarp/node.rb.erb
- templates/template.rb
- test/parse_test.rb
* These 3 places is what the CRuby and JRuby parser use.
> Set newline flag using a visitor for both Ruby and Java nodes

- ext/yarp/extension.c
- test/comments_test.rb
- test/errors_test.rb
Fixes https://github.com/ruby/yarp/issues/1167
> Fix locations for comments, warnings, and errors

- src/yarp.c
> Handle pound terminator in isolation

- Rakefile
- ext/yarp/extension.c
- ext/yarp/extension.h
- include/yarp/unescape.h
- include/yarp/util/yp_string.h
- src/unescape.c
- src/util/yp_string.c
- src/yarp.c
- test/newline_test.rb
* So it can be shared by the various users of librubyparser.
* Needed for https://github.com/ruby/yarp/pull/1112
> Move unescape and file reading logic to librubyparser

- src/yarp.c
> Handle invalid multiple parameters

- config.yml
- lib/yarp/lex_compat.rb
- src/yarp.c
- test/fixtures/method_calls.txt
- test/newline_test.rb
- test/snapshots/method_calls.txt
> Handle parsing foo &:bar correctly

- ext/yarp/extension.c
- lib/yarp.rb
- test/memsize_test.rb
- test/parse_test.rb
- test/regexp_test.rb
- test/unescape_test.rb
> Hide debug methods

- src/yarp.c
> Rework the list lexer to check terminators properly

- .github/workflows/main.yml
- src/util/yp_string.c
- src/yarp.c
> Fix warnings found from gcc-analyzer and clang-analyzer

- templates/java/org/yarp/Loader.java.erb
Didn't see that this was failing because the TruffleRuby build marked the whole thing as red.
> Fix JRuby build

- src/yarp.c
> Syntax error for double block arguments

- src/yarp.c
- test/fixtures/ternary_operator.txt
- test/snapshots/ternary_operator.txt
> Fix ternary operator immediately followed by underscore

- config.yml
- src/yarp.c
- templates/lib/yarp/node.rb.erb
- test/snapshots/not.txt
- test/snapshots/seattlerb/flip2_env_lvar.txt
- test/snapshots/unparser/corpus/literal/flipflop.txt
- test/snapshots/unparser/corpus/semantic/and.txt
- test/snapshots/whitequark/cond_eflipflop.txt
- test/snapshots/whitequark/cond_iflipflop.txt
> FlipFlopNode as opposed to flip flop flag

- test/fixtures/dash_heredocs.txt
- test/snapshots/dash_heredocs.txt
> Add test for empty heredoc

- Gemfile
- Gemfile.lock
- lib/yarp.rb
- lib/yarp/ffi.rb
Follow-up of https://github.com/ruby/yarp/pull/1250
> Small cleanups for the FFI backend

- src/yarp.c
- test/snapshots/tilde_heredocs.txt
- test/snapshots/unparser/corpus/semantic/dstr.txt
- test/snapshots/whitequark/parser_drops_truncated_parts_of_squiggly_heredoc.txt
This mirrors what happens in CRuby and the whitequark/parser gem.
> Drop empty strings from tilde heredocs

- README.md
...so that the links work as expected.
> adjust doc links in `README.md`

- src/yarp.c
- test/fixtures/heredoc_with_escaped_newline_at_start.txt
- test/snapshots/heredoc_with_escaped_newline_at_start.txt
Found via: https://github.com/BlakeWilliams/backbone_handlebars/blob/master/lib/backbone_handlebars/template.rb#L30
> handle missing HEREDOC endline at start of heredoc

- src/yarp.c
In many places in the code we use the idiom:
x < parser->end && *x == 'y'
which is essentially an extension of an existing pattern:
- `peek()` looks at `parser->current.end`
- `peek_at()` looks at `(parser->current.end + offset)`
This commit introduces a new inline function, `peek_addr`, which accepts a pointer and encapsulates the address value check and conditional dereferencing. The result is more readable code, and more ubiquitous safety checks on pointer values, allowing us to rewrite the above as:
peek_addr(parser, x) == 'y'
Also:
- change the type of `peek_at()`'s offset argument from `size_t` to `ptrdiff_t` so that it can accept negative offsets.
- use `current_token_starts_line` in one place where the equivalent code is inline.
These changes simplify the code and make it easier …
> refactor: extract `peek_addr()`

- include/yarp.h
- src/yarp.c
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
* Ensure the node gets initialized in case of failure with no assertions
* Include lambda and top-level nodes for scopes
* Small indentation fixes
> A couple small stylistic updates for yp_scope_node

- test/yarp/ruby_api_test.rb
...as pointed out by @eregon in post-review comments for #1360.
> use a more idiomatic form of `assert_raises`

- bin/lex
- rakelib/lex.rake
- test/yarp/bom_test.rb
- test/yarp/comments_test.rb
- test/yarp/desugar_visitor_test.rb
- test/yarp/encoding_test.rb
- test/yarp/errors_test.rb
- test/yarp/fuzzer_test.rb
- test/yarp/heredoc_dedent_test.rb
- test/yarp/library_symbols_test.rb
- test/yarp/locals_test.rb
- test/yarp/location_test.rb
- test/yarp/memsize_test.rb
- test/yarp/newline_test.rb
- test/yarp/parse_serialize_test.rb
- test/yarp/parse_test.rb
- test/yarp/regexp_test.rb
- test/yarp/ripper_compat_test.rb
- test/yarp/ruby_api_test.rb
- test/yarp/test_helper.rb
- test/yarp/unescape_test.rb
- test/yarp/version_test.rb
Easiest to review without whitespace changes. This is just me trying to be a good citizen within CRuby where right now names might conflict.
> Nest all of the YARP tests under the YARP namespace

- src/unescape.c
We don't need to pass in a destination pointer _and_ a `write_to_str` boolean flag.
> simplify the calling convention for `unescape`

- config.yml
- include/yarp.h
- src/yarp.c
- test/yarp/snapshots/unparser/corpus/literal/dstr.txt
- test/yarp/snapshots/unparser/corpus/literal/variables.txt
- test/yarp/snapshots/whitequark/nth_ref.txt
> Add a value to numbered references

- src/yarp.c
- test/yarp/errors_test.rb
> Better handle invalid gvar write

- .github/workflows/main.yml
Also cache the valgrind directory
> Fix valgrind installs for memcheck action

- include/yarp/enc/yp_encoding.h
- src/enc/yp_unicode.c
Read-only data tables are better than writable data tables.
> make some encoding tables `const`

- src/yarp.c
- test/yarp/errors_test.rb
> Handle invalid operator write on fcall

- src/yarp.c
- test/yarp/fixtures/arithmetic.txt
- test/yarp/snapshots/arithmetic.txt
> Fix up unary minus precedence

- src/yarp.c
- test/yarp/errors_test.rb
> Properly handle missing method names

- src/yarp.c
- test/yarp/fixtures/case.txt
- test/yarp/snapshots/case.txt
> Handle infinite opt terms after missing case predicate

- src/yarp.c
- test/yarp/errors_test.rb
> Handle missing terminators in parenthesized expression

- src/yarp.c
- test/yarp/errors_test.rb
> Handle unterminated interpolated symbol

- src/yarp.c
- test/yarp/errors_test.rb
> Alnum cannot be %-literal delimiters

- src/yarp.c
- test/yarp/errors_test.rb
Fixes #780
Fixes #1487
Fixes #1470
> Ensure multi targets are only in valid locations

- lib/yarp.rb
Respect the current indentation
> Better Node#pretty_print

- test/yarp/parse_test.rb
https://github.com/ruby/yarp/pull/1551#discussion_r1330427847
> Only use Ripper on CRuby

- src/yarp.c
> Fix segfault in argument parsing for brackets

- src/yarp.c
> Fix crashes in parsing block arguments

- rust/prism/build.rs
Using iteration here is clearer.
> [rust] use iteration rather than mutation

- src/prism.c
- test/prism/errors_test.rb
> Fix parsing shadow args in lambda blocks

- src/prism.c
- test/prism/fixtures/super.txt
- test/prism/snapshots/super.txt
> Fix up super with a blockarg

- src/prism.c
- test/prism/fixtures/regex.txt
- test/prism/snapshots/regex.txt
> Use the unescaped regexp to scan for capture groups

- lib/prism/lex_compat.rb
- test/prism/fixtures/tilde_heredocs.txt
- test/prism/heredoc_dedent_test.rb
- test/prism/snapshots/tilde_heredocs.txt
> Fix lex compat when dedent should be 0

- src/prism.c
See https://github.com/ruby/ruby/pull/8752 for context
> Add PostExecutionNode to pm_scope_node_init

- src/prism.c
- test/prism/fixtures/methods.txt
- test/prism/snapshots/methods.txt
> Forward parameters into arrays

- src/prism.c
- test/prism/errors_test.rb
> Disallow assigning to numbered parameters in regexp

- src/prism.c
- test/prism/fixtures/while.txt
- test/prism/snapshots/while.txt
> Reset do_loop_stack around a body of a endless method definition

- .gitignore
- bin/dot
- docs/configuration.md
- docs/ruby_api.md
- lib/prism.rb
- prism.gemspec
- templates/lib/prism/dot_visitor.rb.erb
- templates/lib/prism/node.rb.erb
- templates/template.rb
Just using this for my RubyConf talk but I figured I'd upstream it anyway.
> Add the ability to convert nodes to dot

- fuzz/parse.c
Was broken by a typo in 13fa2626
> dev: Fix the fuzzing harness

- src/prism.c
- test/prism/fuzzer_test.rb
> fix: float suffix at end of file

- Makefile
- docs/building.md
> Turn off missing braces warning

- src/prism.c
Fixes #1592
Previously we were inconsistent with the lex modes we were pushing so we would fail an assertion here.
> More consistent lex modes with %q

- test/prism/fixtures/case.txt
- test/prism/snapshots/case.txt
Fix #1515
It is also fixed by #1807, so this adds only test cases.
> Add test cases for `in` in `case` condition

- include/prism/enc/pm_encoding.h
- prism.gemspec
- rakelib/check_manifest.rake
- src/enc/pm_cp51932.c
- src/prism.c
- test/prism/encoding_test.rb
https://www.iana.org/assignments/charset-reg/CP51932
Resolves: https://github.com/ruby/prism/issues/1844
> Add CP51932 encoding 

- src/prism.c
- test/prism/errors_test.rb
> Do not allow trailing commas in calls without parenthesis

- include/prism/defines.h
- templates/java/org/prism/Loader.java.erb
- templates/lib/prism/serialize.rb.erb
- templates/src/serialize.c.erb
So that it's portable to other machines
> Ensure serialized file is little endian

- src/prism.c
- test/prism/errors_test.rb
> Disallow defining a numbered parameter method

- include/prism/diagnostic.h
- lib/prism/ffi.rb
- src/diagnostic.c
- src/prism.c
- test/prism/errors_test.rb
> Warning for ENDs in methods

- src/prism.c
- test/prism/errors_test.rb
> Fix `..` and `...` to be non-associative

- docs/encoding.md
- include/prism/enc/pm_encoding.h
- prism.gemspec
- src/enc/pm_cp949.c
- src/prism.c
- test/prism/encoding_test.rb
Adds [CP949](https://en.wikipedia.org/wiki/Code_page_949_(IBM)) encoding (#1843)
> Add CP949 encoding

- src/prism.c
- test/prism/errors_test.rb
Follow up on the ruby/ruby#8917 change.
> Check void values in singleton class (`class <<`)

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
> Fix LocalVariableTargetNode depth in patterns

- docs/encoding.md
- include/prism/enc/pm_encoding.h
- prism.gemspec
- src/enc/pm_cp950.c
- src/prism.c
- test/prism/encoding_test.rb
helps https://github.com/ruby/prism/issues/1843
> added CP950 encoding

- src/prism.c
> Fix typo in comment

- rust/prism/build.rs
- rust/prism/src/lib.rs
When writing visitors in Rust, I have found cases where I want to maintain a stack of nodes as I walk through the tree (e.g. to implement something like `rubocop-ast`'s `Node#parent`), and it's tedious to write visitor methods for all possible node types.  (It might also be inefficient, as we might be pushing and popping nodes when it doesn't matter -- you could maintain a list of such nodes yourself, but that seems to go against the spirit of visitors.)
This PR adds such functionality to the `Visit` trait: pre- and post-traversal hooks for child-ful and leaf nodes.
I'm reasonably sure the types for the hooks are correct; we don't want:
* references to the concrete node types, because that makes the hooks kind of useless.  (I did consider making the concrete node classes implement a …
> [rust] add pre- and post-traversal hooks to `Visit`

- lib/prism/node_ext.rb
- test/prism/ruby_api_test.rb
cc @paracycle I remember you asking for this
> Provide heredoc? queries

- src/prism.c
- test/prism/errors_test.rb
> Check "void value expression" for array literals

- ext/prism/extconf.rb
`gem 'prism', github: 'ruby/prism'` fails to bundle install with:
```
extconf.rb:57:in `<main>': prism.h is required (RuntimeError)
```
mkmf.log:
```
fatal error: prism/ast.h: No such file or directory
```
This pull request changes to generate templates before `find_header("prism.h", dir)`.
> Fix git source build

- src/prism.c
> Correct escapes when ctrl+meta+escape

- config.yml
- src/prism.c
- test/prism/attribute_write_test.rb
- test/prism/snapshots/arrays.txt
- test/prism/snapshots/method_calls.txt
- test/prism/snapshots/seattlerb/attr_asgn_colon_id.txt
- test/prism/snapshots/seattlerb/attrasgn_array_arg.txt
- test/prism/snapshots/seattlerb/attrasgn_array_lhs.txt
- test/prism/snapshots/seattlerb/attrasgn_primary_dot_constant.txt
- test/prism/snapshots/seattlerb/eq_begin_why_wont_people_use_their_spacebar.txt
- test/prism/snapshots/seattlerb/index_0.txt
- test/prism/snapshots/seattlerb/safe_attrasgn.txt
- test/prism/snapshots/seattlerb/safe_attrasgn_constant.txt
- test/prism/snapshots/unparser/corpus/literal/assignment.txt
- test/prism/snapshots/unparser/corpus/literal/case.txt
- test/prism/snapshots/unparser/corpus/literal/opasgn.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/whitequark/send_attr_asgn.txt
- test/prism/snapshots/whitequark/send_attr_asgn_conditional.txt
- test/prism/snapshots/whitequark/send_index_asgn.txt
- test/prism/snapshots/whitequark/send_index_asgn_legacy.txt
> Flag for attribute write on calls

- .gitignore
- javascript/package.json
> Inline type definitions into src directory for JS

- src/prism.c
- test/prism/errors_test.rb
> Better error recovery for content after unterminated heredoc

- src/prism.c
- test/prism/errors_test.rb
> Handle parsing a line break in a receiver of a method

- config.yml
This PR adds documentation comments in `config.yml` for `RangeNode`'s fields.
> Document `RangeNode` fields

- src/prism.c
> Allow fsl comment to set to false

- include/prism/util/pm_constant_pool.h
- src/prism.c
- src/util/pm_constant_pool.c
> Fix nested default value error

- .github/workflows/github-pages.yml
- .github/workflows/javascript-bindings.yml
- .github/workflows/main.yml
- .github/workflows/ruby-core.yml
- .github/workflows/rust-bindings.yml
- .github/workflows/truffleruby.yml
This PR updates to latest checkout action version
> Update checkout action version

- config.yml
> Document AndNode and OrNode

- src/prism.c
> Static literal flag for string hash keys

- .github/workflows/java-wasm-bindings.yml
- .github/workflows/main.yml
- Makefile
- java-wasm/.gitignore
- java-wasm/pom.xml
- java-wasm/src/test/java/org/prism/DummyTest.java
- java-wasm/src/test/resources/.gitignore
- rakelib/check_manifest.rake
Hi all 👋 !
Amazing project 🙂 !
In this PR we produce an unoptimized version of Prism that can be interpreted using the early stage build of [Chicory](https://github.com/dylibso/chicory).
The produced `prism.wasm` artifact is uploaded in CI for easy access.
> Test the generated wasm distribution on Chicory

- .github/dependabot.yml
- .github/workflows/java-wasm-bindings.yml
- java-wasm/pom.xml
- java-wasm/src/test/java/org/prism/DummyTest.java
cc. @enebo those are the breaking changes we have been speaking about.
I also added an entry to dependabot to keep current the Java dependencies
> Bump Chicory to the latest release

- src/prism.c
- test/prism/fixtures/rescue.txt
- test/prism/snapshots/rescue.txt
> Fix binding power for modifier rescue

- src/prism.c
> Only warn for unary + on spcarg

- CHANGELOG.md
- Gemfile.lock
- ext/prism/extension.c
- ext/prism/extension.h
- include/prism/options.h
- include/prism/parser.h
- include/prism/version.h
- java/org/prism/ParsingOptions.java
- javascript/package.json
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- prism.gemspec
- rust/Cargo.lock
- rust/ruby-prism-sys/Cargo.toml
- rust/ruby-prism-sys/tests/utils_tests.rs
- rust/ruby-prism/Cargo.toml
- sig/prism_static.rbs
- src/options.c
- src/prism.c
- templates/java/org/prism/Loader.java.erb
- templates/javascript/src/deserialize.js.erb
- templates/lib/prism/serialize.rb.erb
Fixes https://github.com/ruby/prism/issues/2285.
> Bump to version 0.20.0

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2029
> Reject operator writes on operator methods

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2343
> Handle missing begin body in method definition receiver

- src/prism.c
- test/prism/fixtures/rescue.txt
- test/prism/snapshots/rescue.txt
> Fix parsing rescue modifier

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2436
> Fix pattern with constant, (, and newlines

- test/prism/desugar_compiler_test.rb
* The #visit method is no longer called for every node since 2e6baa3.
* As a consequence EnsureEveryNodeOnceInAST was only visiting ProgramNode for `visitor.visit(ast)` and no nodes at all for `ast.accept(visitor)`.
Related: #2433
> Fix visitor in desugar test

- Makefile
- ext/prism/extension.c
- include/prism/options.h
- include/prism/util/pm_constant_pool.h
- src/diagnostic.c
- src/options.c
- src/prism.c
- src/util/pm_buffer.c
- src/util/pm_constant_pool.c
- src/util/pm_newline_list.c
Fixes https://github.com/ruby/prism/issues/2181
> Fix up GCC analyzer

- ext/prism/extension.c
- include/prism/util/pm_integer.h
- src/util/pm_integer.c
- templates/src/node.c.erb
- templates/src/prettyprint.c.erb
- test/prism/integer_parse_test.rb
We're going to need this to exactly match the warnings.
> Convert pm_integer_t to strings

- src/prism.c
- test/prism/fixtures/multi_write.txt
- test/prism/ruby_parser_test.rb
- test/prism/snapshots/multi_write.txt
Fixes https://github.com/ruby/prism/issues/2500
> Fix multi write with modifier rescue

- lib/prism/node_ext.rb
- lib/prism/translation/parser/compiler.rb
Fixes https://github.com/ruby/prism/issues/2498
> Fix xstring heredoc parser translator

- bin/prism
- lib/prism/translation.rb
- lib/prism/translation/parser.rb
- lib/prism/translation/parser/lexer.rb
- lib/prism/translation/parser33.rb
- lib/prism/translation/parser34.rb
- test/prism/parser_test.rb
Fixes https://github.com/ruby/prism/issues/2467
Fixes https://github.com/ruby/prism/issues/2510
> Fix up some minor parser incompatibilities

- config.yml
- lib/prism/translation/parser/compiler.rb
- src/prism.c
- test/prism/snapshots/case.txt
- test/prism/snapshots/seattlerb/bug_case_when_regexp.txt
- test/prism/snapshots/seattlerb/bug_cond_pct.txt
- test/prism/snapshots/seattlerb/when_splat.txt
- test/prism/snapshots/unparser/corpus/literal/case.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/whitequark/case_cond.txt
- test/prism/snapshots/whitequark/case_cond_else.txt
- test/prism/snapshots/whitequark/case_expr.txt
- test/prism/snapshots/whitequark/case_expr_else.txt
- test/prism/snapshots/whitequark/when_multi.txt
- test/prism/snapshots/whitequark/when_splat.txt
- test/prism/snapshots/whitequark/when_then.txt
Fixes https://github.com/ruby/prism/issues/2533
> Add then keyword loc to when nodes

- Rakefile
- ext/prism/extconf.rb
Fixes https://github.com/ruby/prism/issues/2527 again, in theory
> Use gmake on openbsd

- javascript/test.js
- templates/javascript/src/deserialize.js.erb
Fixes https://github.com/ruby/prism/issues/2545
> Fix double parsing in JS

- include/prism/node.h
- templates/src/node.c.erb
Fixes https://github.com/ruby/prism/issues/2543
> Provide API for visiting in C

- include/prism/util/pm_integer.h
- src/prism.c
- src/util/pm_constant_pool.c
see https://github.com/ruby/ruby/pull/10177
> Forward-port from ruby repo

- include/prism/parser.h
- src/prism.c
- test/prism/ruby_parser_test.rb
- test/prism/snapshots/heredocs_with_ignored_newlines.txt
- test/prism/snapshots/whitequark/parser_bug_640.txt
- test/prism/snapshots/whitequark/slash_newline_in_heredocs.txt
- test/prism/unescape_test.rb
Fixes https://github.com/ruby/prism/issues/2074
cc @enebo
> Fix up tilde heredoc line continuations

- docs/serialization.md
- ext/prism/extension.c
- include/prism/options.h
- java-wasm/src/test/java/org/prism/DummyTest.java
- java/org/prism/ParsingOptions.java
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- rbi/prism.rbi
- src/options.c
- src/prism.c
- templates/sig/prism.rbs.erb
- test/prism/ruby_api_test.rb
> Support offset

- lib/prism/translation/parser/lexer.rb
> Fix some whitequark/parser lexer compatibilities

- src/prism.c
- templates/src/diagnostic.c.erb
> Fix calloc argument order

- src/prism.c
- test/prism/errors_test.rb
Fixes https://github.com/ruby/prism/issues/2673
> Fix up invalid global variable error message

- bin/prism
- lib/prism/translation/parser/compiler.rb
Fixes https://github.com/ruby/prism/issues/2715
> Fix it parameters for parser translation

- lib/prism/translation/ruby_parser.rb
Fixes https://github.com/ruby/prism/issues/2713
Fixes https://github.com/ruby/prism/issues/2712
> Fix up ruby_parser translation for dstr

- config.yml
This one seems pretty simple. LMK if I should expand some of the comments.
> Document `BreakNode` fields

- config.yml
Adds documentation for the fields of `UnlessNode`.
> Document `UnlessNode` fields

- lib/prism/translation/parser/compiler.rb
Fixes https://github.com/ruby/prism/pull/2552
> srange_find should only look on current line

- Rakefile
- lib/prism/polyfill/string.rb
@seven1m this should remove the need for those patches you're keeping in https://github.com/natalie-lang/natalie/tree/master/ext/prism-patches
> Remove need for Natalie patches

- lib/prism/parse_result.rb
- rbi/prism/parse_result.rbi
- sig/prism/parse_result.rbs
- templates/lib/prism/node.rb.erb
- templates/rbi/prism/node.rbi.erb
- templates/sig/prism/node.rbs.erb
* `Node#source_lines` and alias `Node#script_lines`
* `Location#source_lines`
* `Source#lines`
> Node#script_lines and supporting infra

- .github/workflows/cpp-bindings.yml
- cpp/test.cpp
- rakelib/check_manifest.rake
This PR adds a test to CI ensuring that the Prism C API is functional in a C++ environment.
> Test support for C++

- lib/prism/translation/ruby_parser.rb
- test/prism/ruby_parser_test.rb
Fixes https://github.com/ruby/prism/issues/2828
> Fix up ruby_parser interpolation concatenation

- include/prism/static_literals.h
- src/prism.c
- src/static_literals.c
- templates/src/diagnostic.c.erb
- test/prism/warnings_test.rb
Pending https://github.com/ruby/ruby/pull/10776
> Update duplicated when error message

- src/prism.c
That do not have interpolation.
Fixes https://github.com/ruby/prism/issues/2634
> Allow quotes symbols in hash patterns

- src/prism.c
Fixes https://github.com/ruby/prism/issues/2018
> Reject additional patterns under splat in target

- config.yml
This one was pretty much the same as `MultiWriteNode`. Another one for #2123
> Document MultiWriteNode fields

- sample/prism/make_tags.rb
Fixes https://github.com/ruby/prism/issues/2960
Hey @teoljungberg — happy to provide a sample of code that would do what you're asking (included in this PR). I don't have the bandwidth to maintain it as a separate project, but you're more than welcome to grab it up and publish it as a gem if you like. Alternatively, you can grab the script out of this repo that will now contain it.
> Add sample for generating tags

- ext/prism/extension.c
- test/prism/api/lex_test.rb
- test/prism/api/parse_test.rb
Fixes https://github.com/ruby/prism/issues/2984
> Fix up lex result constants

- ext/prism/extension.c
Just some minor perf opportunities I spotted while working on other stuff.
> Optimize Array allocations

- config.yml
- src/prism.c
- test/prism/snapshots/arrays.txt
- test/prism/snapshots/constants.txt
- test/prism/snapshots/method_calls.txt
- test/prism/snapshots/methods.txt
- test/prism/snapshots/return.txt
- test/prism/snapshots/unparser/corpus/literal/assignment.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/unparser/corpus/literal/since/32.txt
- test/prism/snapshots/whitequark/args_args_star.txt
- test/prism/snapshots/whitequark/args_star.txt
- test/prism/snapshots/whitequark/forwarded_argument_with_restarg.txt
- test/prism/snapshots/whitequark/forwarded_restarg.txt
If we have a splat, add a flag for it named `contains_splat`.
> Add `contains_splat` flag

- src/prism.c
Fixes [Bug #20747]
Fixes https://github.com/ruby/prism/issues/3065
> Handle retry doubly nested under rescue

- src/prism.c
- test/prism/fixtures/methods.txt
- test/prism/snapshots/methods.txt
Fixes https://github.com/ruby/prism/issues/3074
> Allow returns in default parameter values

- src/prism.c
Fixes https://github.com/ruby/prism/issues/3072
> Accept "do" blocks in some parameter default values

- include/prism/options.h
- javascript/src/parsePrism.js
- lib/prism/ffi.rb
- src/options.c
- test/prism/api/parse_test.rb
- test/prism/version_test.rb
> Accept version shorthand like 3.4

- rakelib/cargo.rake
Fixes https://github.com/ruby/prism/issues/3078
> Remove vendor directory for rust build

- src/prism.c
- test/prism/errors/void_value_expression_in_begin_statement.txt
Fixes https://github.com/ruby/prism/issues/3064
> Fix up void value expression checking for rescue

- templates/include/prism/ast.h.erb
| Before | After |
|--------|-------|
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/8fce1068-9154-44e2-ad46-d599aba538e6"> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/9bac1009-30bb-46c7-ad60-b51420ed9025"> |
> Fix rendering of type overview docs

- src/prism.c
- test/prism/fixtures/patterns.txt
- test/prism/snapshots/patterns.txt
> No implicit , in pattern expressions on newline

- src/prism.c
Partially addresses https://github.com/ruby/prism/issues/3098
> Disallow empty labels when not allowed

- src/prism.c
- test/prism/fixtures/range_beginless.txt
- test/prism/snapshots/range_beginless.txt
Fixes https://github.com/ruby/prism/issues/3120
> Fix up beginless ranges in method definitions

- src/prism.c
Fixes https://github.com/ruby/prism/issues/3122
> Fix up binding power for singleton method receiver

- lib/prism/translation/parser.rb
- lib/prism/translation/ripper.rb
- lib/prism/translation/ruby_parser.rb
- rbi/prism.rbi
Followup to https://github.com/ruby/prism/pull/3079
> Use `partial_script` for the parser translators

- include/prism/parser.h
- src/prism.c
- test/prism/errors/heredoc_unterminated.txt
Fixes https://github.com/ruby/prism/issues/3133
> Pop lex mode for heredocs in the lexer, not the parser

- include/prism/parser.h
- src/prism.c
- test/prism/errors/multi_target_parens.txt
- test/prism/errors/multi_target_star.txt
Fixes https://github.com/ruby/prism/issues/2019
Fixes https://github.com/ruby/prism/issues/3132
> Fix up multi target parsing

- src/prism.c
Fixes https://github.com/ruby/prism/issues/3123
> Fix up pattern parsing with trailing commas

- src/prism.c
Fixes https://github.com/ruby/prism/issues/3144
Fixes https://github.com/ruby/prism/issues/3143
> Fix up errors on invalid escape character syntax

- config.yml
- lib/prism/translation/parser/compiler.rb
- src/prism.c
- test/prism/snapshots/break.txt
- test/prism/snapshots/command_method_call.txt
- test/prism/snapshots/method_calls.txt
- test/prism/snapshots/seattlerb/parse_until_not_canonical.txt
- test/prism/snapshots/seattlerb/parse_until_not_noncanonical.txt
- test/prism/snapshots/seattlerb/parse_while_not_canonical.txt
- test/prism/snapshots/seattlerb/parse_while_not_noncanonical.txt
- test/prism/snapshots/unparser/corpus/literal/send.txt
- test/prism/snapshots/unparser/corpus/literal/while.txt
- test/prism/snapshots/unparser/corpus/semantic/while.txt
- test/prism/snapshots/until.txt
- test/prism/snapshots/while.txt
- test/prism/snapshots/whitequark/bug_while_not_parens_do.txt
- test/prism/snapshots/whitequark/method_definition_in_while_cond.txt
- test/prism/snapshots/whitequark/until.txt
- test/prism/snapshots/whitequark/until_mod.txt
- test/prism/snapshots/whitequark/until_post.txt
- test/prism/snapshots/whitequark/while.txt
- test/prism/snapshots/whitequark/while_mod.txt
- test/prism/snapshots/whitequark/while_post.txt
Fixes https://github.com/ruby/prism/issues/3196
> Track do keyword for WhileNode/UntilNode

- src/prism.c
- test/prism/errors/arguments_splat_after_star_star.txt
> Fix splat after kwsplat in method calls

- config.yml
> Add document CallAndWriteNode fields

- src/prism.c
- test/prism/fixtures/lambda.txt
- test/prism/snapshots/lambda.txt
> Ignore newlines in labelled lambda arguments

- config.yml
> Add document ClassVariableAndWriteNode fields

- config.yml
> Add document CapturePatternNode fields

- ext/prism/extension.c
> Freeze `Prism::VERSION`

- src/prism.c
- test/prism/fixtures/rescue_modifier.txt
- test/prism/snapshots/rescue_modifier.txt
> Fix rescue modifier precedence

- lib/prism/parse_result/newlines.rb
- src/prism.c
- test/prism/errors/numbered_and_write.txt
- test/prism/errors/numbered_operator_write.txt
- test/prism/errors/numbered_or_write.txt
- test/prism/errors_test.rb
> No writing to numbered parameters

- ext/prism/extension.c
- lib/prism/ffi.rb
- templates/lib/prism/serialize.rb.erb
- test/prism/ractor_test.rb
@tenderlove does this look okay to you? I'm less familiar with Ractors, but wanted to make sure this was okay. From the documentation on Ractor safety, I believe this is okay?
> Mark extension as Ractor-safe

- test/prism/ractor_test.rb
https://github.com/ruby/prism/pull/3505#discussion_r2006053165
> Fix fork check in ractor_test.rb

- templates/java/org/prism/Loader.java.erb
- templates/java/org/prism/Nodes.java.erb
- templates/src/serialize.c.erb
Fixes https://github.com/ruby/prism/issues/3502
> Add node_id to Java serialization

- templates/java/org/prism/Loader.java.erb
- templates/java/org/prism/Nodes.java.erb
- templates/src/serialize.c.erb
- templates/template.rb
* See https://github.com/ruby/prism/issues/3502
> Include nodeId in Java Node only if necessary

- lib/prism/translation/parser/compiler.rb
- lib/prism/translation/ripper.rb
- src/prism.c
- test/prism/errors/defined_empty.txt
- test/prism/fixtures/defined.txt
- test/prism/snapshots/defined.txt
Fixes https://github.com/ruby/prism/issues/3510
> Accept a newline after the defined? keyword

- .github/workflows/java-wasm-bindings.yml
- Makefile
- java-wasm/pom.xml
- java-wasm/src/main/java/org/prism/Prism.java
- java-wasm/src/test/java/org/prism/DummyTest.java
Finally got it! :tada: :tada: :tada: 
@enebo I'm not 100% sure about the API that you'd like to expose, happy to do any required change or handover to you, but we should be able to publish this as a self-contained jar.
> Compile Prism to Bytecode with Chicory

- config.yml
- Adds documentation for the fields of the `ClassNode`.
- Part of #2123
> Document ClassNode fields

- java-wasm/pom.xml
- java-wasm/src/main/java/org/prism/Prism.java
Following the posted [migration guide](https://chicory.dev/blog/chicory-1.4.0#%EF%B8%8F-migration-guide).
Please feel free to ping me if it doesn't upgrade smoothly, always happy to have a look!
> Bump Chicory to 1.5.1
